import unittest

from app_core import postgresql_schema


def _column(
    position,
    name,
    declared_type,
    *,
    not_null=False,
    default=None,
    primary_key_position=0,
):
    return {
        "position": position,
        "name": name,
        "declared_type": declared_type,
        "not_null": not_null,
        "default": default,
        "primary_key_position": primary_key_position,
    }


class PostgreSQLSchemaTests(unittest.TestCase):
    def test_check_parser_handles_nested_calls_and_quoted_parenthesis(self):
        sql = """
            CREATE TABLE sample (
                value TEXT CHECK(value IN ('ok', 'texto ) valido')),
                amount INTEGER CHECK(COALESCE(amount, 0) >= 0)
            )
        """

        self.assertEqual(
            postgresql_schema.extract_check_expressions(sql),
            [
                "value IN ('ok', 'texto ) valido')",
                "COALESCE(amount, 0) >= 0",
            ],
        )

    def test_schema_generation_preserves_constraints_and_skips_redundant_index(self):
        inventory = {
            "tables": [
                {
                    "name": "Parent",
                    "create_sql": """
                        CREATE TABLE Parent (
                            ID INTEGER PRIMARY KEY AUTOINCREMENT,
                            Name TEXT NOT NULL UNIQUE CHECK(Name <> '')
                        )
                    """,
                    "columns": [
                        _column(
                            0,
                            "ID",
                            "INTEGER",
                            primary_key_position=1,
                        ),
                        _column(1, "Name", "TEXT", not_null=True),
                    ],
                    "indexes": [
                        {
                            "name": "sqlite_autoindex_Parent_1",
                            "unique": True,
                            "origin": "u",
                            "partial": False,
                            "columns": ["Name"],
                            "create_sql": None,
                        },
                        {
                            "name": "idx_parent_name",
                            "unique": False,
                            "origin": "c",
                            "partial": False,
                            "columns": ["Name"],
                            "create_sql": "CREATE INDEX idx_parent_name ON Parent(Name)",
                        },
                    ],
                    "foreign_keys": [],
                },
                {
                    "name": "Child",
                    "create_sql": """
                        CREATE TABLE Child (
                            id INTEGER PRIMARY KEY,
                            parent_id INTEGER REFERENCES Parent(ID)
                        )
                    """,
                    "columns": [
                        _column(
                            0,
                            "id",
                            "INTEGER",
                            primary_key_position=1,
                        ),
                        _column(1, "parent_id", "INTEGER"),
                    ],
                    "indexes": [
                        {
                            "name": "idx_child_parent_active",
                            "unique": False,
                            "origin": "c",
                            "partial": True,
                            "columns": ["parent_id"],
                            "create_sql": (
                                "CREATE INDEX idx_child_parent_active "
                                "ON Child(parent_id) WHERE parent_id IS NOT NULL"
                            ),
                        }
                    ],
                    "foreign_keys": [
                        {
                            "id": 0,
                            "position": 0,
                            "target_table": "Parent",
                            "source_column": "parent_id",
                            "target_column": "ID",
                            "on_update": "NO ACTION",
                            "on_delete": "NO ACTION",
                            "match": "NONE",
                        }
                    ],
                },
            ]
        }

        sql = postgresql_schema.generate_schema_sql(inventory)
        summary = postgresql_schema.expected_summary(inventory)

        self.assertIn('CREATE TABLE "parent"', sql)
        self.assertIn(
            '"id" bigint GENERATED BY DEFAULT AS IDENTITY',
            sql,
        )
        self.assertIn('CONSTRAINT "uq_parent_name" UNIQUE ("name")', sql)
        self.assertIn("CHECK (Name <> '')", sql)
        self.assertIn('REFERENCES "parent" ("id")', sql)
        self.assertIn(
            'CREATE INDEX "idx_child_parent_active" '
            'ON "child" ("parent_id") WHERE parent_id IS NOT NULL',
            sql,
        )
        self.assertNotIn('INDEX "idx_parent_name"', sql)
        self.assertEqual(summary["tables"], 2)
        self.assertEqual(summary["identity_columns"], 1)
        self.assertEqual(summary["explicit_indexes"], 1)

    def test_long_object_names_are_stable_and_fit_postgresql_limit(self):
        first = postgresql_schema.database_object_name(
            "fk",
            "uma_tabela_com_nome_extremamente_longo",
            "uma_coluna_com_nome_extremamente_longo",
            "outra_tabela_com_nome_extremamente_longo",
        )
        second = postgresql_schema.database_object_name(
            "fk",
            "uma_tabela_com_nome_extremamente_longo",
            "uma_coluna_com_nome_extremamente_longo",
            "outra_tabela_com_nome_extremamente_longo",
        )

        self.assertEqual(first, second)
        self.assertLessEqual(len(first), 63)


if __name__ == "__main__":
    unittest.main()
