-- Endemias - esquema PostgreSQL inicial
-- Gerado deterministicamente a partir do inventario estrutural SQLite.
-- Nao contem dados do sistema.

CREATE TABLE "acoes_setor" (
    "id_acao" bigint GENERATED BY DEFAULT AS IDENTITY,
    "tipo" text NOT NULL,
    "situacao" text NOT NULL DEFAULT 'realizada',
    "data" text NOT NULL,
    "data_fim" text,
    "periodo" text,
    "hora_inicio" text,
    "hora_fim" text,
    "caso" text,
    "localidade" text,
    "endereco" text,
    "local" text,
    "publico_aproximado" bigint,
    "tipo_atividade_realizada" text,
    "publico_alvo" text,
    "recurso_utilizado" text,
    "tema" text,
    "contexto" text,
    "resultados" text,
    "parceiros" text,
    "coordenadas" text,
    "observacoes" text,
    "criado_por" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text,
    CONSTRAINT "pk_acoes_setor" PRIMARY KEY ("id_acao"),
    CONSTRAINT "ck_acoes_setor_01" CHECK (tipo IN ('educativa','limpeza','vistoria','reuniao','outro')),
    CONSTRAINT "ck_acoes_setor_02" CHECK (situacao IN ('realizada','em_acompanhamento','planejada','cancelada'))
);

CREATE TABLE "acoes_setor_agentes" (
    "id_acao" bigint NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_acoes_setor_agentes" PRIMARY KEY ("id_acao", "id_agente")
);

CREATE TABLE "acoes_setor_anexos" (
    "id_anexo" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_acao" bigint NOT NULL,
    "nome_original" text NOT NULL,
    "nome_arquivo" text NOT NULL,
    "caminho_rel" text NOT NULL,
    "mime_type" text,
    "tamanho" bigint NOT NULL DEFAULT 0,
    "criado_por" text,
    "criado_em" text NOT NULL,
    "restrito" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "pk_acoes_setor_anexos" PRIMARY KEY ("id_anexo"),
    CONSTRAINT "ck_acoes_setor_anexos_01" CHECK (restrito IN (0,1))
);

CREATE TABLE "agenda_eventos" (
    "id_evento" bigint GENERATED BY DEFAULT AS IDENTITY,
    "titulo" text NOT NULL,
    "descricao" text,
    "tipo" text NOT NULL DEFAULT 'outro',
    "data_inicio" text NOT NULL,
    "data_fim" text,
    "dia_inteiro" bigint NOT NULL DEFAULT 0,
    "lembrete_min" bigint DEFAULT 60,
    "cor" text DEFAULT '#1a4fba',
    "criado_por" text,
    "criado_em" text NOT NULL,
    "recorrencia" text NOT NULL DEFAULT 'nenhuma',
    "recorrencia_fim" text,
    "atividade_externa" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "pk_agenda_eventos" PRIMARY KEY ("id_evento"),
    CONSTRAINT "ck_agenda_eventos_01" CHECK (tipo IN ('reuniao','planejamento','campo','prazo','treinamento','tarefa','ferias','outro')),
    CONSTRAINT "ck_agenda_eventos_02" CHECK (dia_inteiro IN (0,1)),
    CONSTRAINT "ck_agenda_eventos_03" CHECK (atividade_externa IN (0,1))
);

CREATE TABLE "agentes" (
    "id_agente" bigint GENERATED BY DEFAULT AS IDENTITY,
    "nome" text NOT NULL,
    "matricula" text,
    "cargo" text,
    "ativo" bigint NOT NULL DEFAULT 1,
    "data_inicio" text,
    "data_saida" text,
    "observacoes" text,
    "nome_completo" text,
    "cpf" text,
    "data_nascimento" text,
    CONSTRAINT "pk_agentes" PRIMARY KEY ("id_agente"),
    CONSTRAINT "uq_agentes_nome" UNIQUE ("nome"),
    CONSTRAINT "ck_agentes_01" CHECK (ativo IN (0,1))
);

CREATE TABLE "amostra_animais_agentes" (
    "id_amostra" text NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_amostra_animais_agentes" PRIMARY KEY ("id_amostra", "id_agente")
);

CREATE TABLE "amostras_animais" (
    "id_amostra" text,
    "kobo_uuid" text,
    "kobo_id" bigint,
    "data" date NOT NULL,
    "hora" time without time zone,
    "inicio_registro" text,
    "fim_registro" text,
    "agentes_texto" text,
    "motivo_visita" text,
    "animal_motivador" text,
    "animal_motivador_outro" text,
    "localidade" text,
    "id_localidade" bigint,
    "quarteirao" bigint,
    "tipo_imovel" text,
    "visita" text,
    "logradouro" text,
    "numero" text,
    "sequencia" text,
    "morador" text,
    "ocorrencia_residencia" text,
    "onde" text,
    "houve_acidente" text,
    "houve_captura" text,
    "local_captura" text,
    "tipo_animal" text,
    "animal_capturado" text,
    "especie_serpente" text,
    "especie_escorpiao" text,
    "especie_lagarta" text,
    "especie_aranha" text,
    "especie_carrapato" text,
    "especie_resumo" text,
    "quantidade" bigint DEFAULT 0,
    "origem_estrutura" text NOT NULL DEFAULT 'nova',
    "arquivo_origem" text,
    "submission_time" text,
    "processado_em" text NOT NULL,
    CONSTRAINT "pk_amostras_animais" PRIMARY KEY ("id_amostra"),
    CONSTRAINT "uq_amostras_animais_kobo_uuid" UNIQUE ("kobo_uuid")
);

CREATE TABLE "auditoria_eventos" (
    "id_evento" bigint GENERATED BY DEFAULT AS IDENTITY,
    "acao" text NOT NULL,
    "entidade" text,
    "entidade_id" text,
    "usuario_id" bigint,
    "usuario_nome" text,
    "ip" text,
    "detalhes_json" text NOT NULL DEFAULT '{}',
    "criado_em" text NOT NULL,
    CONSTRAINT "pk_auditoria_eventos" PRIMARY KEY ("id_evento")
);

CREATE TABLE "boletim_mensal_itens" (
    "id_item" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ano_mes" text NOT NULL,
    "chave" text NOT NULL,
    "origem" text NOT NULL DEFAULT 'manual',
    "ordem" bigint NOT NULL DEFAULT 0,
    "indicador" text NOT NULL,
    "quantidade" bigint NOT NULL DEFAULT 0,
    "unidade" text,
    "ativo" bigint NOT NULL DEFAULT 1,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_boletim_mensal_itens" PRIMARY KEY ("id_item"),
    CONSTRAINT "uq_boletim_mensal_itens_ano_mes_chave" UNIQUE ("ano_mes", "chave"),
    CONSTRAINT "ck_boletim_mensal_itens_01" CHECK (origem IN ('auto','manual')),
    CONSTRAINT "ck_boletim_mensal_itens_02" CHECK (ativo IN (0,1))
);

CREATE TABLE "bri_agentes" (
    "id_bri" text NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_bri_agentes" PRIMARY KEY ("id_bri", "id_agente")
);

CREATE TABLE "bri_registros" (
    "id_bri" text,
    "kobo_uuid" text,
    "kobo_id" bigint,
    "sispncd" text,
    "data" date NOT NULL,
    "hora" time without time zone,
    "inicio_registro" text,
    "fim_registro" text,
    "agentes_texto" text,
    "destino_tratamento" text,
    "local_tratamento" text,
    "localidade" text,
    "id_localidade" bigint,
    "logradouro" text,
    "quarteirao" bigint,
    "numero" text,
    "numero_ovitrampa" text,
    "quantidade_carga" double precision DEFAULT 0,
    "tratou_imovel_extra" text,
    "qual_imovel_extra" text,
    "depositos_tratados_extra" bigint,
    "quantidade_carga_extra" double precision DEFAULT 0,
    "origem_estrutura" text NOT NULL DEFAULT 'nova',
    "arquivo_origem" text,
    "submission_time" text,
    "processado_em" text NOT NULL,
    "id_pe" bigint,
    "codigo_pe" text,
    CONSTRAINT "pk_bri_registros" PRIMARY KEY ("id_bri"),
    CONSTRAINT "uq_bri_registros_kobo_uuid" UNIQUE ("kobo_uuid")
);

CREATE TABLE "coletas" (
    "id_coleta" text,
    "id_visita" text NOT NULL,
    "num_tubo" text,
    "codigo_deposito" text,
    "tipo_deposito" text,
    "deposito_eliminado" bigint,
    CONSTRAINT "pk_coletas" PRIMARY KEY ("id_coleta"),
    CONSTRAINT "ck_coletas_01" CHECK (deposito_eliminado IN (0,1))
);

CREATE TABLE "depositos_inspecionados" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_visita" text NOT NULL,
    "tipo_deposito" text NOT NULL,
    "inspecionado" bigint,
    "eliminado" bigint,
    "tratado" bigint,
    "tipo_tratamento" text,
    "qtd_carga" double precision,
    "is_historico" bigint DEFAULT 0,
    CONSTRAINT "pk_depositos_inspecionados" PRIMARY KEY ("id"),
    CONSTRAINT "uq_depositos_inspecionados_id_visita_tipo_deposito" UNIQUE ("id_visita", "tipo_deposito"),
    CONSTRAINT "ck_depositos_inspecionados_01" CHECK (is_historico IN (0,1))
);

CREATE TABLE "esporotricose_animais" (
    "id_animal" text,
    "id_visita" text NOT NULL,
    "kobo_uuid" text,
    "especie" text,
    "outro_animal" text,
    "nome" text,
    "raca" text,
    "sexo" text,
    "ambiente" text,
    "vacinado" text,
    "castrado" text,
    "feridas" text,
    "regiao_ferida" text,
    "atendimento_veterinario" text,
    "data_atendimento" date,
    "evolucao_caso" text,
    "arquivo_origem" text,
    "processado_em" text NOT NULL,
    "busca_ferido_data" date,
    "busca_ferido_agente" text,
    "busca_ferido_observacoes" text,
    CONSTRAINT "pk_esporotricose_animais" PRIMARY KEY ("id_animal"),
    CONSTRAINT "uq_esporotricose_animais_id_visita_kobo_uuid" UNIQUE ("id_visita", "kobo_uuid")
);

CREATE TABLE "esporotricose_buscas_ferido" (
    "id_busca" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_animal" text NOT NULL,
    "data_busca" date,
    "agente" text,
    "observacoes" text,
    "origem" text NOT NULL DEFAULT 'sistema',
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_esporotricose_buscas_ferido" PRIMARY KEY ("id_busca")
);

CREATE TABLE "esporotricose_doentes_anexos" (
    "id_anexo" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_animal_doente" bigint NOT NULL,
    "id_receita" bigint,
    "nome_original" text NOT NULL,
    "nome_arquivo" text NOT NULL,
    "caminho_rel" text NOT NULL,
    "mime_type" text,
    "tamanho" bigint NOT NULL,
    "criado_por" text,
    "criado_em" text NOT NULL,
    CONSTRAINT "pk_esporotricose_doentes_anexos" PRIMARY KEY ("id_anexo")
);

CREATE TABLE "esporotricose_doentes_animais" (
    "id_animal_doente" bigint GENERATED BY DEFAULT AS IDENTITY,
    "chave" text NOT NULL,
    "tutor" text,
    "nome" text NOT NULL,
    "sexo" text,
    "telefone" text,
    "localidade" text,
    "quarteirao" text,
    "endereco" text,
    "latitude" double precision,
    "longitude" double precision,
    "sinan" text,
    "status" text,
    "bloqueio" text,
    "data_bloqueio" date,
    "observacoes_entomologica" text,
    "pedido_zoomed" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    "especie" text,
    "cpf" text,
    "data_notificacao" date,
    CONSTRAINT "pk_esporotricose_doentes_animais" PRIMARY KEY ("id_animal_doente"),
    CONSTRAINT "uq_esporotricose_doentes_animais_chave" UNIQUE ("chave")
);

CREATE TABLE "esporotricose_doentes_entregas" (
    "id_entrega" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_receita" bigint NOT NULL,
    "quantidade" bigint NOT NULL,
    "data_entrega" date,
    "observacoes" text,
    "criado_em" text NOT NULL,
    "baixa_zoomed" text NOT NULL DEFAULT 'Sim',
    CONSTRAINT "pk_esporotricose_doentes_entregas" PRIMARY KEY ("id_entrega")
);

CREATE TABLE "esporotricose_doentes_origens" (
    "id_animal_visita" text,
    "id_animal_doente" bigint NOT NULL,
    "vinculado_em" text NOT NULL,
    CONSTRAINT "pk_esporotricose_doentes_origens" PRIMARY KEY ("id_animal_visita")
);

CREATE TABLE "esporotricose_doentes_receitas" (
    "id_receita" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_animal_doente" bigint NOT NULL,
    "data_notificacao" date,
    "inicio_sintomas" date,
    "data_receita" date,
    "visita_va_veterinario" date,
    "capsulas_total" bigint,
    "posologia" text,
    "status" text,
    "observacoes" text,
    "origem_linha" bigint,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    "capsulas_por_dia" double precision NOT NULL DEFAULT 1,
    "receita_pendente" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "pk_esporotricose_doentes_receitas" PRIMARY KEY ("id_receita")
);

CREATE TABLE "esporotricose_doentes_status" (
    "id_status" bigint GENERATED BY DEFAULT AS IDENTITY,
    "nome" text NOT NULL,
    "ativo" bigint NOT NULL DEFAULT 1,
    "criado_em" text NOT NULL,
    CONSTRAINT "pk_esporotricose_doentes_status" PRIMARY KEY ("id_status"),
    CONSTRAINT "uq_esporotricose_doentes_status_nome" UNIQUE ("nome"),
    CONSTRAINT "ck_esporotricose_doentes_status_01" CHECK (ativo IN (0,1))
);

CREATE TABLE "esporotricose_estoque_medicacao" (
    "id_movimento" bigint GENERATED BY DEFAULT AS IDENTITY,
    "data" date,
    "tipo" text NOT NULL,
    "quantidade" bigint NOT NULL,
    "descricao" text,
    "origem" text,
    "observacoes" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_esporotricose_estoque_medicacao" PRIMARY KEY ("id_movimento")
);

CREATE TABLE "esporotricose_visita_agentes" (
    "id_visita" text NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_esporotricose_visita_agentes" PRIMARY KEY ("id_visita", "id_agente")
);

CREATE TABLE "esporotricose_visitas" (
    "id_visita" text,
    "kobo_uuid" text NOT NULL,
    "kobo_id" bigint,
    "data" date NOT NULL,
    "hora_inicio" time without time zone,
    "hora_fim" time without time zone,
    "inicio_registro" text,
    "fim_registro" text,
    "agentes_texto" text,
    "localidade" text,
    "id_localidade" bigint,
    "quarteirao" bigint,
    "tipo_imovel" text,
    "logradouro" text,
    "numero" text,
    "morador" text,
    "visita" text,
    "telefone" text,
    "observacoes" text,
    "deseja_cadastrar_animal" text,
    "origem_estrutura" text NOT NULL DEFAULT 'nova',
    "arquivo_origem" text,
    "submission_time" text,
    "processado_em" text NOT NULL,
    CONSTRAINT "pk_esporotricose_visitas" PRIMARY KEY ("id_visita"),
    CONSTRAINT "uq_esporotricose_visitas_kobo_uuid" UNIQUE ("kobo_uuid")
);

CREATE TABLE "focos_historico" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_foco" text NOT NULL,
    "campo" text NOT NULL,
    "valor_ant" text,
    "valor_novo" text,
    "usuario" text,
    "alterado_em" text NOT NULL,
    CONSTRAINT "pk_focos_historico" PRIMARY KEY ("id")
);

CREATE TABLE "focos_positivos" (
    "id_foco" text,
    "id_visita" text,
    "id_coleta" text,
    "id_resultado" bigint,
    "num_tubo" text,
    "origem" text NOT NULL DEFAULT 'kobo',
    "tipo_trabalho" text,
    "data" text,
    "id_localidade" bigint,
    "localidade" text,
    "quarteirao" bigint,
    "logradouro" text,
    "numero" text,
    "complemento" text,
    "nome_morador" text,
    "tipo_imovel" text,
    "depositos" text,
    "agentes" text,
    "gera_notificacao" bigint NOT NULL DEFAULT 1,
    "status_notificacao" text DEFAULT 'pendente',
    "tentativa_1" text,
    "tentativa_2" text,
    "tentativa_3" text,
    "data_entrega" text,
    "observacoes" text,
    "processado_em" text,
    "codigo" text,
    CONSTRAINT "pk_focos_positivos" PRIMARY KEY ("id_foco"),
    CONSTRAINT "ck_focos_positivos_01" CHECK (status_notificacao IS NULL OR status_notificacao IN (
                'pendente','impressa','entregue',
                'morador não localizado','dados inconsistentes','arquivada'
            ))
);

CREATE TABLE "importacoes" (
    "id_importacao" bigint GENERATED BY DEFAULT AS IDENTITY,
    "job_id" text NOT NULL,
    "usuario" text,
    "arquivos_json" text NOT NULL DEFAULT '[]',
    "status" text NOT NULL DEFAULT 'upload',
    "dry_run_ok" bigint,
    "commit_ok" bigint,
    "sumario_json" text,
    "erro" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_importacoes" PRIMARY KEY ("id_importacao"),
    CONSTRAINT "uq_importacoes_job_id" UNIQUE ("job_id")
);

CREATE TABLE "laboratorio_coletas_status" (
    "id_coleta" text,
    "status" text NOT NULL,
    "motivo" text NOT NULL,
    "encerrado_em" text NOT NULL,
    "encerrado_por" bigint,
    CONSTRAINT "pk_laboratorio_coletas_status" PRIMARY KEY ("id_coleta"),
    CONSTRAINT "ck_laboratorio_coletas_status_01" CHECK (status IN ('sem_resultado'))
);

CREATE TABLE "localidades" (
    "id_localidade" bigint GENERATED BY DEFAULT AS IDENTITY,
    "nome" text NOT NULL,
    "cod_localidade" text,
    CONSTRAINT "pk_localidades" PRIMARY KEY ("id_localidade"),
    CONSTRAINT "uq_localidades_nome" UNIQUE ("nome")
);

CREATE TABLE "login_tentativas" (
    "chave" text,
    "tentativas" bigint NOT NULL DEFAULT 0,
    "primeira_em" double precision NOT NULL,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_login_tentativas" PRIMARY KEY ("chave")
);

CREATE TABLE "meteorologia_alertas_config" (
    "id" bigint,
    "expediente_inicio" bigint NOT NULL DEFAULT 8,
    "expediente_fim" bigint NOT NULL DEFAULT 17,
    "chuva_atencao_pct" double precision NOT NULL DEFAULT 50,
    "chuva_critica_mm_hora" double precision NOT NULL DEFAULT 5,
    "rajada_atencao_kmh" double precision NOT NULL DEFAULT 40,
    "rajada_critica_kmh" double precision NOT NULL DEFAULT 60,
    "sensacao_frio_atencao_c" double precision NOT NULL DEFAULT 7,
    "sensacao_frio_critica_c" double precision NOT NULL DEFAULT 3,
    "sensacao_calor_atencao_c" double precision NOT NULL DEFAULT 32,
    "sensacao_calor_critica_c" double precision NOT NULL DEFAULT 36,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_meteorologia_alertas_config" PRIMARY KEY ("id"),
    CONSTRAINT "ck_meteorologia_alertas_config_01" CHECK (id = 1)
);

CREATE TABLE "meteorologia_condicoes_atuais" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "observado_em" text NOT NULL,
    "fonte" text NOT NULL,
    "latitude" double precision,
    "longitude" double precision,
    "temperatura" double precision,
    "sensacao_termica" double precision,
    "umidade" double precision,
    "precipitacao" double precision,
    "velocidade_vento" double precision,
    "codigo_tempo" bigint,
    "periodo_dia" bigint,
    "bruto_json" text NOT NULL,
    "importado_em" text NOT NULL,
    CONSTRAINT "pk_meteorologia_condicoes_atuais" PRIMARY KEY ("id"),
    CONSTRAINT "uq_meteorologia_condicoes_atuais_observado_em_fonte" UNIQUE ("observado_em", "fonte"),
    CONSTRAINT "ck_meteorologia_condicoes_atuais_01" CHECK (periodo_dia IN (0,1))
);

CREATE TABLE "meteorologia_estacoes" (
    "codigo" text,
    "nome" text NOT NULL,
    "uf" text,
    "situacao" text,
    "tipo" text,
    "entidade" text,
    "latitude" double precision,
    "longitude" double precision,
    "altitude" double precision,
    "distancia_km" double precision,
    "papel" text NOT NULL DEFAULT 'referencia',
    "inicio_operacao" text,
    "fim_operacao" text,
    "fonte" text NOT NULL DEFAULT 'INMET',
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_meteorologia_estacoes" PRIMARY KEY ("codigo")
);

CREATE TABLE "meteorologia_previsoes_horarias" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "previsto_em" text NOT NULL,
    "fonte" text NOT NULL DEFAULT 'Open-Meteo',
    "temperatura" double precision,
    "sensacao_termica" double precision,
    "umidade" double precision,
    "probabilidade_chuva" double precision,
    "precipitacao" double precision,
    "codigo_tempo" bigint,
    "velocidade_vento" double precision,
    "rajada_vento" double precision,
    "importado_em" text NOT NULL,
    CONSTRAINT "pk_meteorologia_previsoes_horarias" PRIMARY KEY ("id"),
    CONSTRAINT "uq_meteorologia_previsoes_horarias_previsto_em_fonte" UNIQUE ("previsto_em", "fonte")
);

CREATE TABLE "meteorologia_resumos_diarios" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "data" date NOT NULL,
    "referencia" text NOT NULL,
    "fonte" text NOT NULL,
    "temperatura_min" double precision,
    "temperatura_max" double precision,
    "umidade_min" double precision,
    "precipitacao" double precision,
    "provisorio" bigint NOT NULL DEFAULT 0,
    "bruto_json" text NOT NULL,
    "importado_em" text NOT NULL,
    CONSTRAINT "pk_meteorologia_resumos_diarios" PRIMARY KEY ("id"),
    CONSTRAINT "uq_meteorologia_resumos_diarios_data_referencia_fonte" UNIQUE ("data", "referencia", "fonte"),
    CONSTRAINT "ck_meteorologia_resumos_diarios_01" CHECK (provisorio IN (0,1))
);

CREATE TABLE "meteorologia_sincronizacoes" (
    "id_sincronizacao" bigint GENERATED BY DEFAULT AS IDENTITY,
    "fonte" text NOT NULL,
    "status" text NOT NULL,
    "iniciado_em" text NOT NULL,
    "finalizado_em" text,
    "registros" bigint NOT NULL DEFAULT 0,
    "detalhes_json" text NOT NULL DEFAULT '{}',
    "erro" text,
    CONSTRAINT "pk_meteorologia_sincronizacoes" PRIMARY KEY ("id_sincronizacao")
);

CREATE TABLE "ovitrampas_armadilhas" (
    "ovitrampa_id" text,
    "rua" text,
    "numero" text,
    "complemento" text,
    "bairro" text,
    "localizacao" text,
    "localidade" text,
    "responsavel" text,
    "quarteirao" text,
    "latitude" double precision,
    "longitude" double precision,
    "arquivo_origem" text,
    "atualizado_em" text NOT NULL,
    "telefone_responsavel" text,
    "ativo" bigint NOT NULL DEFAULT 1,
    CONSTRAINT "pk_ovitrampas_armadilhas" PRIMARY KEY ("ovitrampa_id")
);

CREATE TABLE "ovitrampas_armadilhas_historico" (
    "id_historico" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ovitrampa_id" text NOT NULL,
    "campo" text NOT NULL,
    "valor_anterior" text,
    "valor_novo" text,
    "motivo" text,
    "agentes" text,
    "usuario" text,
    "arquivo_origem" text,
    "criado_em" text NOT NULL,
    CONSTRAINT "pk_ovitrampas_armadilhas_historico" PRIMARY KEY ("id_historico")
);

CREATE TABLE "ovitrampas_calendario_agentes" (
    "id_evento" bigint NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_ovitrampas_calendario_agentes" PRIMARY KEY ("id_evento", "id_agente")
);

CREATE TABLE "ovitrampas_calendario_eventos" (
    "id_evento" bigint GENERATED BY DEFAULT AS IDENTITY,
    "data" date NOT NULL,
    "movimento" text NOT NULL,
    "titulo" text,
    "id_grupo" bigint,
    "ciclo" text,
    "observacoes" text,
    "criado_por" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text,
    CONSTRAINT "pk_ovitrampas_calendario_eventos" PRIMARY KEY ("id_evento"),
    CONSTRAINT "uq_ovitrampas_calendario_eventos_data" UNIQUE ("data"),
    CONSTRAINT "ck_ovitrampas_calendario_eventos_01" CHECK (movimento IN ('instalacao','troca','retirada','feriado'))
);

CREATE TABLE "ovitrampas_calendario_grupos" (
    "id_grupo" bigint GENERATED BY DEFAULT AS IDENTITY,
    "nome" text NOT NULL,
    "localidades" text,
    "cor" text NOT NULL DEFAULT '#0f766e',
    "ativo" bigint NOT NULL DEFAULT 1,
    "criado_em" text NOT NULL,
    "atualizado_em" text,
    CONSTRAINT "pk_ovitrampas_calendario_grupos" PRIMARY KEY ("id_grupo"),
    CONSTRAINT "ck_ovitrampas_calendario_grupos_01" CHECK (ativo IN (0,1))
);

CREATE TABLE "ovitrampas_diario_armadilhas" (
    "id_diario" bigint NOT NULL,
    "ovitrampa_id" text NOT NULL,
    "ordem" bigint NOT NULL DEFAULT 0,
    "observacoes" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text,
    CONSTRAINT "pk_ovitrampas_diario_armadilhas" PRIMARY KEY ("id_diario", "ovitrampa_id")
);

CREATE TABLE "ovitrampas_diarios" (
    "id_diario" bigint GENERATED BY DEFAULT AS IDENTITY,
    "nome" text NOT NULL,
    "observacoes" text,
    "ativo" bigint NOT NULL DEFAULT 1,
    "criado_em" text NOT NULL,
    "atualizado_em" text,
    CONSTRAINT "pk_ovitrampas_diarios" PRIMARY KEY ("id_diario"),
    CONSTRAINT "uq_ovitrampas_diarios_nome" UNIQUE ("nome"),
    CONSTRAINT "ck_ovitrampas_diarios_01" CHECK (ativo IN (0,1))
);

CREATE TABLE "ovitrampas_laboratorio_itens" (
    "id_item" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_lote" bigint NOT NULL,
    "ovitrampa_id" text NOT NULL,
    "complemento" text,
    "localidade" text,
    "ovos" bigint NOT NULL DEFAULT 0,
    "atualizado_em" text,
    "ocorrencia" bigint,
    CONSTRAINT "pk_ovitrampas_laboratorio_itens" PRIMARY KEY ("id_item"),
    CONSTRAINT "uq_ovitrampas_laboratorio_itens_id_lote_ovitrampa_id" UNIQUE ("id_lote", "ovitrampa_id"),
    CONSTRAINT "ck_ovitrampas_laboratorio_itens_01" CHECK (ovos >= 0),
    CONSTRAINT "ck_ovitrampas_laboratorio_itens_02" CHECK (ocorrencia BETWEEN 1 AND 8)
);

CREATE TABLE "ovitrampas_laboratorio_lotes" (
    "id_lote" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_evento" bigint NOT NULL,
    "id_diario" bigint NOT NULL,
    "diario_nome" text NOT NULL,
    "data_movimento" date NOT NULL,
    "movimento" text NOT NULL,
    "ciclo" text,
    "status" text NOT NULL DEFAULT 'pendente',
    "id_laboratorista" bigint,
    "laboratorista_nome" text,
    "iniciado_em" text,
    "concluido_em" text,
    "enviado_conta_ovos_em" text,
    "enviado_conta_ovos_por" bigint,
    "enviado_por_nome" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_ovitrampas_laboratorio_lotes" PRIMARY KEY ("id_lote"),
    CONSTRAINT "uq_ovitrampas_laboratorio_lotes_id_evento_id_diario" UNIQUE ("id_evento", "id_diario"),
    CONSTRAINT "ck_ovitrampas_laboratorio_lotes_01" CHECK (movimento IN ('troca','retirada')),
    CONSTRAINT "ck_ovitrampas_laboratorio_lotes_02" CHECK (status IN ('pendente','em_preenchimento','concluido','enviado_conta_ovos'))
);

CREATE TABLE "ovitrampas_leituras" (
    "id_leitura" text,
    "ovitrampa_id" text NOT NULL,
    "estado" text,
    "municipio" text,
    "distrito" text,
    "rua" text,
    "numero" text,
    "complemento" text,
    "localizacao" text,
    "latitude" double precision,
    "longitude" double precision,
    "ano" bigint NOT NULL,
    "semana" bigint NOT NULL,
    "data_envio_contagem" text,
    "ovos" bigint DEFAULT 0,
    "quem_enviou" text,
    "observacao" text,
    "lat_lng" text,
    "quarteirao" text,
    "data_instalacao" date,
    "data_coleta" date,
    "arquivo_origem" text,
    "importado_em" text NOT NULL,
    "id_laboratorista" bigint,
    "data_leitura" date,
    "ocorrencia_codigo" bigint,
    CONSTRAINT "pk_ovitrampas_leituras" PRIMARY KEY ("id_leitura"),
    CONSTRAINT "uq_ovitrampas_leituras_ovitrampa_id_ano_semana_data__98191c0a0e" UNIQUE ("ovitrampa_id", "ano", "semana", "data_instalacao", "data_coleta", "data_envio_contagem")
);

CREATE TABLE "ovitrampas_ocorrencias_conta_ovos" (
    "id_contagem" text,
    "ovitrampa_id" text NOT NULL,
    "ano" bigint NOT NULL,
    "semana" bigint NOT NULL,
    "data" date,
    "data_envio_contagem" text,
    "ovos" bigint DEFAULT 0,
    "resultado" text,
    "codigo_conta_ovos" bigint,
    "observacao_conta_ovos" text,
    "ocorrencia_codigo" bigint,
    "latitude" double precision,
    "longitude" double precision,
    "lat_lng" text,
    "arquivo_origem" text,
    "importado_em" text NOT NULL,
    CONSTRAINT "pk_ovitrampas_ocorrencias_conta_ovos" PRIMARY KEY ("id_contagem")
);

CREATE TABLE "pontos_estrategicos" (
    "id_pe" bigint GENERATED BY DEFAULT AS IDENTITY,
    "codigo_pe" text NOT NULL,
    "localidade" text,
    "id_localidade" bigint,
    "quarteirao" bigint,
    "nome" text NOT NULL,
    "logradouro" text,
    "numero" text,
    "situacao" bigint NOT NULL DEFAULT 1,
    "data_inclusao" date,
    "data_desativacao" date,
    "cnpj" text,
    "razao_social" text,
    "telefone" text,
    "tipo" text,
    "latitude" double precision,
    "longitude" double precision,
    "observacoes" text,
    "chave_origem" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    CONSTRAINT "pk_pontos_estrategicos" PRIMARY KEY ("id_pe"),
    CONSTRAINT "uq_pontos_estrategicos_chave_origem" UNIQUE ("chave_origem"),
    CONSTRAINT "uq_pontos_estrategicos_codigo_pe" UNIQUE ("codigo_pe")
);

CREATE TABLE "pontos_estrategicos_alias" (
    "id_alias" bigint GENERATED BY DEFAULT AS IDENTITY,
    "alias_logradouro" text NOT NULL,
    "alias_normalizado" text NOT NULL,
    "localidade" text,
    "localidade_normalizada" text NOT NULL DEFAULT '',
    "codigo_pe" text NOT NULL,
    "observacoes" text,
    "ativo" bigint NOT NULL DEFAULT 1,
    "criado_em" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "atualizado_em" text NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "pk_pontos_estrategicos_alias" PRIMARY KEY ("id_alias"),
    CONSTRAINT "uq_pontos_estrategicos_alias_alias_normalizado_local_62e3037cc5" UNIQUE ("alias_normalizado", "localidade_normalizada"),
    CONSTRAINT "ck_pontos_estrategicos_alias_01" CHECK (ativo IN (0,1))
);

CREATE TABLE "recolhimento_agentes" (
    "id_recolhimento" text NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_recolhimento_agentes" PRIMARY KEY ("id_recolhimento", "id_agente")
);

CREATE TABLE "recolhimentos" (
    "id_recolhimento" text,
    "kobo_uuid" text,
    "kobo_id" bigint,
    "data" date NOT NULL,
    "hora" time without time zone,
    "inicio_registro" text,
    "fim_registro" text,
    "localidade" text,
    "id_localidade" bigint,
    "agentes_texto" text,
    "pneu" bigint DEFAULT 0,
    "louca_sanitaria" bigint DEFAULT 0,
    "tv" bigint DEFAULT 0,
    "parachoque" bigint DEFAULT 0,
    "outros" bigint DEFAULT 0,
    "total_materiais" bigint DEFAULT 0,
    "origem_estrutura" text NOT NULL DEFAULT 'nova',
    "arquivo_origem" text,
    "submission_time" text,
    "processado_em" text NOT NULL,
    CONSTRAINT "pk_recolhimentos" PRIMARY KEY ("id_recolhimento"),
    CONSTRAINT "uq_recolhimentos_kobo_uuid" UNIQUE ("kobo_uuid")
);

CREATE TABLE "registro_geografico_imoveis" (
    "id_imovel" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_quarteirao" bigint NOT NULL,
    "id_localidade" bigint NOT NULL,
    "localidade" text NOT NULL,
    "quarteirao" text NOT NULL,
    "logradouro" text NOT NULL,
    "numero" text NOT NULL DEFAULT 'SN',
    "sequencia" text,
    "lado" text,
    "tipo" text,
    "condominio" bigint,
    "observacao" text,
    "data_atualizacao" date,
    "agentes_texto" text,
    "chave_origem" text,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    "busca_normalizada" text,
    "ordem" bigint,
    CONSTRAINT "pk_registro_geografico_imoveis" PRIMARY KEY ("id_imovel"),
    CONSTRAINT "uq_registro_geografico_imoveis_chave_origem" UNIQUE ("chave_origem")
);

CREATE TABLE "registro_geografico_imovel_agentes" (
    "id_imovel" bigint NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_registro_geografico_imovel_agentes" PRIMARY KEY ("id_imovel", "id_agente")
);

CREATE TABLE "registro_geografico_quarteiroes" (
    "id_quarteirao" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_localidade" bigint NOT NULL,
    "localidade" text NOT NULL,
    "quarteirao" text NOT NULL,
    "criado_em" text NOT NULL,
    "atualizado_em" text NOT NULL,
    "atualizado_por_usuario_id" bigint,
    "atualizado_por_usuario_nome" text,
    "atualizado_por_em" text,
    CONSTRAINT "pk_registro_geografico_quarteiroes" PRIMARY KEY ("id_quarteirao"),
    CONSTRAINT "uq_registro_geografico_quarteiroes_id_localidade_quarteirao" UNIQUE ("id_localidade", "quarteirao")
);

CREATE TABLE "resultados_laboratorio" (
    "id_resultado" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_coleta" text NOT NULL,
    "num_tubo" text NOT NULL,
    "data_coleta" date NOT NULL,
    "laboratorista" text,
    "data_leitura" date,
    "aegypt_larvas" bigint DEFAULT 0,
    "aegypt_pupas" bigint DEFAULT 0,
    "aegypt_exuvias" bigint DEFAULT 0,
    "aegypt_adulto" bigint DEFAULT 0,
    "albopictus_larvas" bigint DEFAULT 0,
    "albopictus_pupas" bigint DEFAULT 0,
    "albopictus_exuvias" bigint DEFAULT 0,
    "albopictus_adulto" bigint DEFAULT 0,
    "outra_larvas" bigint DEFAULT 0,
    "outra_pupas" bigint DEFAULT 0,
    "outra_exuvias" bigint DEFAULT 0,
    "outra_adulto" bigint DEFAULT 0,
    "kobo_uuid" text,
    "id_laboratorista" bigint,
    "origem" text NOT NULL DEFAULT 'kobo',
    "criado_em" text,
    "atualizado_em" text,
    CONSTRAINT "pk_resultados_laboratorio" PRIMARY KEY ("id_resultado"),
    CONSTRAINT "uq_resultados_laboratorio_id_coleta" UNIQUE ("id_coleta"),
    CONSTRAINT "uq_resultados_laboratorio_kobo_uuid" UNIQUE ("kobo_uuid"),
    CONSTRAINT "ck_resultados_laboratorio_01" CHECK (origem IN ('kobo','sistema'))
);

CREATE TABLE "tratamentos" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "id_visita" text NOT NULL,
    "tipo" text,
    "quantidade_carga" double precision,
    "qtd_depositos_tratados" bigint,
    CONSTRAINT "pk_tratamentos" PRIMARY KEY ("id"),
    CONSTRAINT "uq_tratamentos_id_visita_tipo" UNIQUE ("id_visita", "tipo")
);

CREATE TABLE "usuarios" (
    "id_usuario" bigint GENERATED BY DEFAULT AS IDENTITY,
    "usuario" text NOT NULL,
    "nome" text NOT NULL,
    "senha_hash" text NOT NULL,
    "nivel" text NOT NULL DEFAULT 'visualizador',
    "ativo" bigint NOT NULL DEFAULT 1,
    "criado_em" text NOT NULL,
    "acesso_laboratorio" bigint NOT NULL DEFAULT 0,
    "somente_laboratorio" bigint NOT NULL DEFAULT 0,
    CONSTRAINT "pk_usuarios" PRIMARY KEY ("id_usuario"),
    CONSTRAINT "uq_usuarios_usuario" UNIQUE ("usuario"),
    CONSTRAINT "ck_usuarios_01" CHECK (nivel IN ('admin','operador','visualizador')),
    CONSTRAINT "ck_usuarios_02" CHECK (ativo IN (0,1)),
    CONSTRAINT "ck_usuarios_03" CHECK (acesso_laboratorio IN (0,1)),
    CONSTRAINT "ck_usuarios_04" CHECK (somente_laboratorio IN (0,1))
);

CREATE TABLE "visita_agentes" (
    "id_visita" text NOT NULL,
    "id_agente" bigint NOT NULL,
    CONSTRAINT "pk_visita_agentes" PRIMARY KEY ("id_visita", "id_agente")
);

CREATE TABLE "visitas" (
    "id_visita" text,
    "kobo_uuid" text NOT NULL,
    "kobo_id" bigint,
    "tipo" text NOT NULL,
    "data" date NOT NULL,
    "hora_inicio" time without time zone,
    "hora_fim" time without time zone,
    "ciclo" bigint,
    "localidade" text,
    "logradouro" text,
    "numero" text,
    "quarteirao" bigint,
    "sequencia" text,
    "morador" text,
    "tipo_imovel" text,
    "visita" text,
    "lado" text,
    "agua_sanepar" bigint,
    "observacoes" text,
    "submission_time" text,
    "processado_em" text NOT NULL,
    "id_localidade" bigint,
    "sispncd" varchar(20),
    "contaovos_status" bigint,
    "id_pe" bigint,
    "codigo_pe" text,
    CONSTRAINT "pk_visitas" PRIMARY KEY ("id_visita"),
    CONSTRAINT "ck_visitas_01" CHECK (tipo IN ('PE','TB','TBO','PVE')),
    CONSTRAINT "ck_visitas_02" CHECK (agua_sanepar IN (0,1))
);

-- Chaves estrangeiras sao adicionadas depois de todas as tabelas.
ALTER TABLE "acoes_setor_agentes" ADD CONSTRAINT "fk_acoes_setor_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "acoes_setor_agentes" ADD CONSTRAINT "fk_acoes_setor_agentes_id_acao_acoes_setor" FOREIGN KEY ("id_acao") REFERENCES "acoes_setor" ("id_acao") ON DELETE CASCADE;
ALTER TABLE "acoes_setor_anexos" ADD CONSTRAINT "fk_acoes_setor_anexos_id_acao_acoes_setor" FOREIGN KEY ("id_acao") REFERENCES "acoes_setor" ("id_acao") ON DELETE CASCADE;
ALTER TABLE "amostra_animais_agentes" ADD CONSTRAINT "fk_amostra_animais_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "amostra_animais_agentes" ADD CONSTRAINT "fk_amostra_animais_agentes_id_amostra_amostras_animais" FOREIGN KEY ("id_amostra") REFERENCES "amostras_animais" ("id_amostra") ON DELETE CASCADE;
ALTER TABLE "amostras_animais" ADD CONSTRAINT "fk_amostras_animais_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "bri_agentes" ADD CONSTRAINT "fk_bri_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "bri_agentes" ADD CONSTRAINT "fk_bri_agentes_id_bri_bri_registros" FOREIGN KEY ("id_bri") REFERENCES "bri_registros" ("id_bri") ON DELETE CASCADE;
ALTER TABLE "bri_registros" ADD CONSTRAINT "fk_bri_registros_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "coletas" ADD CONSTRAINT "fk_coletas_id_visita_visitas" FOREIGN KEY ("id_visita") REFERENCES "visitas" ("id_visita");
ALTER TABLE "depositos_inspecionados" ADD CONSTRAINT "fk_depositos_inspecionados_id_visita_visitas" FOREIGN KEY ("id_visita") REFERENCES "visitas" ("id_visita");
ALTER TABLE "esporotricose_animais" ADD CONSTRAINT "fk_esporotricose_animais_id_visita_esporotricose_visitas" FOREIGN KEY ("id_visita") REFERENCES "esporotricose_visitas" ("id_visita") ON DELETE CASCADE;
ALTER TABLE "esporotricose_buscas_ferido" ADD CONSTRAINT "fk_esporotricose_buscas_ferido_id_animal_esporotricose_animais" FOREIGN KEY ("id_animal") REFERENCES "esporotricose_animais" ("id_animal") ON DELETE CASCADE;
ALTER TABLE "esporotricose_doentes_anexos" ADD CONSTRAINT "fk_esporotricose_doentes_anexos_id_receita_esporotri_8ebeea017b" FOREIGN KEY ("id_receita") REFERENCES "esporotricose_doentes_receitas" ("id_receita") ON DELETE SET NULL;
ALTER TABLE "esporotricose_doentes_anexos" ADD CONSTRAINT "fk_esporotricose_doentes_anexos_id_animal_doente_esp_3528506e8e" FOREIGN KEY ("id_animal_doente") REFERENCES "esporotricose_doentes_animais" ("id_animal_doente") ON DELETE CASCADE;
ALTER TABLE "esporotricose_doentes_entregas" ADD CONSTRAINT "fk_esporotricose_doentes_entregas_id_receita_esporot_888820ab3e" FOREIGN KEY ("id_receita") REFERENCES "esporotricose_doentes_receitas" ("id_receita") ON DELETE CASCADE;
ALTER TABLE "esporotricose_doentes_origens" ADD CONSTRAINT "fk_esporotricose_doentes_origens_id_animal_doente_es_bc1495ca3e" FOREIGN KEY ("id_animal_doente") REFERENCES "esporotricose_doentes_animais" ("id_animal_doente") ON DELETE CASCADE;
ALTER TABLE "esporotricose_doentes_origens" ADD CONSTRAINT "fk_esporotricose_doentes_origens_id_animal_visita_es_47d76861c3" FOREIGN KEY ("id_animal_visita") REFERENCES "esporotricose_animais" ("id_animal") ON DELETE CASCADE;
ALTER TABLE "esporotricose_doentes_receitas" ADD CONSTRAINT "fk_esporotricose_doentes_receitas_id_animal_doente_e_dc7c27617b" FOREIGN KEY ("id_animal_doente") REFERENCES "esporotricose_doentes_animais" ("id_animal_doente") ON DELETE CASCADE;
ALTER TABLE "esporotricose_visita_agentes" ADD CONSTRAINT "fk_esporotricose_visita_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "esporotricose_visita_agentes" ADD CONSTRAINT "fk_esporotricose_visita_agentes_id_visita_esporotricose_visitas" FOREIGN KEY ("id_visita") REFERENCES "esporotricose_visitas" ("id_visita") ON DELETE CASCADE;
ALTER TABLE "esporotricose_visitas" ADD CONSTRAINT "fk_esporotricose_visitas_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "focos_positivos" ADD CONSTRAINT "fk_focos_positivos_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "focos_positivos" ADD CONSTRAINT "fk_focos_positivos_id_resultado_resultados_laboratorio" FOREIGN KEY ("id_resultado") REFERENCES "resultados_laboratorio" ("id_resultado");
ALTER TABLE "focos_positivos" ADD CONSTRAINT "fk_focos_positivos_id_coleta_coletas" FOREIGN KEY ("id_coleta") REFERENCES "coletas" ("id_coleta");
ALTER TABLE "focos_positivos" ADD CONSTRAINT "fk_focos_positivos_id_visita_visitas" FOREIGN KEY ("id_visita") REFERENCES "visitas" ("id_visita");
ALTER TABLE "laboratorio_coletas_status" ADD CONSTRAINT "fk_laboratorio_coletas_status_encerrado_por_usuarios" FOREIGN KEY ("encerrado_por") REFERENCES "usuarios" ("id_usuario");
ALTER TABLE "laboratorio_coletas_status" ADD CONSTRAINT "fk_laboratorio_coletas_status_id_coleta_coletas" FOREIGN KEY ("id_coleta") REFERENCES "coletas" ("id_coleta");
ALTER TABLE "ovitrampas_calendario_agentes" ADD CONSTRAINT "fk_ovitrampas_calendario_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "ovitrampas_calendario_agentes" ADD CONSTRAINT "fk_ovitrampas_calendario_agentes_id_evento_ovitrampa_a80391bc0d" FOREIGN KEY ("id_evento") REFERENCES "ovitrampas_calendario_eventos" ("id_evento") ON DELETE CASCADE;
ALTER TABLE "ovitrampas_calendario_eventos" ADD CONSTRAINT "fk_ovitrampas_calendario_eventos_id_grupo_ovitrampas_5dfff773f4" FOREIGN KEY ("id_grupo") REFERENCES "ovitrampas_calendario_grupos" ("id_grupo");
ALTER TABLE "ovitrampas_diario_armadilhas" ADD CONSTRAINT "fk_ovitrampas_diario_armadilhas_ovitrampa_id_ovitram_20ceed6e15" FOREIGN KEY ("ovitrampa_id") REFERENCES "ovitrampas_armadilhas" ("ovitrampa_id") ON DELETE CASCADE;
ALTER TABLE "ovitrampas_diario_armadilhas" ADD CONSTRAINT "fk_ovitrampas_diario_armadilhas_id_diario_ovitrampas_diarios" FOREIGN KEY ("id_diario") REFERENCES "ovitrampas_diarios" ("id_diario") ON DELETE CASCADE;
ALTER TABLE "ovitrampas_laboratorio_itens" ADD CONSTRAINT "fk_ovitrampas_laboratorio_itens_id_lote_ovitrampas_l_be098d8e55" FOREIGN KEY ("id_lote") REFERENCES "ovitrampas_laboratorio_lotes" ("id_lote") ON DELETE CASCADE;
ALTER TABLE "ovitrampas_laboratorio_lotes" ADD CONSTRAINT "fk_ovitrampas_laboratorio_lotes_enviado_conta_ovos_por_usuarios" FOREIGN KEY ("enviado_conta_ovos_por") REFERENCES "usuarios" ("id_usuario");
ALTER TABLE "ovitrampas_laboratorio_lotes" ADD CONSTRAINT "fk_ovitrampas_laboratorio_lotes_id_laboratorista_usuarios" FOREIGN KEY ("id_laboratorista") REFERENCES "usuarios" ("id_usuario");
ALTER TABLE "ovitrampas_laboratorio_lotes" ADD CONSTRAINT "fk_ovitrampas_laboratorio_lotes_id_diario_ovitrampas_diarios" FOREIGN KEY ("id_diario") REFERENCES "ovitrampas_diarios" ("id_diario");
ALTER TABLE "ovitrampas_laboratorio_lotes" ADD CONSTRAINT "fk_ovitrampas_laboratorio_lotes_id_evento_ovitrampas_f202648706" FOREIGN KEY ("id_evento") REFERENCES "ovitrampas_calendario_eventos" ("id_evento") ON DELETE CASCADE;
ALTER TABLE "ovitrampas_leituras" ADD CONSTRAINT "fk_ovitrampas_leituras_id_laboratorista_agentes" FOREIGN KEY ("id_laboratorista") REFERENCES "agentes" ("id_agente");
ALTER TABLE "pontos_estrategicos" ADD CONSTRAINT "fk_pontos_estrategicos_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "pontos_estrategicos_alias" ADD CONSTRAINT "fk_pontos_estrategicos_alias_codigo_pe_pontos_estrategicos" FOREIGN KEY ("codigo_pe") REFERENCES "pontos_estrategicos" ("codigo_pe");
ALTER TABLE "recolhimento_agentes" ADD CONSTRAINT "fk_recolhimento_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "recolhimento_agentes" ADD CONSTRAINT "fk_recolhimento_agentes_id_recolhimento_recolhimentos" FOREIGN KEY ("id_recolhimento") REFERENCES "recolhimentos" ("id_recolhimento") ON DELETE CASCADE;
ALTER TABLE "recolhimentos" ADD CONSTRAINT "fk_recolhimentos_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "registro_geografico_imoveis" ADD CONSTRAINT "fk_registro_geografico_imoveis_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "registro_geografico_imoveis" ADD CONSTRAINT "fk_registro_geografico_imoveis_id_quarteirao_registr_d42256c411" FOREIGN KEY ("id_quarteirao") REFERENCES "registro_geografico_quarteiroes" ("id_quarteirao");
ALTER TABLE "registro_geografico_imovel_agentes" ADD CONSTRAINT "fk_registro_geografico_imovel_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "registro_geografico_imovel_agentes" ADD CONSTRAINT "fk_registro_geografico_imovel_agentes_id_imovel_regi_f935588082" FOREIGN KEY ("id_imovel") REFERENCES "registro_geografico_imoveis" ("id_imovel") ON DELETE CASCADE;
ALTER TABLE "registro_geografico_quarteiroes" ADD CONSTRAINT "fk_registro_geografico_quarteiroes_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");
ALTER TABLE "resultados_laboratorio" ADD CONSTRAINT "fk_resultados_laboratorio_id_laboratorista_agentes" FOREIGN KEY ("id_laboratorista") REFERENCES "agentes" ("id_agente");
ALTER TABLE "resultados_laboratorio" ADD CONSTRAINT "fk_resultados_laboratorio_id_coleta_coletas" FOREIGN KEY ("id_coleta") REFERENCES "coletas" ("id_coleta");
ALTER TABLE "tratamentos" ADD CONSTRAINT "fk_tratamentos_id_visita_visitas" FOREIGN KEY ("id_visita") REFERENCES "visitas" ("id_visita");
ALTER TABLE "visita_agentes" ADD CONSTRAINT "fk_visita_agentes_id_agente_agentes" FOREIGN KEY ("id_agente") REFERENCES "agentes" ("id_agente");
ALTER TABLE "visita_agentes" ADD CONSTRAINT "fk_visita_agentes_id_visita_visitas" FOREIGN KEY ("id_visita") REFERENCES "visitas" ("id_visita");
ALTER TABLE "visitas" ADD CONSTRAINT "fk_visitas_id_localidade_localidades" FOREIGN KEY ("id_localidade") REFERENCES "localidades" ("id_localidade");

-- Indices explicitos; redundancias com PK/UNIQUE foram removidas.
CREATE INDEX "idx_acoes_setor_caso" ON "acoes_setor" ("caso");
CREATE INDEX "idx_acoes_setor_data" ON "acoes_setor" ("data");
CREATE INDEX "idx_acoes_setor_localidade" ON "acoes_setor" ("localidade");
CREATE INDEX "idx_acoes_setor_situacao" ON "acoes_setor" ("situacao");
CREATE INDEX "idx_acoes_setor_tipo" ON "acoes_setor" ("tipo");
CREATE INDEX "idx_acoes_setor_agente" ON "acoes_setor_agentes" ("id_agente");
CREATE INDEX "idx_acoes_setor_anexo_acao" ON "acoes_setor_anexos" ("id_acao");
CREATE INDEX "idx_acoes_setor_anexo_restrito" ON "acoes_setor_anexos" ("restrito", "id_acao");
CREATE INDEX "idx_agenda_inicio" ON "agenda_eventos" ("data_inicio");
CREATE INDEX "idx_agenda_recorrencia" ON "agenda_eventos" ("recorrencia", "recorrencia_fim");
CREATE UNIQUE INDEX "idx_agentes_cpf_unico" ON "agentes" ("cpf") WHERE cpf IS NOT NULL AND cpf<>'';
CREATE INDEX "idx_amostra_animais_agentes_agente" ON "amostra_animais_agentes" ("id_agente");
CREATE INDEX "idx_amostras_animais_data" ON "amostras_animais" ("data");
CREATE INDEX "idx_amostras_animais_localidade" ON "amostras_animais" ("id_localidade");
CREATE INDEX "idx_amostras_animais_motivo" ON "amostras_animais" ("motivo_visita");
CREATE INDEX "idx_amostras_animais_tipo" ON "amostras_animais" ("tipo_animal");
CREATE INDEX "idx_auditoria_acao" ON "auditoria_eventos" ("acao");
CREATE INDEX "idx_auditoria_criado" ON "auditoria_eventos" ("criado_em");
CREATE INDEX "idx_boletim_mensal_mes" ON "boletim_mensal_itens" ("ano_mes", "ordem");
CREATE INDEX "idx_bri_agentes_agente" ON "bri_agentes" ("id_agente");
CREATE INDEX "idx_bri_codigo_pe" ON "bri_registros" ("codigo_pe");
CREATE INDEX "idx_bri_data" ON "bri_registros" ("data");
CREATE INDEX "idx_bri_destino" ON "bri_registros" ("destino_tratamento");
CREATE INDEX "idx_bri_id_pe" ON "bri_registros" ("id_pe");
CREATE INDEX "idx_bri_localidade" ON "bri_registros" ("id_localidade");
CREATE INDEX "idx_bri_sispncd" ON "bri_registros" ("sispncd");
CREATE INDEX "idx_col_tubo" ON "coletas" ("num_tubo");
CREATE INDEX "idx_col_visita" ON "coletas" ("id_visita");
CREATE INDEX "idx_dep_visita" ON "depositos_inspecionados" ("id_visita");
CREATE INDEX "idx_esporo_animais_especie" ON "esporotricose_animais" ("especie");
CREATE INDEX "idx_esporo_animais_visita" ON "esporotricose_animais" ("id_visita");
CREATE INDEX "idx_esporo_buscas_animal" ON "esporotricose_buscas_ferido" ("id_animal", "data_busca");
CREATE INDEX "idx_esporo_buscas_data" ON "esporotricose_buscas_ferido" ("data_busca");
CREATE UNIQUE INDEX "idx_esporo_buscas_legado" ON "esporotricose_buscas_ferido" ("id_animal") WHERE origem='legado';
CREATE INDEX "idx_esporo_doentes_anexos_animal" ON "esporotricose_doentes_anexos" ("id_animal_doente");
CREATE INDEX "idx_esporo_doentes_data_notificacao" ON "esporotricose_doentes_animais" ("data_notificacao");
CREATE INDEX "idx_esporo_doentes_localidade" ON "esporotricose_doentes_animais" ("localidade");
CREATE INDEX "idx_esporo_doentes_status" ON "esporotricose_doentes_animais" ("status");
CREATE INDEX "idx_esporo_doentes_entregas_receita" ON "esporotricose_doentes_entregas" ("id_receita");
CREATE INDEX "idx_esporo_doentes_origens_doente" ON "esporotricose_doentes_origens" ("id_animal_doente");
CREATE INDEX "idx_esporo_doentes_receitas_animal" ON "esporotricose_doentes_receitas" ("id_animal_doente");
CREATE INDEX "idx_esporo_estoque_data" ON "esporotricose_estoque_medicacao" ("data");
CREATE INDEX "idx_esporo_estoque_tipo" ON "esporotricose_estoque_medicacao" ("tipo");
CREATE INDEX "idx_esporo_visitas_data" ON "esporotricose_visitas" ("data");
CREATE INDEX "idx_esporo_visitas_localidade" ON "esporotricose_visitas" ("id_localidade");
CREATE INDEX "idx_esporo_visitas_quarteirao" ON "esporotricose_visitas" ("quarteirao");
CREATE INDEX "idx_hist_em" ON "focos_historico" ("alterado_em");
CREATE INDEX "idx_hist_foco" ON "focos_historico" ("id_foco");
CREATE INDEX "idx_foco_codigo" ON "focos_positivos" ("codigo");
CREATE INDEX "idx_foco_data" ON "focos_positivos" ("data");
CREATE INDEX "idx_foco_localidade" ON "focos_positivos" ("id_localidade");
CREATE INDEX "idx_foco_notif" ON "focos_positivos" ("gera_notificacao", "status_notificacao");
CREATE INDEX "idx_foco_status" ON "focos_positivos" ("status_notificacao");
CREATE INDEX "idx_importacoes_criado" ON "importacoes" ("criado_em");
CREATE INDEX "idx_importacoes_status" ON "importacoes" ("status");
CREATE INDEX "idx_lab_status_status" ON "laboratorio_coletas_status" ("status");
CREATE INDEX "idx_login_tentativas_primeira" ON "login_tentativas" ("primeira_em");
CREATE INDEX "idx_meteo_atual_observado" ON "meteorologia_condicoes_atuais" ("observado_em");
CREATE INDEX "idx_meteo_previsao_hora" ON "meteorologia_previsoes_horarias" ("previsto_em");
CREATE INDEX "idx_meteo_resumos_data" ON "meteorologia_resumos_diarios" ("data");
CREATE INDEX "idx_meteo_sync_inicio" ON "meteorologia_sincronizacoes" ("iniciado_em");
CREATE INDEX "idx_ovitrampas_armadilhas_localidade" ON "ovitrampas_armadilhas" ("localidade");
CREATE INDEX "idx_ovitrampas_armadilhas_quarteirao" ON "ovitrampas_armadilhas" ("quarteirao");
CREATE INDEX "idx_ovi_arm_hist_ovitrampa" ON "ovitrampas_armadilhas_historico" ("ovitrampa_id", "criado_em");
CREATE INDEX "idx_ovitrampas_cal_agentes_agente" ON "ovitrampas_calendario_agentes" ("id_agente");
CREATE INDEX "idx_ovitrampas_cal_eventos_grupo" ON "ovitrampas_calendario_eventos" ("id_grupo");
CREATE INDEX "idx_ovi_diario_arm_diario" ON "ovitrampas_diario_armadilhas" ("id_diario", "ordem");
CREATE INDEX "idx_ovi_diario_arm_ovitrampa" ON "ovitrampas_diario_armadilhas" ("ovitrampa_id");
CREATE INDEX "idx_ovi_lab_lotes_status" ON "ovitrampas_laboratorio_lotes" ("status", "data_movimento");
CREATE INDEX "idx_ovitrampas_ano_semana" ON "ovitrampas_leituras" ("ano", "semana");
CREATE INDEX "idx_ovitrampas_coleta" ON "ovitrampas_leituras" ("data_coleta");
CREATE INDEX "idx_ovitrampas_distrito" ON "ovitrampas_leituras" ("distrito");
CREATE INDEX "idx_ovitrampas_id" ON "ovitrampas_leituras" ("ovitrampa_id");
CREATE INDEX "idx_ovitrampas_laboratorista" ON "ovitrampas_leituras" ("id_laboratorista");
CREATE INDEX "idx_ovitrampas_ovos" ON "ovitrampas_leituras" ("ovos");
CREATE INDEX "idx_ovi_ocorrencias_ano_semana" ON "ovitrampas_ocorrencias_conta_ovos" ("ano", "semana");
CREATE INDEX "idx_ovi_ocorrencias_codigo" ON "ovitrampas_ocorrencias_conta_ovos" ("ocorrencia_codigo");
CREATE INDEX "idx_ovi_ocorrencias_id" ON "ovitrampas_ocorrencias_conta_ovos" ("ovitrampa_id");
CREATE INDEX "idx_pe_localidade" ON "pontos_estrategicos" ("id_localidade");
CREATE INDEX "idx_pe_situacao" ON "pontos_estrategicos" ("situacao");
CREATE INDEX "idx_pe_tipo" ON "pontos_estrategicos" ("tipo");
CREATE INDEX "idx_pe_alias_lookup" ON "pontos_estrategicos_alias" ("alias_normalizado", "localidade_normalizada", "ativo");
CREATE INDEX "idx_recolhimento_agentes_agente" ON "recolhimento_agentes" ("id_agente");
CREATE INDEX "idx_recolhimentos_data" ON "recolhimentos" ("data");
CREATE INDEX "idx_recolhimentos_localidade" ON "recolhimentos" ("id_localidade");
CREATE INDEX "idx_recolhimentos_origem" ON "recolhimentos" ("origem_estrutura");
CREATE INDEX "idx_rg_imoveis_data" ON "registro_geografico_imoveis" ("data_atualizacao");
CREATE INDEX "idx_rg_imoveis_localidade" ON "registro_geografico_imoveis" ("id_localidade", "quarteirao");
CREATE INDEX "idx_rg_imoveis_logradouro" ON "registro_geografico_imoveis" ("logradouro");
CREATE INDEX "idx_rg_imoveis_ordem" ON "registro_geografico_imoveis" ("ordem", "id_imovel");
CREATE INDEX "idx_rg_imoveis_quarteirao_ordem" ON "registro_geografico_imoveis" ("id_quarteirao", "ordem", "id_imovel");
CREATE INDEX "idx_rg_imoveis_tipo" ON "registro_geografico_imoveis" ("tipo");
CREATE INDEX "idx_lab_tubo_data" ON "resultados_laboratorio" ("num_tubo", "data_coleta");
CREATE INDEX "idx_resultado_lab_leitura" ON "resultados_laboratorio" ("data_leitura", "id_resultado");
CREATE INDEX "idx_trat_visita" ON "tratamentos" ("id_visita");
CREATE INDEX "idx_va_agente" ON "visita_agentes" ("id_agente");
CREATE INDEX "idx_visitas_codigo_pe" ON "visitas" ("codigo_pe");
CREATE INDEX "idx_visitas_data" ON "visitas" ("data");
CREATE INDEX "idx_visitas_data_tipo" ON "visitas" ("data", "tipo");
CREATE INDEX "idx_visitas_id_pe" ON "visitas" ("id_pe");
CREATE INDEX "idx_visitas_kobo_uuid" ON "visitas" ("kobo_uuid");
CREATE INDEX "idx_visitas_localidade" ON "visitas" ("localidade");
CREATE INDEX "idx_visitas_localidade_data_tipo" ON "visitas" ("id_localidade", "data", "tipo");
CREATE INDEX "idx_visitas_quarteirao" ON "visitas" ("quarteirao");
CREATE INDEX "idx_visitas_tipo" ON "visitas" ("tipo");
