CREATE TABLE contaovos_sync_cursor (
    fluxo text PRIMARY KEY,
    ultimo_id_remoto text,
    atualizado_em text NOT NULL
);

CREATE TABLE contaovos_execucoes (
    id_execucao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo text NOT NULL,
    iniciado_em text NOT NULL,
    finalizado_em text,
    status text NOT NULL
        CHECK (status IN ('executando','concluido','parcial','erro')),
    itens_ok bigint NOT NULL DEFAULT 0 CHECK (itens_ok >= 0),
    itens_erro bigint NOT NULL DEFAULT 0 CHECK (itens_erro >= 0),
    resumo_sanitizado text
);

CREATE INDEX idx_contaovos_execucoes_inicio
    ON contaovos_execucoes (iniciado_em DESC, id_execucao DESC);
