CREATE TABLE contaovos_fila_contagens (
    id_fila bigint GENERATED BY DEFAULT AS IDENTITY,
    id_item bigint NOT NULL,
    status text NOT NULL DEFAULT 'pendente',
    tentativas bigint NOT NULL DEFAULT 0,
    id_remoto text,
    erro_sanitizado text,
    payload_hash text NOT NULL,
    criado_em text NOT NULL,
    atualizado_em text NOT NULL,
    ultima_tentativa_em text,
    confirmado_em text,
    CONSTRAINT pk_contaovos_fila_contagens PRIMARY KEY (id_fila),
    CONSTRAINT uq_contaovos_fila_contagens_id_item UNIQUE (id_item),
    CONSTRAINT fk_contaovos_fila_contagens_item
        FOREIGN KEY (id_item)
        REFERENCES ovitrampas_laboratorio_itens (id_item),
    CONSTRAINT ck_contaovos_fila_contagens_status
        CHECK (status IN ('pendente','enviando','confirmado','erro')),
    CONSTRAINT ck_contaovos_fila_contagens_tentativas
        CHECK (tentativas >= 0)
);

CREATE INDEX idx_contaovos_fila_contagens_status
    ON contaovos_fila_contagens (status, atualizado_em, id_fila);
