CREATE TABLE enderecos_normalizados (
    id_endereco bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave_endereco text NOT NULL UNIQUE,
    logradouro_normalizado text NOT NULL,
    logradouro_oficial text NOT NULL,
    numero_normalizado text NOT NULL,
    criado_em text NOT NULL,
    atualizado_em text NOT NULL,
    confirmado_por text
);

CREATE TABLE visitas_enderecos_normalizados (
    id_visita text PRIMARY KEY REFERENCES visitas(id_visita),
    id_endereco bigint NOT NULL REFERENCES enderecos_normalizados(id_endereco),
    logradouro_bruto text,
    numero_bruto text,
    confirmado_em text NOT NULL,
    confirmado_por text
);

CREATE INDEX idx_visitas_enderecos_id_endereco
    ON visitas_enderecos_normalizados (id_endereco);
