CREATE TABLE contaovos_fila_cadastro_ovitrampas (
    id_fila bigint GENERATED BY DEFAULT AS IDENTITY,
    id_item bigint NOT NULL,
    ovitrampa_id text NOT NULL,
    status text NOT NULL DEFAULT 'pendente',
    tentativas bigint NOT NULL DEFAULT 0,
    payload_json text NOT NULL,
    payload_hash text NOT NULL,
    atualizar_desde date,
    erro_sanitizado text,
    resposta_sanitizada text,
    criado_em text NOT NULL,
    atualizado_em text NOT NULL,
    ultima_tentativa_em text,
    confirmado_em text,
    CONSTRAINT pk_contaovos_fila_cadastro_ovitrampas PRIMARY KEY (id_fila),
    CONSTRAINT uq_contaovos_fila_cadastro_item UNIQUE (id_item),
    CONSTRAINT fk_contaovos_fila_cadastro_item FOREIGN KEY (id_item)
        REFERENCES ovitrampas_laboratorio_itens (id_item),
    CONSTRAINT ck_contaovos_fila_cadastro_status
        CHECK (status IN ('pendente','enviando','confirmado','erro','incerto')),
    CONSTRAINT ck_contaovos_fila_cadastro_tentativas CHECK (tentativas >= 0)
);

CREATE INDEX idx_contaovos_fila_cadastro_status
    ON contaovos_fila_cadastro_ovitrampas (status, atualizado_em, id_fila);
