CREATE TABLE esporotricose_imoveis (
    id_imovel bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_localidade bigint NOT NULL REFERENCES localidades(id_localidade),
    localidade text NOT NULL,
    quarteirao text NOT NULL,
    logradouro_chave text NOT NULL,
    numero_chave text NOT NULL,
    chave text NOT NULL UNIQUE,
    criado_em text NOT NULL,
    atualizado_em text NOT NULL
);

CREATE TABLE esporotricose_visita_imoveis (
    id_visita text PRIMARY KEY REFERENCES esporotricose_visitas(id_visita) ON DELETE CASCADE,
    id_imovel bigint NOT NULL REFERENCES esporotricose_imoveis(id_imovel),
    origem text NOT NULL CHECK (origem IN ('automatico', 'manual')),
    confianca integer NOT NULL CHECK (confianca BETWEEN 0 AND 100),
    vinculado_em text NOT NULL
);

CREATE INDEX idx_esporo_imoveis_endereco
    ON esporotricose_imoveis (id_localidade, quarteirao, logradouro_chave, numero_chave);
CREATE INDEX idx_esporo_visita_imoveis_imovel
    ON esporotricose_visita_imoveis (id_imovel);
