CREATE TABLE esporotricose_pacientes_humanos (
    id_paciente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome text NOT NULL,
    data_nascimento date,
    cartao_sus text,
    nome_mae text,
    telefone text,
    data_notificacao date,
    status text NOT NULL CHECK (status IN ('Em tratamento', 'Acabou tratamento', 'Outros')),
    status_outro text,
    id_localidade bigint REFERENCES localidades(id_localidade),
    localidade text,
    quarteirao text,
    logradouro text,
    numero text,
    complemento text,
    latitude double precision,
    longitude double precision,
    observacoes text,
    criado_por text,
    atualizado_por text,
    criado_em text NOT NULL,
    atualizado_em text NOT NULL,
    CONSTRAINT ck_esporo_paciente_status_outro
        CHECK (status <> 'Outros' OR NULLIF(TRIM(status_outro), '') IS NOT NULL),
    CONSTRAINT ck_esporo_paciente_coordenadas
        CHECK ((latitude IS NULL) = (longitude IS NULL)),
    CONSTRAINT ck_esporo_paciente_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_esporo_paciente_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE UNIQUE INDEX uq_esporo_pacientes_sus
    ON esporotricose_pacientes_humanos(cartao_sus)
    WHERE cartao_sus IS NOT NULL AND TRIM(cartao_sus) <> '';
CREATE INDEX idx_esporo_pacientes_status
    ON esporotricose_pacientes_humanos(status);
CREATE INDEX idx_esporo_pacientes_localidade
    ON esporotricose_pacientes_humanos(id_localidade, localidade);

CREATE TABLE esporotricose_pacientes_acompanhamentos (
    id_acompanhamento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente bigint NOT NULL REFERENCES esporotricose_pacientes_humanos(id_paciente) ON DELETE CASCADE,
    data date NOT NULL,
    status text NOT NULL CHECK (status IN ('Em tratamento', 'Acabou tratamento', 'Outros')),
    status_outro text,
    observacoes text,
    criado_por text,
    criado_em text NOT NULL,
    CONSTRAINT ck_esporo_acompanhamento_status_outro
        CHECK (status <> 'Outros' OR NULLIF(TRIM(status_outro), '') IS NOT NULL)
);
CREATE INDEX idx_esporo_pacientes_acompanhamentos
    ON esporotricose_pacientes_acompanhamentos(id_paciente, data);

CREATE TABLE esporotricose_pacientes_anexos (
    id_anexo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente bigint NOT NULL REFERENCES esporotricose_pacientes_humanos(id_paciente) ON DELETE CASCADE,
    nome_original text NOT NULL,
    nome_arquivo text NOT NULL,
    caminho_rel text NOT NULL,
    mime_type text,
    tamanho bigint NOT NULL,
    criado_por text,
    criado_em text NOT NULL
);
CREATE INDEX idx_esporo_pacientes_anexos
    ON esporotricose_pacientes_anexos(id_paciente);

CREATE TABLE esporotricose_paciente_imoveis (
    id_paciente bigint NOT NULL REFERENCES esporotricose_pacientes_humanos(id_paciente) ON DELETE CASCADE,
    id_imovel bigint NOT NULL REFERENCES esporotricose_imoveis(id_imovel) ON DELETE CASCADE,
    vinculado_por text,
    vinculado_em text NOT NULL,
    PRIMARY KEY (id_paciente, id_imovel)
);

CREATE TABLE esporotricose_paciente_animais (
    id_paciente bigint NOT NULL REFERENCES esporotricose_pacientes_humanos(id_paciente) ON DELETE CASCADE,
    id_animal_doente bigint NOT NULL REFERENCES esporotricose_doentes_animais(id_animal_doente) ON DELETE CASCADE,
    vinculado_por text,
    vinculado_em text NOT NULL,
    PRIMARY KEY (id_paciente, id_animal_doente)
);
