CREATE TABLE territorializacao_microareas (
    id_microarea bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_localidade bigint NOT NULL REFERENCES localidades(id_localidade),
    numero text NOT NULL,
    acs_codigo text,
    observacoes text NOT NULL DEFAULT '',
    criado_em text NOT NULL,
    atualizado_em text NOT NULL,
    CONSTRAINT uq_territorializacao_microarea_numero UNIQUE (id_localidade, numero)
);

CREATE TABLE territorializacao_microarea_quarteiroes (
    id_microarea bigint NOT NULL REFERENCES territorializacao_microareas(id_microarea) ON DELETE CASCADE,
    id_localidade bigint NOT NULL REFERENCES localidades(id_localidade),
    quarteirao text NOT NULL,
    PRIMARY KEY (id_microarea, id_localidade, quarteirao),
    CONSTRAINT uq_territorializacao_microarea_quarteirao UNIQUE (id_localidade, quarteirao)
);

CREATE INDEX idx_territorializacao_microareas_acs ON territorializacao_microareas(acs_codigo);
