CREATE TABLE territorializacao_microarea_partes (
    id_parte bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_microarea bigint NOT NULL REFERENCES territorializacao_microareas(id_microarea) ON DELETE CASCADE,
    id_localidade bigint NOT NULL REFERENCES localidades(id_localidade),
    quarteirao text NOT NULL,
    logradouro text NOT NULL,
    lado text NOT NULL,
    geometry_json text NOT NULL,
    base_geometry_hash text NOT NULL,
    criado_em text NOT NULL,
    atualizado_em text NOT NULL,
    CONSTRAINT uq_territorializacao_microarea_parte_lado
        UNIQUE (id_localidade, quarteirao, logradouro, lado)
);

CREATE INDEX idx_territorializacao_microarea_partes_area
    ON territorializacao_microarea_partes(id_microarea);
CREATE INDEX idx_territorializacao_microarea_partes_quarteirao
    ON territorializacao_microarea_partes(id_localidade, quarteirao);
