CREATE TABLE liraa_ciclos (
    id_ciclo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano integer NOT NULL CHECK (ano BETWEEN 2000 AND 2100),
    nome text NOT NULL, inicio text, fim text,
    observacoes text NOT NULL DEFAULT '', criado_em text NOT NULL,
    CONSTRAINT uq_liraa_ciclo_ano_nome UNIQUE (ano, nome)
);

CREATE TABLE liraa_estratos (
    id_estrato bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ciclo bigint NOT NULL REFERENCES liraa_ciclos(id_ciclo) ON DELETE CASCADE,
    numero integer NOT NULL CHECK (numero > 0),
    tipo text NOT NULL CHECK (tipo IN ('normal', 'reduzido')),
    imoveis_confirmados integer NOT NULL CHECK (imoveis_confirmados > 0),
    observacoes text NOT NULL DEFAULT '',
    criado_em text NOT NULL, atualizado_em text NOT NULL,
    CONSTRAINT uq_liraa_estrato_numero UNIQUE (id_ciclo, numero)
);

CREATE TABLE liraa_estrato_localidades (
    id_estrato bigint NOT NULL REFERENCES liraa_estratos(id_estrato) ON DELETE CASCADE,
    id_ciclo bigint NOT NULL REFERENCES liraa_ciclos(id_ciclo) ON DELETE CASCADE,
    id_localidade bigint NOT NULL REFERENCES localidades(id_localidade),
    PRIMARY KEY (id_estrato, id_localidade),
    CONSTRAINT uq_liraa_ciclo_localidade UNIQUE (id_ciclo, id_localidade)
);

CREATE TABLE liraa_sorteios (
    id_sorteio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estrato bigint NOT NULL UNIQUE REFERENCES liraa_estratos(id_estrato) ON DELETE RESTRICT,
    criado_em text NOT NULL, semente text NOT NULL,
    n integer NOT NULL, a integer NOT NULL, q integer NOT NULL,
    fracao double precision NOT NULL, intervalo double precision NOT NULL,
    inicio_casual double precision NOT NULL,
    universo_hash text NOT NULL, universo_json text NOT NULL,
    selecionados_json text NOT NULL
);
