CREATE TABLE liraa_visitas (
    id_visita bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ciclo bigint NOT NULL REFERENCES liraa_ciclos(id_ciclo) ON DELETE RESTRICT,
    id_estrato bigint REFERENCES liraa_estratos(id_estrato) ON DELETE RESTRICT,
    kobo_uuid text NOT NULL UNIQUE,
    kobo_id bigint,
    data_visita text NOT NULL,
    hora_inicio text,
    enviado_em text,
    agentes_codigos text NOT NULL DEFAULT '',
    acs_codigos text NOT NULL DEFAULT '',
    id_localidade bigint REFERENCES localidades(id_localidade),
    localidade_informada text NOT NULL,
    quarteirao text NOT NULL,
    situacao_vinculo text NOT NULL,
    tipo_imovel text,
    logradouro text,
    numero text,
    sequencia text,
    morador text,
    observacoes text,
    criado_em text NOT NULL
);
CREATE INDEX idx_liraa_visitas_ciclo_data ON liraa_visitas(id_ciclo, data_visita);
CREATE INDEX idx_liraa_visitas_localidade_q ON liraa_visitas(id_localidade, quarteirao);

CREATE TABLE liraa_visita_tubitos (
    id_tubito bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_visita bigint NOT NULL REFERENCES liraa_visitas(id_visita) ON DELETE CASCADE,
    ordem integer NOT NULL,
    numero text,
    codigo_deposito text,
    deposito text,
    UNIQUE(id_visita, ordem)
);

CREATE TABLE liraa_visitas_excluidas (
    kobo_uuid text PRIMARY KEY,
    excluida_em text NOT NULL,
    id_ciclo bigint,
    motivo text NOT NULL DEFAULT ''
);
