-- Configuração local do formulário por ciclo; não publica nada no Kobo.
CREATE TABLE liraa_ciclo_config (
    id_ciclo bigint PRIMARY KEY REFERENCES liraa_ciclos(id_ciclo) ON DELETE CASCADE,
    acs_json text NOT NULL DEFAULT '[]',
    acs_definidos integer NOT NULL DEFAULT 0 CHECK (acs_definidos IN (0,1)),
    kobo_uid text NOT NULL DEFAULT '', atualizado_em text NOT NULL
);

CREATE TABLE liraa_sorteios_historico (
    id_historico bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estrato bigint NOT NULL REFERENCES liraa_estratos(id_estrato) ON DELETE CASCADE,
    id_sorteio_original bigint NOT NULL, substituido_em text NOT NULL,
    snapshot_json text NOT NULL
);
CREATE INDEX idx_liraa_sorteios_historico_estrato ON liraa_sorteios_historico(id_estrato);

ALTER TABLE liraa_visitas ADD COLUMN tratamento_json text NOT NULL DEFAULT '{}';
ALTER TABLE liraa_visitas ADD COLUMN form_ciclo text NOT NULL DEFAULT '';
ALTER TABLE liraa_visitas ADD COLUMN plano_hash text NOT NULL DEFAULT '';

-- Uma leitura por tubito/recipiente; a positividade é derivada das formas.
CREATE TABLE liraa_leituras (
    id_tubito bigint PRIMARY KEY REFERENCES liraa_visita_tubitos(id_tubito) ON DELETE CASCADE,
    data_leitura text NOT NULL, laboratorista text NOT NULL, id_usuario bigint NOT NULL,
    aegypt_larvas integer NOT NULL DEFAULT 0 CHECK (aegypt_larvas >= 0),
    aegypt_pupas integer NOT NULL DEFAULT 0 CHECK (aegypt_pupas >= 0),
    albopictus_larvas integer NOT NULL DEFAULT 0 CHECK (albopictus_larvas >= 0),
    albopictus_pupas integer NOT NULL DEFAULT 0 CHECK (albopictus_pupas >= 0),
    outra_larvas integer NOT NULL DEFAULT 0 CHECK (outra_larvas >= 0),
    outra_pupas integer NOT NULL DEFAULT 0 CHECK (outra_pupas >= 0),
    observacoes text NOT NULL DEFAULT '', atualizado_em text NOT NULL
);
