"""Base local de ajuda orientada ao uso do sistema."""
import unicodedata


ARTIGOS = (
    {
        "id": "inicio",
        "titulo": "Conhecendo a tela inicial",
        "categoria": "Geral",
        "rotas": ("/",),
        "tags": ("inicio", "painel", "dashboard", "indicadores", "atalhos"),
        "resumo": "A tela inicial reúne os indicadores do setor, alertas e atalhos para as rotinas mais frequentes.",
        "passos": (
            "Use os cards para abrir diretamente a área relacionada ao indicador.",
            "Confira os alertas antes de iniciar as rotinas do dia.",
            "Use o menu lateral para acessar os módulos do sistema.",
        ),
        "link": "/",
        "link_label": "Abrir início",
    },
    {
        "id": "importacao-kobo",
        "titulo": "Importar dados do Kobo",
        "categoria": "Dados",
        "rotas": ("/processar",),
        "tags": ("kobo", "importacao", "api", "pendencias", "planilha", "visitas", "laboratorio"),
        "resumo": "Use a Importação Kobo para conferir pendências, buscar uma prévia e gravar os registros no sistema.",
        "passos": (
            "Abra Pendências por formulário para identificar registros novos.",
            "Escolha o formulário e, se necessário, o período desejado.",
            "Busque a prévia, confira os avisos e prepare a importação.",
            "A importação por planilhas fica disponível como recurso emergencial.",
        ),
        "link": "/processar",
        "link_label": "Abrir Importação Kobo",
    },
    {
        "id": "registro-geografico-consulta",
        "titulo": "Consultar o Registro Geográfico",
        "categoria": "Registro Geográfico",
        "rotas": ("/registro-geografico",),
        "tags": ("rg", "consulta", "imoveis", "populacao", "filtro", "quarteirao", "localidade"),
        "resumo": "A aba Consulta permite localizar imóveis e resumir os dados por localidade, quarteirão, tipo, atualização e agente.",
        "passos": (
            "Selecione uma ou mais localidades nos filtros.",
            "Refine por quarteirão, tipo de imóvel, atualização ou agente.",
            "Use a pesquisa para encontrar rua, número ou observação.",
        ),
        "link": "/registro-geografico",
        "link_label": "Abrir Registro Geográfico",
    },
    {
        "id": "registro-geografico-edicao",
        "titulo": "Editar um quarteirão",
        "categoria": "Registro Geográfico",
        "rotas": ("/registro-geografico",),
        "tags": ("rg", "edicao", "quarteirao", "logradouro", "imovel", "referencia", "ref", "setas"),
        "resumo": "Na aba Edição, altere as linhas de imóveis de um quarteirão ou comece um registro novo do zero.",
        "passos": (
            "Escolha a localidade e o quarteirão na aba Edição.",
            "Use as setas do teclado para avançar entre as células da grade.",
            "Linhas do tipo REF servem apenas como referência de lado ou acesso e não entram na contagem de imóveis.",
            "Salve a grade ao terminar as alterações.",
        ),
        "link": "/registro-geografico",
        "link_label": "Abrir edição do RG",
    },
    {
        "id": "registro-geografico-impressao",
        "titulo": "Imprimir fichas do Registro Geográfico",
        "categoria": "Registro Geográfico",
        "rotas": ("/registro-geografico",),
        "tags": ("rg", "impressao", "imprimir", "mapa", "satelite", "osm", "quarteiroes", "selecionar tudo"),
        "resumo": "A aba Impressão gera as fichas de campo com a relação de imóveis e, quando escolhido, os mapas do quarteirão.",
        "passos": (
            "Escolha a localidade e marque os quarteirões desejados ou use Selecionar tudo.",
            "Defina se a ficha deve incluir os mapas de satélite e ruas.",
            "Abra a impressão e use a visualização do navegador antes de enviar para a impressora.",
        ),
        "link": "/registro-geografico",
        "link_label": "Abrir impressão do RG",
    },
    {
        "id": "registro-geografico-mapa",
        "titulo": "Analisar áreas no mapa do RG",
        "categoria": "Registro Geográfico",
        "rotas": ("/registro-geografico",),
        "tags": ("rg", "mapa", "analise", "area", "selecao", "cores", "localidade", "satelite"),
        "resumo": "Na aba Mapa / Análise, clique em um ou mais quarteirões para somar imóveis, tipos e população aproximada.",
        "passos": (
            "Filtre as localidades que deseja visualizar.",
            "Clique nos quarteirões para montar uma seleção de área.",
            "Confira os totais e a lista de quarteirões selecionados no painel lateral.",
        ),
        "link": "/registro-geografico",
        "link_label": "Abrir mapa do RG",
    },
    {
        "id": "ovitrampas-diarios",
        "titulo": "Gerar diários de ovitrampas",
        "categoria": "Ovitrampas",
        "rotas": ("/ovitrampas",),
        "tags": ("ovitrampas", "diario", "rota", "armadilha", "impressao", "conta ovos", "realocar"),
        "resumo": "Os Diários organizam as armadilhas para impressão e uso no campo durante o ciclo.",
        "passos": (
            "Importe o cadastro exportado do Conta Ovos quando houver alterações.",
            "Defina o diário e ajuste a ordem das armadilhas arrastando os itens.",
            "Armadilhas marcadas como REALOCAR permanecem fora do diário até serem definidas.",
            "Abra a impressão ao finalizar a organização do diário.",
        ),
        "link": "/ovitrampas",
        "link_label": "Abrir Ovitrampas",
    },
    {
        "id": "ovitrampas-leituras",
        "titulo": "Lançar e corrigir leituras de ovitrampas",
        "categoria": "Ovitrampas",
        "rotas": ("/ovitrampas",),
        "tags": ("ovitrampas", "leituras", "laboratorista", "lote", "editar", "palhetas", "ovos"),
        "resumo": "Use as leituras para registrar os resultados das ovitrampas, inclusive em lote quando várias leituras recebem a mesma informação.",
        "passos": (
            "Filtre o grupo ou a data de leitura desejada.",
            "Selecione os registros que devem receber a mesma informação.",
            "Informe o laboratorista e a data no lançamento em lote.",
        ),
        "link": "/ovitrampas",
        "link_label": "Abrir leituras",
    },
    {
        "id": "laboratorio-lancamentos",
        "titulo": "Lançar resultados de laboratório",
        "categoria": "Laboratório",
        "rotas": ("/laboratorio/lancamentos",),
        "tags": ("laboratorio", "tubo", "larvas", "pupas", "aegypti", "resultado", "historico", "negativo"),
        "resumo": "Em Lançamentos Laboratório, os tubos pendentes são preenchidos a partir das coletas registradas nas visitas.",
        "passos": (
            "Abra um tubo pendente e confira a origem da coleta, o agente e o tipo de trabalho.",
            "Registre as quantidades por espécie e forma encontrada.",
            "Resultado negativo significa ausência de Aedes aegypti em todas as formas informadas.",
            "Os registros recentes podem ser corrigidos no histórico dentro do prazo permitido.",
        ),
        "link": "/laboratorio/lancamentos",
        "link_label": "Abrir Laboratório",
    },
    {
        "id": "esporotricose-visitas",
        "titulo": "Consultar visitas de esporotricose",
        "categoria": "Esporotricose",
        "rotas": ("/esporotricose",),
        "tags": ("esporotricose", "visitas", "animais", "ferido", "kobo", "agente", "localidade", "imprimir"),
        "resumo": "A área Visitas reúne os dados importados do Kobo, com filtros, detalhes dos animais e acompanhamento de busca de animal ferido.",
        "passos": (
            "Use os filtros para combinar localidades, agentes, situações e outros critérios.",
            "Abra Detalhes de um animal para ver a visita relacionada.",
            "Registre a data e o agente quando houver busca de animal ferido.",
        ),
        "link": "/esporotricose",
        "link_label": "Abrir Esporotricose",
    },
    {
        "id": "esporotricose-doentes",
        "titulo": "Acompanhar animais doentes e medicação",
        "categoria": "Esporotricose",
        "rotas": ("/esporotricose",),
        "tags": ("esporotricose", "doentes", "receita", "capsulas", "entrega", "estoque", "zoomed", "proxima entrega"),
        "resumo": "A área Doentes controla receitas, entregas, próxima dispensação e o estoque de medicação.",
        "passos": (
            "Cadastre ou edite a receita com quantidade total e posologia.",
            "Registre cada entrega com a quantidade efetivamente dispensada.",
            "A próxima entrega é calculada conforme a última dispensação e a posologia.",
            "Confira o estoque para entradas, saídas, sobras e baixas no Zoomed.",
        ),
        "link": "/esporotricose",
        "link_label": "Abrir Doentes",
    },
    {
        "id": "agenda",
        "titulo": "Planejar atividades na Agenda",
        "categoria": "Planejamento",
        "rotas": ("/agenda",),
        "tags": ("agenda", "evento", "campo", "atividade externa", "recorrencia", "clima", "lembrete"),
        "resumo": "A Agenda reúne compromissos manuais e atividades registradas automaticamente pelo sistema.",
        "passos": (
            "Crie eventos manuais com data, horário, lembrete e recorrência quando necessário.",
            "Marque Atividade externa para receber o alerta meteorológico correspondente.",
            "Use o painel de condições para campo para acompanhar chuva, vento e temperatura no expediente.",
        ),
        "link": "/agenda",
        "link_label": "Abrir Agenda",
    },
    {
        "id": "meteorologia",
        "titulo": "Consultar dados meteorológicos",
        "categoria": "Planejamento",
        "rotas": ("/meteorologia",),
        "tags": ("meteorologia", "inmet", "clima", "chuva", "temperatura", "umidade", "previsao", "atualizar"),
        "resumo": "A Meteorologia apresenta condições atuais estimadas e resumos diários de referência para apoiar o planejamento do setor.",
        "passos": (
            "Atualize os dados quando precisar de uma previsão nova.",
            "Consulte as temperaturas, umidade e precipitação nos resumos diários.",
            "Para trabalho externo, use também os alertas da Agenda dentro do horário de expediente.",
        ),
        "link": "/meteorologia",
        "link_label": "Abrir Meteorologia",
    },
    {
        "id": "acoes-setor",
        "titulo": "Registrar ações, atendimentos e anexos",
        "categoria": "Ações e Atendimentos",
        "rotas": ("/acoes-setor",),
        "tags": ("acoes", "atendimentos", "vistoria", "reuniao", "palestra", "limpeza", "anexos", "caso", "restrito"),
        "resumo": "Registre ações coletivas, atendimentos técnicos, reuniões e os arquivos relacionados a cada atividade.",
        "passos": (
            "Clique em Novo registro, escolha o tipo, a situação e informe o período.",
            "Use Caso / acompanhamento para relacionar várias atividades à mesma situação.",
            "Em ações educativas, preencha atividade realizada, público-alvo e recursos utilizados.",
            "Administradores podem marcar documentos sensíveis como restritos.",
            "Use os filtros dos Registros ou a aba Anexos para localizar dados e arquivos.",
        ),
        "link": "/acoes-setor",
        "link_label": "Abrir Ações e Atendimentos",
    },
    {
        "id": "pontos-estrategicos",
        "titulo": "Acompanhar Pontos Estratégicos",
        "categoria": "Campo",
        "rotas": ("/pontos-estrategicos",),
        "tags": ("pe", "ponto estrategico", "atraso", "visita", "situacao", "prazo"),
        "resumo": "A tela de Pontos Estratégicos ajuda a identificar locais que precisam de visita e acompanhar suas situações.",
        "passos": (
            "Use os filtros para localizar pontos por situação, localidade ou responsável.",
            "Confira os atrasos antes de organizar a rota de campo.",
            "Após importar a visita correta, atualize a página para conferir a nova situação.",
        ),
        "link": "/pontos-estrategicos",
        "link_label": "Abrir Pontos Estratégicos",
    },
    {
        "id": "backups",
        "titulo": "Fazer e localizar backups",
        "categoria": "Administração",
        "rotas": ("/admin/sistema",),
        "tags": ("backup", "copia", "seguranca", "central do sistema", "banco", "restaurar"),
        "resumo": "A Central do Sistema reúne os controles de backup do banco e dos arquivos importantes do setor.",
        "passos": (
            "Abra a Central do Sistema para gerar um backup manual quando necessário.",
            "Os backups são organizados em D:\\BackupsEndemias conforme a configuração do sistema.",
            "Mantenha cópias adicionais em outro local para proteção contra falhas do computador.",
        ),
        "link": "/admin/sistema",
        "link_label": "Abrir Central do Sistema",
        "nivel_minimo": "admin",
    },
)
ARTIGOS_BASE = ARTIGOS


def _artigo(identificador, titulo, categoria, rotas, tags, resumo, passos, link, link_label,
             contextos=(), nivel_minimo="visualizador", atencao=()):
    """Cria um artigo curto, pesquisável e orientado a uma tela do sistema.

    ``atencao`` reune cuidados e enganos comuns do assunto. E opcional: o painel
    so desenha o bloco quando o artigo traz algum item.
    """
    return {
        "id": identificador,
        "titulo": titulo,
        "categoria": categoria,
        "rotas": tuple(rotas),
        "tags": tuple(tags),
        "resumo": resumo,
        "passos": tuple(passos),
        "link": link,
        "link_label": link_label,
        "contextos": tuple(contextos),
        "nivel_minimo": nivel_minimo,
        "atencao": tuple(atencao),
    }


# Complemento detalhado: os primeiros artigos explicam os módulos; estes orientam
# os controles e as abas que a pessoa encontra durante o trabalho diário.
ARTIGOS += (
    _artigo("navegacao", "Usar o menu e os atalhos", "Geral", ("/",),
             ("menu", "navegacao", "atalhos", "tela", "voltar", "inicio"),
             "O menu lateral concentra os módulos do setor. Ele pode ser recolhido para ganhar espaço, especialmente em telas menores.",
             ("Abra o menu pelo ícone de três linhas quando ele estiver recolhido.",
              "Use Início para voltar ao painel com os indicadores e alertas.",
              "Os itens disponíveis dependem das permissões do usuário conectado."),
             "/", "Abrir início"),
    _artigo("filtros-multiplos", "Selecionar filtros múltiplos", "Geral", ("/",),
             ("filtro", "multiplos", "selecionar", "localidades", "agentes", "limpar", "dropdown"),
             "Em listas com seleção múltipla, clique no campo para abrir as opções e marque quantos itens precisar. Não é necessário segurar Ctrl.",
             ("Clique no campo do filtro para abrir as opções disponíveis.",
              "Marque ou desmarque cada opção; o resumo do campo mostra a seleção.",
              "Use Limpar dentro do seletor ou o botão de limpar filtros da tela para recomeçar."),
             "/", "Abrir início"),
    _artigo("tabelas-pesquisa", "Ler tabelas, pesquisar e atualizar", "Geral", ("/",),
             ("tabela", "pesquisa", "buscar", "atualizar", "ordenar", "setas", "alfabetica", "data", "lista", "paginacao"),
             "As telas de consulta combinam filtros, pesquisa e tabelas. A pesquisa localiza trechos de texto, como nome, rua, observação ou código, conforme a página.",
             ("Aplique primeiro os filtros mais amplos, como período ou localidade.",
              "Digite uma palavra ou código no campo de pesquisa para refinar a lista.",
              "Quando houver setas no cabeçalho, clique no nome da coluna para alternar entre ordem crescente e decrescente.",
              "Use Atualizar quando a tela indicar que os dados podem ter mudado após uma importação ou edição."),
             "/", "Abrir início"),
    _artigo("impressao-geral", "Preparar uma impressão", "Geral", ("/",),
             ("imprimir", "impressao", "pdf", "pagina", "navegador", "preview"),
             "As impressões são abertas em uma visualização própria do navegador. Revise a prévia antes de enviar para a impressora ou salvar em PDF.",
             ("Escolha os registros ou o período desejado na tela de origem.",
              "Clique no comando de impressão e aguarde a prévia abrir.",
              "Na prévia, confirme orientação, margens e páginas antes de imprimir."),
             "/", "Abrir início"),
    _artigo("tema-visual", "Ajustar a visualização da interface", "Geral", ("/",),
             ("tema", "escuro", "claro", "acessibilidade", "celular", "tela", "contraste"),
             "O botão de tema no topo alterna entre os modos claro e escuro. O modo escuro costuma oferecer mais contraste para tabelas e campos extensos.",
             ("Use o botão de tema no canto superior direito para alternar a aparência.",
              "Em celular ou tablet, abra o menu lateral pelo ícone de três linhas.",
              "Gire o dispositivo para paisagem quando uma tabela tiver muitas colunas."),
             "/", "Abrir início"),
    _artigo("dashboard-visitas", "Interpretar o Dashboard de Visitas", "Análise", ("/dashboard",),
             ("dashboard", "visitas", "indicadores", "graficos", "periodo", "kobo"),
             "O Dashboard de Visitas consolida as visitas já importadas e ajuda a acompanhar a produção por período, equipe e frente de trabalho.",
             ("Defina o período antes de comparar indicadores.",
              "Use os gráficos como visão resumida e as listas detalhadas para conferir registros específicos.",
              "Compare frentes de trabalho (PE, PVE, TB, TBO) para entender o esforço de cada tipo de visita.",
              "Passe o cursor sobre os gráficos para ver o valor exato de cada ponto ou barra.",
              "Depois de uma importação, atualize a página para refletir os novos dados."),
             "/dashboard", "Abrir Dashboard",
             atencao=(
                 "O dashboard só enxerga o que já foi importado. Uma queda repentina costuma ser importação pendente, não parada de campo.",
                 "Períodos muito longos deixam o gráfico difícil de ler; prefira comparar mês a mês.",
             )),
    _artigo("visitas-arboviroses", "Consultar Visitas Arboviroses", "Análise", ("/visitas",),
             ("visitas", "arboviroses", "filtro", "kobo", "depósitos", "tratamentos", "coletas", "exportar"),
             "A página Visitas Arboviroses reúne os registros importados dos formulários PE, PVE, TB e TBO com seus dados de campo relacionados.",
             ("Combine filtros de período, formulário, localidade, agente, depósitos, produtos, coletas e situação laboratorial.",
              "Cada sigla é uma frente: PE é ponto estratégico, PVE é ponto de vigilância entomológica, TB é tratamento de bloqueio e TBO é tratamento com contagem de ovos.",
              "Use Ver mais para conferir os dados completos da visita, depósitos, tratamentos, coletas e resultados laboratoriais.",
              "A edição permite corrigir o registro principal e seus dados relacionados; confira tudo antes de salvar.",
              "Exporte quando precisar analisar fora do sistema ou encaminhar a relação."),
             "/visitas", "Abrir Visitas Arboviroses",
             atencao=(
                 "Editar aqui corrige o sistema, mas não corrige o formulário original no Kobo. Se o mesmo registro for reimportado, o erro pode voltar.",
                 "Antes de editar, confira se o caso não é de reimportação: às vezes o dado certo já está a caminho.",
             )),
    _artigo("laboratorio-consulta", "Consultar resultados laboratoriais", "Laboratório", ("/laboratorio",),
             ("laboratorio", "resultados", "tubos", "tabela", "evolucao", "localidades", "larvas"),
             "A página Resultados Lab consolida as leituras registradas, permitindo acompanhar tabelas, evolução e distribuição por localidade.",
             ("Use a aba Tabela para localizar uma leitura específica.",
              "Use Evolução para comparar períodos e tendências.",
              "Use Localidades para identificar onde há resultados concentrados."),
             "/laboratorio", "Abrir Resultados Lab", ("Tabela", "Evolução", "Localidades")),
    _artigo("laboratorio-pendentes", "Ler tubos pendentes", "Laboratório", ("/laboratorio/lancamentos",),
             ("laboratorio", "tubo", "pendente", "coleta", "agente", "pe", "tb", "tbo", "pve"),
             "Cada cartão pendente representa um tubo vindo de uma visita ou coleta ainda sem resultado. O cartão informa origem, agente e tipo de trabalho.",
             ("Confira o código do tubo e a origem antes de lançar o resultado.",
              "Tubos de equipes externas, como UBS, podem levar alguns dias para chegar ao setor.",
              "Não use esta tela para criar tubos sem uma coleta correspondente."),
             "/laboratorio/lancamentos", "Abrir lançamentos", ("Pendentes", "Tubo")),
    _artigo("laboratorio-resultado", "Enviar o resultado de um tubo", "Laboratório", ("/laboratorio/lancamentos",),
             ("laboratorio", "salvar", "resultado", "aedes", "aegypti", "larva", "pupa", "negativo", "confirmar"),
             "O resultado registra as quantidades encontradas por espécie e forma. A data e o laboratorista são definidos automaticamente pelo envio e pelo usuário conectado.",
             ("Abra o tubo e informe as quantidades efetivamente identificadas.",
              "Resultado negativo só se aplica quando não há Aedes aegypti em nenhuma forma.",
              "Clique em Salvar e confirme a segunda pergunta antes de concluir o lançamento."),
             "/laboratorio/lancamentos", "Abrir lançamentos", ("Lançar resultado", "Salvar")),
    _artigo("laboratorio-historico", "Corrigir uma leitura recente", "Laboratório", ("/laboratorio/lancamentos",),
             ("laboratorio", "historico", "editar", "corrigir", "tubo", "tres dias"),
             "O Histórico mostra leituras concluídas. Envios recentes podem ser corrigidos por alguns dias para reparar um erro de digitação.",
             ("Abra o Histórico e localize o tubo pelo código, data ou origem.",
              "Use Editar somente para ajustar um resultado realmente incorreto.",
              "Tubos sem resultado não aparecem no histórico; eles permanecem fora da fila ou são tratados conforme a situação da coleta."),
             "/laboratorio/lancamentos", "Abrir lançamentos", ("Histórico", "Editar")),
    _artigo("laboratorio-ovitrampas", "Registrar a leitura de ovitrampas", "Laboratório", ("/laboratorio/lancamentos",),
             ("laboratorio", "ovitrampa", "ovos", "ocorrencia", "rota", "diario", "troca", "retirada", "rascunho"),
             "A aba Leitura Ovitrampa reúne os diários que tiveram troca ou retirada. Cada armadilha começa com zero ovos e utiliza o ID e o complemento para identificação.",
             ("Abra o diário correspondente ao documento recebido no laboratório.",
              "Altere somente as armadilhas com ovos; os demais campos podem permanecer em zero.",
              "Quando houver uma ocorrência, abra a lista da armadilha e escolha uma das oito situações. Sem ocorrência, deixe o campo vazio.",
              "Confira o total e conclua a leitura. O rascunho é salvo durante o preenchimento.",
              "Uma leitura concluída ainda pode ser corrigida até ser marcada como enviada ao Conta Ovos."),
             "/laboratorio/lancamentos", "Abrir Leitura Ovitrampa", ("Leitura Ovitrampa", "Pendentes")),
    _artigo("conta-ovos", "Consultar Conta Ovos e SisPNCD", "Campo", ("/conta-ovos-sispncd",),
             ("conta ovos", "sispncd", "pendencias", "ovitrampas", "sincronizacao", "exportar"),
             "A tela reúne consultas de apoio ao Conta Ovos e ao SisPNCD, incluindo pendências que precisam de conferência antes do fechamento.",
             ("Alterne entre Conta Ovos e SisPNCD conforme o dado que precisa conferir.",
              "Use os filtros antes de analisar pendências ou resultados.",
              "Confirme a origem do dado antes de corrigir algo no sistema externo."),
             "/conta-ovos-sispncd", "Abrir Conta Ovos / SisPNCD", ("Conta Ovos", "SisPNCD")),
    _artigo("ovitrampas-importar-leituras", "Importar leituras de ovitrampas", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "leitura", "importar", "csv", "conta ovos", "arquivo", "resultado"),
             "A aba Leituras permite trazer resultados exportados do Conta Ovos e conferi-los antes de trabalhar nos dados do monitoramento.",
             ("Use o arquivo exportado pelo Conta Ovos no formato solicitado pela tela.",
              "Confira o retorno da importação antes de considerar as leituras concluídas.",
              "Se houver dados iguais, revise o período e o grupo para evitar duplicidade."),
             "/ovitrampas", "Abrir Ovitrampas", ("Leituras", "Importar")),
    _artigo("ovitrampas-laboratorio", "Conferir leituras antes do Conta Ovos", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "laboratorio", "conta ovos", "pendente", "enviado", "rota", "diario", "ocorrencia"),
             "A aba Laboratório funciona como espelho dos resultados enviados pelo laboratorista antes do lançamento manual no Conta Ovos.",
             ("Abra um diário concluído e confira as armadilhas em ordem numérica de ID.",
              "Use as quantidades de ovos e as ocorrências durante a digitação no Conta Ovos.",
              "Depois de lançar todo o diário, marque-o como enviado ao Conta Ovos.",
              "A confirmação bloqueia novas correções do laboratorista para preservar o registro utilizado."),
             "/ovitrampas", "Abrir Laboratório de Ovitrampas", ("Laboratório", "Conta Ovos"), nivel_minimo="operador"),
    _artigo("ovitrampas-lote", "Editar leituras em lote", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "lote", "laboratorista", "data leitura", "selecionar", "editar"),
             "A edição em lote agiliza situações em que várias leituras receberam a mesma data ou foram feitas pela mesma pessoa.",
             ("Filtre e marque apenas as leituras que devem mudar juntas.",
              "Preencha o laboratorista e/ou a data de leitura desejada.",
              "Revise a quantidade selecionada antes de aplicar a alteração."),
             "/ovitrampas", "Abrir Ovitrampas", ("Leituras", "Lote")),
    _artigo("ovitrampas-monitoramento", "Acompanhar o monitoramento", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "monitoramento", "semana", "indice", "mapa", "positividade"),
             "A aba Monitoramento reúne os indicadores das leituras por semana, diário ou localidade para acompanhamento do programa.",
             ("Escolha ano e semana epidemiológica antes de comparar resultados.",
              "Use os filtros de localidade ou grupo para reduzir a análise à área desejada.",
              "Considere registros sem leitura separadamente de resultados negativos."),
             "/ovitrampas", "Abrir Ovitrampas", ("Monitoramento",)),
    _artigo("ovitrampas-armadilhas", "Manter o cadastro de armadilhas", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "armadilhas", "cadastro", "endereco", "quarteirao", "historico", "realocar"),
             "A aba Armadilhas mantém os dados operacionais, como endereço, número, quarteirão e localização. As alterações ficam registradas no histórico.",
             ("Localize a armadilha pelo código, endereço ou localidade.",
              "Atualize os dados quando houver mudança real de posição ou responsável.",
              "Registre a justificativa da alteração para que o histórico explique o que mudou."),
             "/ovitrampas", "Abrir Ovitrampas", ("Armadilhas", "Histórico")),
    _artigo("ovitrampas-diario-impressao", "Organizar e imprimir um diário", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "diario", "imprimir", "rota", "arrastar", "ordem", "qr code"),
             "O Diário organiza a sequência de campo. A ordem é editável por arrastar e soltar, e a impressão mantém a ficha pensada para uso durante o ciclo.",
             ("Escolha o diário que deseja organizar.",
              "Use o controle de arrastar para mover uma armadilha para a posição desejada.",
              "Revise a ordem e imprima o diário; o mesmo impresso atende os movimentos do ciclo."),
             "/ovitrampas", "Abrir Ovitrampas", ("Diários", "Imprimir")),
    _artigo("ovitrampas-calendario", "Consultar o calendário de ovitrampas", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "calendario", "instalacao", "recolhimento", "leitura", "grupo", "ciclo"),
             "O Calendário concentra os movimentos previstos das ovitrampas para ajudar no planejamento dos ciclos de instalação, recolhimento e leitura.",
             ("Navegue até o mês ou período desejado.",
              "Confira o grupo e a etapa prevista antes de organizar a equipe.",
              "Use a Agenda para conciliar atividades de campo com os demais compromissos do setor."),
             "/ovitrampas", "Abrir Ovitrampas", ("Calendário",)),
    _artigo("esporo-visitas-animais", "Consultar animais nas visitas", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "animais", "detalhes", "visita", "agente", "ferido", "busca"),
             "Na subaba Animais, cada animal vem de uma visita do Kobo. Os detalhes mostram os dados relacionados àquela visita e permitem acompanhar busca de animal ferido.",
             ("Aplique os filtros para encontrar o conjunto de animais desejado.",
              "Clique em Detalhes para ver o agente, a visita e demais informações de origem.",
              "Ao registrar uma busca, informe data e agente; ela entra no histórico do animal e aparece automaticamente na Agenda.",
              "Se houver uma nova tentativa, use Registrar nova busca sem apagar as anteriores.",
              "Se o diagnóstico for confirmado, use Cadastrar como doente para abrir o cadastro clínico com os dados da visita já preenchidos."),
             "/esporotricose", "Abrir Esporotricose", ("Visitas", "Animais", "Detalhes")),
    _artigo("esporo-visitas-resumos", "Resumir visitas por localidade", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "resumo", "localidades", "dashboard", "visitas", "grafico"),
             "As subabas Resumo, Localidades e Dashboard mostram a produção importada do Kobo em diferentes níveis de detalhe.",
             ("Use Resumo para uma visão rápida do período.",
              "Use Localidades para comparar áreas atendidas.",
              "Use Dashboard para gráficos e acompanhamento visual das visitas."),
             "/esporotricose", "Abrir Esporotricose", ("Visitas", "Resumo", "Localidades", "Dashboard")),
    _artigo("esporo-doentes-cadastro", "Cadastrar e acompanhar um animal doente", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "doentes", "animal", "tutor", "cpf", "especie", "gato", "cao", "excluir"),
             "A Lista de Doentes é um cadastro manual, separado das visitas do Kobo. Ela reúne animal, espécie, situação, tutor, telefone e CPF quando informado.",
             ("Cadastre a espécie correta; os registros antigos foram considerados gatos, exceto onde houver exceção cadastrada.",
              "Preencha os dados do tutor que forem necessários para contato e controle.",
              "Excluir exige confirmação dupla porque remove o registro do animal doente."),
             "/esporotricose", "Abrir Doentes", ("Doentes", "Lista")),
    _artigo("esporo-receitas-entregas", "Controlar receita, entregas e próxima data", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "receita", "entrega", "capsulas", "posologia", "proxima entrega", "zoomed"),
             "A receita define a quantidade e a posologia. Cada dispensação deve registrar a quantidade realmente entregue, normalmente em parcelas de até 30 cápsulas.",
             ("Cadastre ou edite a receita com a posologia; o padrão é 1 cápsula por dia para receitas antigas.",
              "Lance uma entrega por vez, sem registrar totais acumulados como se fossem uma única entrega.",
              "A próxima entrega é calculada pela última dispensação dividida pela posologia, e só aparece para animais em tratamento."),
             "/esporotricose", "Abrir Doentes", ("Doentes", "Receitas", "Cápsulas")),
    _artigo("esporo-sem-receita", "Registrar entrega sem receita cadastrada", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "sem receita", "excedente", "nat", "entrega", "medicacao"),
             "Entregas sem receita podem ser registradas enquanto se aguarda o documento. Nessa situação não há como calcular faltantes ou próxima entrega até que a receita seja cadastrada.",
             ("Registre a quantidade dispensada e mantenha a observação de que a receita está pendente.",
              "Cadastre a receita assim que ela chegar para que o saldo e a próxima entrega sejam calculados.",
              "Não interprete “excedente” como sobra disponível: é uma entrega ainda sem quantidade prescrita para comparação."),
             "/esporotricose", "Abrir Doentes", ("Doentes", "Cápsulas")),
    _artigo("esporo-resumo", "Ler o resumo dos doentes", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "resumo", "tratamento", "capsulas", "entregues", "faltantes", "zoomed"),
             "A subaba Resumo consolida animais, tratamentos, cápsulas entregues, faltantes e baixas no Zoomed para acompanhamento rápido.",
             ("Compare entregues e faltantes apenas entre animais em tratamento.",
              "Use o card de baixas no Zoomed para acompanhar as receitas já baixadas.",
              "Investigue valores negativos no estoque antes de concluir que há perda física de medicação."),
             "/esporotricose", "Abrir Doentes", ("Doentes", "Resumo")),
    _artigo("esporo-estoque", "Controlar o estoque de medicação", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "estoque", "entrada", "saida", "sobra", "saldo", "reserva", "editar"),
             "O estoque reúne entradas, saídas vinculadas às entregas, sobras reaproveitáveis e o saldo do setor. Movimentos ficam editáveis após clicar em Editar.",
             ("Registre entradas físicas reais do setor; não registre sobra como nova entrada se ela já veio de uma entrega anterior.",
              "As saídas são criadas a partir das entregas de receita, inclusive para manter o histórico consistente.",
              "Saldo após reserva mostra o saldo físico menos as cápsulas ainda necessárias para receitas em tratamento."),
             "/esporotricose", "Abrir Doentes", ("Doentes", "Estoque medicação", "Editar")),
    _artigo("recolhimentos", "Consultar recolhimentos", "Campo", ("/recolhimentos",),
             ("recolhimentos", "animais", "filtro", "coleta", "destino", "visita", "pneu", "louca"),
             "A página Recolhimentos organiza os registros de coleta de materiais feitos em campo, com totais por tipo de material e por localidade.",
             ("Comece pelo período: preencha Data inicial e Data final antes dos demais filtros.",
              "Refine por Localidade, Agente ou Origem para chegar ao recorte desejado.",
              "Use a Pesquisa para procurar por endereço, observação ou referência do registro.",
              "Os cartões no topo somam pneus, louças e outros materiais do recorte filtrado.",
              "O bloco Por localidade mostra onde o recolhimento se concentrou no período.",
              "Confira a contagem de registros ao lado do título da tabela para saber o tamanho do resultado."),
             "/recolhimentos", "Abrir Recolhimentos",
             atencao=(
                 "Os totais sempre refletem os filtros aplicados. Se um número parecer baixo, confira primeiro o período.",
                 "Recolhimentos chegam pela Importação Kobo. Se um registro de campo não aparece, verifique se a importação do dia foi feita.",
                 "Corrija dados errados no formulário de origem e importe de novo; editar só a consulta não resolve.",
             )),
    _artigo("amostras-animais", "Consultar amostras de animais", "Campo", ("/amostras-animais",),
             ("amostra", "animais", "laboratorio", "coleta", "resultado", "filtro", "captura", "acidente"),
             "Amostra de Animais reúne capturas, acidentes, reclamações e investigações registrados em campo, com totais por tipo de ocorrência.",
             ("Defina o período nos campos de data antes de analisar os números.",
              "Filtre por Localidade, Agente ou tipo de ocorrência conforme a pergunta que precisa responder.",
              "Os cartões separam capturas, acidentes, reclamações e investigações do recorte.",
              "Use a Pesquisa para localizar um animal, endereço ou referência específica.",
              "Abra o registro para conferir os dados completos antes de qualquer conclusão.",
              "O bloco por localidade ajuda a ver concentração de ocorrências em uma área."),
             "/amostras-animais", "Abrir Amostra de Animais",
             atencao=(
                 "Cada tipo de ocorrência é contado separadamente; não some os cartões esperando o total de registros.",
                 "A origem dos dados é o formulário de campo. Uma correção precisa ser feita lá e reimportada.",
             )),
    _artigo("bri", "Consultar BRI", "Campo", ("/bri",),
             ("bri", "boletim", "campo", "filtros", "imprimir", "indicadores", "destino", "carga", "larvicida"),
             "A página BRI reúne os registros de Bloqueio e Redução de Infestação, com totais por destino do tratamento e por localidade.",
             ("Preencha Data inicial e Data final para delimitar o período.",
              "Use Destino para separar os tipos de tratamento, incluindo Ponto Estratégico.",
              "Filtre por Localidade, Agente ou Origem para chegar ao recorte necessário.",
              "O bloco Por destino mostra a distribuição do tratamento aplicado no período.",
              "O bloco Por localidade indica onde o esforço se concentrou.",
              "Use a Pesquisa para localizar um endereço ou registro pontual.",
              "Imprima somente depois de conferir que os filtros representam o recorte desejado."),
             "/bri", "Abrir BRI",
             atencao=(
                 "Registros com destino Ponto Estratégico também alimentam a página Pontos Estratégicos. Se o BRI de um PE não aparece lá, confira se o destino foi preenchido corretamente na origem.",
                 "A impressão leva exatamente o que está filtrado na tela; revise os filtros antes de gerar.",
             )),
    _artigo("relatorio-agente", "Gerar relatório por agente", "Análise", ("/relatorio-agente",),
             ("relatorio", "agente", "producao", "periodo", "imprimir", "frente"),
             "O Relatório por Agente consolida a produção por profissional e período para consulta, conferência e impressão.",
             ("Escolha o período que deseja analisar antes de qualquer outro filtro.",
              "Selecione um agente específico ou deixe em branco para ver toda a equipe.",
              "Revise os totais por frente de trabalho: visitas, BRI e demais atividades aparecem separadas.",
              "Compare agentes do mesmo período para entender diferenças de produção.",
              "Use a impressão para levar o relatório a uma reunião ou encaminhar à chefia."),
             "/relatorio-agente", "Abrir Relatório por Agente",
             atencao=(
                 "Produção baixa pode significar importação pendente, e não trabalho não realizado. Confira a Importação Kobo do período antes de concluir qualquer coisa.",
                 "Um agente só aparece se estiver cadastrado em Controle de Pessoal e vinculado aos registros.",
             )),
    _artigo("boletim-mensal", "Montar o Boletim Mensal", "Análise", ("/boletim-mensal",),
             ("boletim", "mensal", "producao", "acoes", "educativas", "limpeza", "periodo", "whatsapp"),
             "O Boletim Mensal consolida os indicadores do mês e soma as ações educativas e de limpeza registradas no setor.",
             ("Selecione o mês desejado no campo de período no topo da página.",
              "Aguarde o carregamento e confira o total consolidado apresentado.",
              "Percorra as linhas do boletim conferindo cada indicador antes de divulgar.",
              "Use o botão de envio por WhatsApp quando precisar compartilhar o resumo rapidamente.",
              "Imprima ou salve o boletim como registro do mês fechado."),
             "/boletim-mensal", "Abrir Boletim Mensal",
             atencao=(
                 "O boletim é uma consolidação: ele apenas soma o que já existe. Corrigir um número aqui não é possível, a correção é sempre no módulo de origem.",
                 "Feche o mês só depois de garantir que todas as importações do período foram feitas, senão o boletim sai incompleto.",
                 "Ações educativas e de limpeza vêm de Ações e Atendimentos; se faltarem, confira se foram registradas lá.",
             )),
    _artigo("notificacoes", "Acompanhar notificações", "Gestão", ("/notificacoes",),
             ("notificacoes", "situacao", "filtro", "atualizar", "imprimir", "caso", "foco", "docx"),
             "Notificações reúne os focos que geram documento oficial, permite selecionar vários casos e emitir a notificação em HTML ou DOCX.",
             ("Use os filtros para separar os focos que precisam de notificação.",
              "Marque os casos desejados na lista; a caixa Selecionar todos marca o conjunto inteiro de uma vez.",
              "Acompanhe o contador de selecionados para confirmar quantos documentos serão gerados.",
              "Escolha Imprimir em HTML para conferir na tela ou gerar PDF pelo navegador.",
              "Escolha Imprimir em DOCX quando precisar editar o documento no Word antes de entregar.",
              "Confira nome, endereço e data em cada documento antes de imprimir para entrega."),
             "/notificacoes", "Abrir Notificações",
             atencao=(
                 "Só são notificados os focos marcados como geradores de notificação. Um foco registrado não vira documento automaticamente.",
                 "Gerar o documento não registra a entrega ao morador; esse controle continua sendo do setor.",
                 "Confira o endereço antes de imprimir: documento com endereço errado precisa ser refeito.",
             )),
    _artigo("mapa-geral", "Usar o Mapa do sistema", "Gestão", ("/mapa",),
             ("mapa", "camadas", "localidades", "satelite", "cores", "filtro", "pontos", "quarteirao"),
             "O Mapa reúne informações territoriais do setor. Camadas, filtros e cores permitem focar na área relevante para a análise.",
             ("Ative somente as camadas necessárias para evitar poluição visual.",
              "Use filtros de localidade para reduzir o mapa à área desejada.",
              "Aproxime o zoom até enxergar os quarteirões antes de tirar conclusões sobre um ponto.",
              "Clique em um ponto para ver os dados vinculados a ele.",
              "A imagem de satélite é uma camada de referência; o Registro Geográfico continua sendo a fonte dos dados de imóveis."),
             "/mapa", "Abrir Mapa",
             atencao=(
                 "Registros sem coordenada não aparecem no mapa. A ausência de um ponto não significa ausência do registro.",
                 "O mapa depende de conexão com a internet para carregar as imagens de fundo. Sem rede, o fundo fica cinza mas os pontos continuam.",
             )),
    _artigo("registro-geografico-grade", "Navegar pela grade do RG", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "edicao", "grade", "setas", "copiar", "preencher", "linha", "celula"),
             "A grade de Edição foi desenhada para uso semelhante a uma planilha: a célula e a linha ativas ficam destacadas, e as linhas alternam cores para leitura mais fácil.",
             ("Clique em uma célula e use as setas do teclado para se mover pela grade.",
              "Use Copiar de cima para repetir dados da linha anterior quando fizer sentido.",
              "Use Preencher abaixo ou Preencher vazios com atenção, conferindo a prévia da informação que será repetida."),
             "/registro-geografico", "Abrir Edição do RG", ("Edição", "Grade")),
    _artigo("registro-geografico-quarteirao", "Criar, renomear ou apagar quarteirão", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "quarteirao", "adicionar", "novo", "apagar", "localidade", "numeracao", "limpar"),
             "Na Edição é possível criar um quarteirão, mudar sua localidade ou numeração, limpar as linhas para recomeçar e apagar completamente um quarteirão sem dados necessários.",
             ("Use Novo quarteirão para criar uma área ainda não cadastrada.",
              "Ao salvar o destino, confira a localidade e a numeração para evitar duplicar códigos.",
              "Limpar quarteirão e Apagar quarteirão exigem confirmação; use apagar apenas quando o cadastro inteiro não deve existir."),
             "/registro-geografico", "Abrir Edição do RG", ("Edição", "Novo quarteirão", "Apagar")),
    _artigo("registro-geografico-logradouros", "Normalizar logradouros em lote", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "edicao em lotes", "logradouro", "parecidos", "normalizar", "substituir", "similaridade"),
             "A Edição em lotes encontra logradouros parecidos e permite padronizar nomes sem editar cada imóvel individualmente.",
             ("Primeiro use a busca de logradouros parecidos para identificar variações do mesmo nome.",
              "Escolha o campo e o modo de substituição; confira a prévia antes de aplicar.",
              "Use alterações em lote apenas quando todos os registros selecionados realmente devem receber o mesmo texto."),
             "/registro-geografico", "Abrir Edição em lotes", ("Edição em lotes", "Logradouros parecidos")),
    _artigo("registro-geografico-imprimir-detalhes", "Imprimir fichas do RG com mapas", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "impressao", "mapas", "satelite", "osm", "frente e verso", "selecionar tudo", "pagina impar"),
             "A impressão pode incluir dois mapas, satélite e ruas, além da ficha de imóveis. Há opção para iniciar cada quarteirão na frente da folha em impressão frente e verso.",
             ("Escolha a localidade e use Selecionar tudo quando for imprimir a área completa.",
              "Marque Incluir mapas para gerar satélite e OSM/Ruas; desmarque para quarteirões que ainda não precisam de mapa.",
              "Ative o modo frente e verso para inserir uma página em branco quando necessário e manter cada início em página ímpar."),
             "/registro-geografico", "Abrir Impressão do RG", ("Impressão", "Selecionar tudo")),
    _artigo("registro-geografico-analise", "Selecionar áreas no mapa do RG", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "mapa", "analise", "selecionar", "totais", "populacao", "imoveis", "equipamentos da saude"),
             "No Mapa / Análise, uma seleção de quarteirões calcula imóveis, tipos e população. Quando há vários selecionados, a lista lateral substitui o detalhe de um único quarteirão.",
             ("Escolha uma ou mais localidades para exibir os polígonos correspondentes.",
              "Clique nos polígonos para adicionar ou remover quarteirões da seleção.",
              "Use as cores por localidade, as camadas de satélite e os Equipamentos da Saúde como apoio visual."),
             "/registro-geografico", "Abrir Mapa / Análise", ("Mapa / Análise", "Totais da seleção")),
    _artigo("pe-atrasos", "Tratar atrasos de Pontos Estratégicos", "Campo", ("/pontos-estrategicos",),
             ("pe", "atrasado", "visita", "importacao", "kobo", "ponto estrategico", "prazo"),
             "Um PE em atraso normalmente indica ausência de visita vinculada dentro do prazo. Antes de corrigir, confira se a visita foi registrada no Kobo com o ponto correto.",
             ("Filtre os pontos em atraso e abra o histórico do local.",
              "Confira no Kobo se houve duplicidade ou registro no ponto errado.",
              "Depois de corrigir o dado de origem, importe novamente a visita e atualize a situação do PE."),
             "/pontos-estrategicos", "Abrir Pontos Estratégicos"),
    _artigo("acoes-registro", "Registrar ação ou atendimento", "Ações e Atendimentos", ("/acoes-setor",),
             ("acoes", "atendimento", "vistoria", "reuniao", "limpeza", "periodo", "caso", "resultado", "parceiros"),
             "A página reúne ações educativas, limpezas, atendimentos técnicos, reuniões e outros registros institucionais.",
             ("Clique em Novo registro para abrir o formulário.",
              "Escolha o tipo, a situação e o período; a data final e os horários são opcionais.",
              "Informe Caso / acompanhamento quando várias atividades pertencerem à mesma situação.",
              "Para ação educativa, selecione uma ou mais atividades, públicos-alvo e recursos utilizados.",
              "Registre resultados, providências e órgãos parceiros nos campos próprios.",
              "Após o primeiro salvamento, os anexos ficam disponíveis na mesma janela."),
             "/acoes-setor", "Abrir Ações e Atendimentos", ("Registros", "Vistoria / atendimento técnico")),
    _artigo("acoes-consulta", "Consultar e editar registros", "Ações e Atendimentos", ("/acoes-setor",),
             ("acoes", "atendimentos", "filtros", "caso", "situacao", "servidor", "localidade", "data", "editar"),
             "A área Registros reúne indicadores, filtros combináveis e ordenação para localizar as atividades do setor.",
             ("Combine pesquisa, tipo, situação, caso, período, localidade, servidor e intervalo de datas.",
              "Use Detalhes para consultar informações e anexos sem abrir o formulário.",
              "Use Editar para abrir o registro em uma janela separada."),
             "/acoes-setor", "Abrir Registros", ("Registros", "Aplicar filtros", "Detalhes")),
    _artigo("acoes-anexos", "Gerenciar anexos e documentos restritos", "Ações e Atendimentos", ("/acoes-setor",),
             ("acoes", "anexos", "restrito", "administracao", "galeria", "imagem", "video", "baixar todos"),
             "A aba Anexos funciona como uma galeria dos arquivos registrados. Documentos restritos ficam disponíveis apenas para administradores.",
             ("Use filtros para restringir por ação, localidade, servidor, datas ou tipo de arquivo.",
              "Clique na miniatura ou no arquivo para abrir ou baixar individualmente.",
              "Ao adicionar um documento sensível, marque Restritos à administração.",
              "Dentro do registro, use Baixar todos os anexos para obter o conjunto completo."),
             "/acoes-setor", "Abrir Anexos", ("Anexos", "Baixar todos")),
    _artigo("acoes-relatorio", "Gerar relatório técnico das ações", "Ações e Atendimentos", ("/acoes-setor",),
             ("acoes", "atendimentos", "relatorio", "pdf", "imagens", "filtros", "imprimir"),
             "A aba Relatório de Ações reúne filtros próprios e gera um documento técnico com síntese, detalhamento e registro fotográfico.",
             ("Defina o período, tipo, situação, localidade, caso ou servidor.",
              "Atualize a prévia para conferir os registros selecionados.",
              "Mantenha Incluir imagens anexadas marcado quando desejar o registro fotográfico.",
              "Use Gerar relatório e escolha Imprimir ou Salvar PDF."),
             "/acoes-setor", "Abrir Relatório de Ações", ("Relatório de Ações", "Gerar relatório")),
    _artigo("agenda-eventos", "Criar e editar eventos na Agenda", "Planejamento", ("/agenda",),
             ("agenda", "novo evento", "editar", "recorrencia", "lembrete", "atividade externa", "calendario"),
             "A Agenda aceita eventos manuais e recorrentes. O calendário também mostra atividades criadas por outros módulos, que devem ser alteradas na origem.",
             ("Clique em um dia ou em Novo evento para preencher título, data e horário.",
              "Use recorrência quando a mesma atividade se repete em uma cadência previsível.",
              "Marque Atividade externa para incluir o evento na verificação meteorológica do expediente."),
             "/agenda", "Abrir Agenda", ("Novo evento", "Calendário")),
    _artigo("agenda-clima", "Usar alertas meteorológicos da Agenda", "Planejamento", ("/agenda",),
             ("agenda", "clima", "chuva", "vento", "temperatura", "campo", "alerta", "8h", "17h"),
             "Para atividades externas em dias úteis, a Agenda considera o período de trabalho das 8h às 17h e sinaliza chuva, vento ou temperaturas extremas conforme a previsão disponível.",
             ("Marque o evento como atividade externa.",
              "Confira o painel de condições antes de organizar a saída de campo.",
              "Trate o alerta como apoio ao planejamento: as condições reais do local ainda devem ser avaliadas pela equipe."),
             "/agenda", "Abrir Agenda", ("Condições para campo", "Clima")),
    _artigo("meteorologia-atualizar", "Atualizar a Meteorologia", "Planejamento", ("/meteorologia",),
             ("meteorologia", "atualizar", "inmet", "bdmep", "atual", "previsao", "provisorio"),
             "A Meteorologia usa dados do INMET e do BDMEP como referência. O card de clima atual é uma estimativa baseada na fonte disponível no momento.",
             ("Use Atualizar para buscar as informações mais recentes disponíveis.",
              "Leia a situação exibida junto de cada dado, especialmente quando ela indicar caráter provisório.",
              "Use os dados para planejamento, não como substituto de uma medição local oficial."),
             "/meteorologia", "Abrir Meteorologia"),
    _artigo("importacao-pendencias", "Ver pendências de todos os formulários Kobo", "Importação Kobo", ("/processar",),
             ("kobo", "pendencias", "formularios", "api", "novos", "previsualizacao", "importar"),
             "Pendências por formulário consulta os formulários configurados e mostra onde há registros novos sem exigir uma prévia individual de cada um.",
             ("Clique em Ver pendências e aguarde a lista dos formulários.",
              "Use o período quando quiser restringir a busca; sem período, a consulta considera todo o histórico disponível.",
              "Abra a prévia do formulário escolhido antes de preparar a importação."),
             "/processar", "Abrir Importação Kobo", ("Pendências por formulário", "Ver pendências")),
    _artigo("importacao-previa", "Conferir prévia e importar pelo Kobo", "Importação Kobo", ("/processar",),
             ("kobo", "previa", "importacao", "api", "campos obrigatorios", "atencao", "normalizacao"),
             "A prévia valida os registros antes de gravar no banco. Avisos apontam campos incompletos ou vínculos que merecem conferência, sem transformar situações legítimas em erro.",
             ("Clique em Ver pendências e use Prévia na linha do formulário desejado.",
              "Leia os avisos de atenção e confira a origem quando houver inconsistência real.",
              "Clique em Importar na mesma linha somente depois de revisar a quantidade e os dados exibidos."),
             "/processar", "Abrir Importação Kobo", ("Ver pendências", "Prévia", "Importar")),
    _artigo("importacao-planilhas", "Usar importação por planilhas", "Importação Kobo", ("/processar",),
             ("kobo", "planilha", "xlsx", "emergencial", "arrastar", "arquivo", "importacao"),
             "Importação por Planilhas é um recurso emergencial para arquivos XLSX exportados manualmente do Kobo. A API deve ser preferida na rotina normal.",
             ("Abra a seção Importação por Planilhas.",
              "Arraste os arquivos XLSX ou clique na área de arquivos para selecioná-los.",
              "Confira o processamento e a auditoria da importação antes de descartar o arquivo de origem."),
             "/processar", "Abrir Importação Kobo", ("Importação por Planilhas", "Arquivos XLSX")),
    _artigo("importacao-consolidados", "Gerar consolidados em planilha", "Importação Kobo", ("/processar",),
             ("consolidados", "planilha", "excel", "gerar", "baixar", "visitas", "coletas"),
             "Consolidados em planilha gera arquivos de consulta quando solicitado. Cada arquivo reúne abas adequadas aos dados disponíveis, como Visitas e Coletas.",
             ("Escolha Gerar no arquivo desejado ou Gerar todos quando precisar atualizar o conjunto.",
              "Aguarde a geração terminar antes de clicar em Baixar.",
              "Use estes arquivos para consulta e compartilhamento; o banco do sistema continua sendo a fonte principal."),
             "/processar", "Abrir Importação Kobo", ("Consolidados em planilha", "Gerar todos")),
    _artigo("central-backup", "Fazer backup pela Central do Sistema", "Administração", ("/admin/sistema",),
             ("backup", "central", "sistema", "banco", "arquivos", "d backupsendemias", "restaurar"),
             "A Central do Sistema concentra o backup do banco e dos arquivos importantes. Os backups devem ser guardados também fora do computador que executa o sistema.",
             ("Gere um backup antes de mudanças grandes ou periodicamente.",
              "Confirme a data e o tamanho do arquivo criado em D:\\BackupsEndemias.",
              "Copie os backups relevantes para outra unidade, servidor ou armazenamento confiável."),
             "/admin/sistema", "Abrir Central do Sistema", nivel_minimo="admin"),
    _artigo("usuarios-permissoes", "Gerenciar usuários e permissões", "Administração", ("/admin/usuarios",),
             ("usuarios", "permissoes", "senha", "admin", "operador", "visualizador", "laboratorista"),
             "Gestão de Usuários cria contas, ajusta níveis e limita o acesso quando necessário. O usuário Laboratorista pode ficar restrito à tela de lançamentos de laboratório.",
             ("Crie cada conta com nome e senha próprios; não compartilhe credenciais.",
              "Escolha o nível conforme a necessidade: visualizador, operador ou administrador.",
              "Use o acesso somente ao laboratório para quem deve trabalhar exclusivamente com os tubos."),
             "/admin/usuarios", "Abrir Gestão de Usuários", nivel_minimo="admin"),
    _artigo("agentes-cadastro", "Gerenciar agentes e equipes", "Administração", ("/admin/agentes",),
             ("agentes", "cadastro", "equipe", "nome", "normalizacao", "usuario"),
             "Gestão de Agentes mantém os nomes usados pelos módulos e pelas importações. Padronizar esses nomes evita que a mesma pessoa apareça em duplicidade.",
             ("Localize o agente antes de criar um novo cadastro.",
              "Ajuste a grafia quando a origem tiver variações conhecidas.",
              "Confira os reflexos em filtros e relatórios depois de uma alteração importante."),
             "/admin/agentes", "Abrir Gestão de Agentes", nivel_minimo="admin"),
    _artigo("auditoria", "Consultar a auditoria do sistema", "Administração", ("/admin/auditoria",),
             ("auditoria", "historico", "alteracoes", "usuario", "importacao", "registro"),
             "A auditoria registra ações relevantes, como importações e alterações. Ela serve para investigação e rastreabilidade, não para substituir os dados de origem.",
             ("Filtre por período, usuário ou tipo de ação quando precisar rastrear uma alteração.",
              "Leia os detalhes do evento antes de assumir a causa de uma mudança.",
              "Use as informações para corrigir o dado no módulo adequado."),
             "/admin/auditoria", "Abrir Auditoria", nivel_minimo="admin"),
    _artigo("ajuda-como-usar", "Encontrar uma orientação na Ajuda", "Geral", ("/",),
             ("ajuda", "pesquisar", "categoria", "duvida", "orientacao", "nesta pagina"),
             "A Ajuda prioriza orientações da tela e da aba abertas, mas também permite pesquisar todo o manual local do sistema.",
             ("Abra Ajuda e confira primeiro a seção Nesta página.",
              "Digite palavras do que deseja fazer, como imprimir diário ou corrigir receita.",
              "Use a categoria para reduzir os resultados a um módulo específico."),
             "/", "Abrir início"),
    _artigo("seguranca-exclusoes", "Entender confirmações para apagar dados", "Geral", ("/",),
             ("apagar", "excluir", "confirmacao", "dupla", "seguranca", "desfazer"),
             "Ações que removem registros importantes usam confirmação adicional para reduzir exclusões acidentais.",
             ("Leia qual registro e quais dados vinculados serão removidos.",
              "Cancele quando o nome ou o contexto não for exatamente o esperado.",
              "Confirme definitivamente somente quando a exclusão for intencional; alguns dados não podem ser recuperados sem backup."),
             "/", "Abrir início"),
    _artigo("senha-pessoal", "Alterar a própria senha", "Geral", ("/minha-senha",),
             ("senha", "alterar senha", "conta", "usuario", "acesso", "seguranca"),
             "Cada usuário pode trocar a própria senha sem acessar a Gestão de Usuários.",
             ("Abra o menu do usuário no canto superior e escolha Alterar senha.",
              "Informe a senha atual e a nova senha conforme os requisitos exibidos.",
              "Não compartilhe a senha nem use a conta de outra pessoa."),
             "/minha-senha", "Abrir Alterar senha"),
    _artigo("esporo-data-notificacao", "Usar a data de notificação do animal", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "doentes", "data", "notificacao", "cadastro", "ordenar", "receita"),
             "A data de notificação pertence ao cadastro do animal doente, não à receita. Ela identifica quando o caso foi registrado para acompanhamento.",
             ("Em um novo cadastro, a data atual é preenchida automaticamente.",
              "Altere a data no cadastro do paciente quando a notificação tiver ocorrido antes.",
              "Na lista, clique no cabeçalho Data para alternar entre casos mais recentes e mais antigos."),
             "/esporotricose#doentes", "Abrir Doentes", ("Doentes", "Lista")),
    _artigo("esporo-buscas-ferido", "Registrar mais de uma busca de animal ferido", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "animais", "busca ferido", "agenda", "agente", "data", "historico"),
             "Cada tentativa de busca de um animal ferido fica no histórico dos detalhes da visita e pode gerar acompanhamento na Agenda.",
             ("Abra Visitas, entre em Animais e use Detalhes no animal desejado.",
              "Adicione a data, o agente e uma observação para cada tentativa realizada.",
              "Registre uma nova busca quando houver outra ida ao local; não substitua a anterior."),
             "/esporotricose#animais", "Abrir Animais", ("Visitas", "Animais", "Busca ferido")),
    _artigo("esporo-vincular-doente", "Cadastrar um animal visitado como doente", "Esporotricose", ("/esporotricose",),
             ("esporotricose", "visita", "animal", "doente", "cadastrar", "vincular", "detalhes"),
             "Um animal encontrado nas visitas pode iniciar um cadastro de doente com os dados já disponíveis, mantendo o vínculo com a visita original.",
             ("Abra os detalhes do animal na sub-aba Animais.",
              "Use Cadastrar como doente e revise os dados preenchidos automaticamente.",
              "Complete as informações clínicas e salve; a visita original permanece inalterada."),
             "/esporotricose#animais", "Abrir Animais", ("Visitas", "Animais", "Detalhes")),
    _artigo("ovitrampas-historico", "Consultar alterações das armadilhas", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "armadilhas", "historico", "endereco", "numero", "quarteirao", "localizacao", "alteracao"),
             "O histórico registra mudanças relevantes de uma ovitrampa, principalmente número, endereço, quarteirão e localização.",
             ("Abra a aba Armadilhas e localize a ovitrampa.",
              "Ao alterar o cadastro, descreva a razão de forma objetiva.",
              "Consulte o histórico para entender o endereço anterior e quando a mudança ocorreu."),
             "/ovitrampas", "Abrir Armadilhas", ("Armadilhas", "Histórico")),
    _artigo("ovitrampas-realocar", "Tratar armadilhas para realocação", "Ovitrampas", ("/ovitrampas",),
             ("ovitrampas", "realocar", "sem diario", "rota", "conta ovos", "pendente"),
             "Armadilhas marcadas como REALOCAR ficam fora dos diários até receberem um novo local e uma posição no diário.",
             ("Atualize o cadastro no Conta Ovos e importe a planilha na aba Diários.",
              "Localize as armadilhas sem diário definido.",
              "Depois da realocação, atribua o diário e arraste a armadilha para a posição correta."),
             "/ovitrampas", "Abrir Diários", ("Diários", "Sem diário", "REALOCAR")),
    _artigo("rg-logradouro-sugestoes", "Usar sugestões de logradouro no RG", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "logradouro", "sugestao", "autocompletar", "digitar", "padronizar", "rua"),
             "Na grade de Edição, o campo de logradouro sugere nomes já existentes para reduzir novas variações de grafia.",
             ("Comece a digitar o nome da rua e aguarde as sugestões.",
              "Escolha uma opção existente quando ela representar o mesmo logradouro.",
              "Quando houver variações antigas, use Edição em lotes para normalizá-las."),
             "/registro-geografico", "Abrir Edição do RG", ("Edição", "Logradouro")),
    _artigo("rg-linhas-ref", "Marcar lados do quarteirão com REF", "Registro Geográfico", ("/registro-geografico",),
             ("rg", "ref", "referencia", "lado", "logradouro", "praca", "triangulo", "imovel"),
             "O tipo REF cria uma linha apenas de referência para indicar um lado, acesso ou logradouro do quarteirão sem contar como imóvel.",
             ("Crie uma linha para o logradouro que precisa aparecer como referência.",
              "Escolha REF no tipo do imóvel.",
              "Não use REF para residências, comércios ou outros imóveis que devam entrar nos totais."),
             "/registro-geografico", "Abrir Edição do RG", ("Edição", "REF")),
    _artigo("laboratorio-corrigir-recente", "Corrigir um resultado laboratorial recente", "Laboratório", ("/laboratorio/lancamentos",),
             ("laboratorio", "historico", "editar", "corrigir", "resultado", "tubo", "tres dias"),
             "Resultados enviados nos últimos três dias podem ser corrigidos no histórico quando houver erro de digitação.",
             ("Abra o Histórico e localize o tubo pelo código ou pela origem.",
              "Use Editar somente quando o registro estiver dentro do prazo disponível.",
              "Revise todas as espécies e quantidades antes de salvar a correção."),
             "/laboratorio/lancamentos", "Abrir Histórico", ("Histórico", "Editar")),
    _artigo("central-diagnostico", "Verificar a saúde do sistema", "Administração", ("/admin/sistema",),
             ("central", "sistema", "diagnostico", "integridade", "banco", "backup", "espaco"),
             "A Central do Sistema mostra verificações operacionais do banco, dos backups e dos arquivos essenciais.",
             ("Leia primeiro os itens marcados como atenção ou erro.",
              "Atualize o diagnóstico completo quando precisar de uma conferência mais ampla.",
              "Crie um backup antes de executar correções administrativas importantes."),
             "/admin/sistema", "Abrir Central do Sistema", nivel_minimo="admin"),
    _artigo("central-restaurar", "Restaurar um backup do banco", "Administração", ("/admin/sistema",),
             ("backup", "restaurar", "banco", "seguranca", "reverter", "central"),
             "Restaurar substitui o banco atual pelo conteúdo de um backup e deve ser usado somente quando houver uma necessidade confirmada.",
             ("Confirme a data e o tamanho do backup escolhido.",
              "Garanta que ninguém esteja alterando dados durante a restauração.",
              "Após restaurar, confira o diagnóstico e as páginas relacionadas ao problema."),
             "/admin/sistema", "Abrir Backups", nivel_minimo="admin"),
)


# Orientacao para quem usa o sistema de vez em quando: primeiros passos, siglas,
# rotinas do dia a dia e o que fazer quando algo parece errado.
ARTIGOS += (
    _artigo("primeiros-passos", "Primeiro acesso: por onde começar", "Geral", ("/",),
             ("comecar", "primeiro", "novo", "iniciante", "basico", "aprender", "duvida"),
             "Se você usa o sistema de vez em quando, este roteiro mostra o caminho seguro para se localizar antes de mexer em qualquer coisa.",
             ("Comece pela tela Início: ela mostra o que precisa de atenção hoje.",
              "Abra o menu lateral para ver todas as áreas liberadas para o seu perfil.",
              "Antes de alterar qualquer dado, use os filtros só para consultar e se familiarizar.",
              "Consulte esta Ajuda na própria página em que estiver: os primeiros tópicos são sempre sobre a tela aberta.",
              "Use a busca da Ajuda com uma palavra simples, como pneu, receita ou semana.",
              "Se ficar em dúvida sobre uma ação que grava dados, prefira perguntar antes de salvar."),
             "/", "Abrir Início",
             atencao=(
                 "Consultar e filtrar nunca estraga nada. Você pode explorar as telas à vontade.",
                 "As ações que gravam, excluem ou enviam dados são as que exigem cuidado. Na dúvida, não confirme.",
             )),
    _artigo("glossario-siglas", "Entender as siglas do setor", "Geral", ("/",),
             ("sigla", "glossario", "significado", "pe", "pve", "tb", "tbo", "bri", "rg", "sispncd", "ovitrampa"),
             "As siglas aparecem em quase todas as telas. Este resumo evita confusão entre frentes de trabalho parecidas.",
             ("PE é Ponto Estratégico: locais fixos de risco, como ferro-velho e borracharia, visitados periodicamente.",
              "PVE é Ponto de Vigilância Entomológica: imóveis acompanhados para vigilância.",
              "TB é Tratamento de Bloqueio, feito em resposta a um foco encontrado.",
              "TBO é o tratamento com contagem de ovos, ligado às ovitrampas.",
              "BRI é Bloqueio e Redução de Infestação, registrado na página BRI.",
              "RG é o Registro Geográfico, o cadastro de imóveis por quarteirão.",
              "SisPNCD é o sistema nacional; o código do SisPNCD é registrado junto às visitas.",
              "Ovitrampa é a armadilha de coleta de ovos, identificada por um número."),
             "/", "Abrir Início"),
    _artigo("semana-epidemiologica", "Entender a semana epidemiológica", "Geral", ("/",),
             ("semana", "epidemiologica", "ano", "periodo", "calendario", "domingo", "sabado"),
             "Várias telas organizam o trabalho por semana epidemiológica, que não é igual à semana do calendário comum.",
             ("A semana epidemiológica começa no domingo e termina no sábado.",
              "A contagem reinicia a cada ano e vai de 1 até 52 ou 53.",
              "O número da semana atual aparece no topo da página, ao lado do nome do setor.",
              "Ao filtrar por semana, informe ano e número: as duas informações juntas definem o período.",
              "Se precisar da semana de uma data específica, confira o indicador do topo na data desejada."),
             "/", "Abrir Início",
             atencao=(
                 "A semana 1 de um ano pode começar ainda em dezembro do ano anterior. Ao filtrar a virada do ano, confira o ano informado.",
             )),
    _artigo("nada-aparece", "Quando um registro não aparece na tela", "Geral", ("/",),
             ("sumiu", "nao aparece", "vazio", "faltando", "problema", "erro", "encontrar", "filtro"),
             "Registro que some quase sempre é filtro, período ou importação pendente. Verifique nesta ordem antes de concluir que houve perda de dado.",
             ("Confira o período: datas fora do intervalo escondem o registro.",
              "Limpe a pesquisa e os filtros de localidade, agente e tipo, depois filtre de novo aos poucos.",
              "Verifique se há filtro de situação ativo escondendo itens inativos ou encerrados.",
              "Se o dado veio de campo, confira na Importação Kobo se a importação do dia foi feita.",
              "Depois de importar, atualize a página com F5 para recarregar a consulta.",
              "Se ainda assim não aparecer, procure pelo endereço ou por parte do nome na pesquisa."),
             "/", "Abrir Início",
             atencao=(
                 "Não recadastre um registro só porque ele não apareceu: você pode criar duplicidade. Confirme primeiro que ele realmente não existe.",
             )),
    _artigo("rotina-diaria", "Rotina sugerida para o dia a dia", "Geral", ("/",),
             ("rotina", "diaria", "dia", "checklist", "sequencia", "trabalho"),
             "Sequência simples para quem precisa tocar o setor sem acompanhar o sistema todos os dias.",
             ("Abra o Início e leia os alertas e pendências apresentados.",
              "Faça a Importação Kobo dos formulários do dia para trazer o trabalho de campo.",
              "Confira as notificações pendentes e imprima o que precisa ser entregue.",
              "No laboratório, registre as leituras dos tubos pendentes do dia.",
              "Confira os Pontos Estratégicos pendentes na semana atual.",
              "Ao final, confira na Central do Sistema se o backup do dia está saudável."),
             "/", "Abrir Início",
             atencao=(
                 "A importação é o passo que alimenta quase todas as outras telas. Se ela não for feita, os números do dia ficam desatualizados em todo o sistema.",
             )),
    _artigo("conta-ovos-central", "Conhecer a central Conta Ovos", "Conta Ovos", ("/conta-ovos",),
             ("conta ovos", "central", "ovitrampas", "api", "visao geral", "abas", "remoto"),
             "A central Conta Ovos reúne, em modo de consulta, os dados que vieram da API do Conta Ovos. Ela não substitui a página Ovitrampas, que continua sendo a área de trabalho local.",
             ("A aba Visão geral resume os números da integração.",
              "A área Ovitrampas concentra o que veio da API, dividida em cinco abas internas.",
              "Contagens e Monitoramento mostram apenas dados de proveniência API, sem misturar com planilhas antigas.",
              "Cadastro remoto mostra as ovitrampas como estão registradas no Conta Ovos.",
              "Mapa posiciona as ovitrampas pelas coordenadas do cadastro remoto.",
              "Sincronização e divergências compara o cadastro remoto com o local e aponta diferenças.",
              "As áreas EDLs e Quarteirões e ações estão reservadas para uso futuro e ainda não têm dados."),
             "/conta-ovos", "Abrir Conta Ovos",
             ("Visão geral", "Ovitrampas", "Contagens", "Monitoramento", "Cadastro remoto", "Mapa", "Sincronização e divergências"),
             atencao=(
                 "Esta central é somente leitura. Nada do que você faz aqui altera dados no Conta Ovos.",
                 "As telas não consultam a API ao serem abertas: elas mostram o que já foi sincronizado antes. Cadastro remoto e Mapa vazios significam que a sincronização ainda não foi executada.",
                 "Para o trabalho diário de leitura e lançamento, use a página Ovitrampas, não esta central.",
             )),
    _artigo("conta-ovos-divergencias", "Ler as divergências do Conta Ovos", "Conta Ovos", ("/conta-ovos",),
             ("divergencia", "diferenca", "cadastro", "coordenada", "comparar", "sincronizacao"),
             "A aba Sincronização e divergências mostra onde o cadastro remoto e o cadastro local não combinam. Ela apenas informa: nenhuma diferença é corrigida automaticamente.",
             ("Veja primeiro a data da última sincronização para saber a que momento os dados se referem.",
              "Ovitrampas sem cadastro local existem no Conta Ovos mas não no cadastro do setor.",
              "Coordenadas divergentes indicam que a posição registrada aqui e lá é diferente.",
              "Contagens sem cadastro remoto são leituras cuja ovitrampa não foi localizada no Conta Ovos.",
              "Anote as divergências e trate cada caso pelo cadastro correto, na página Ovitrampas."),
             "/conta-ovos", "Abrir Conta Ovos",
             ("Sincronização e divergências",),
             atencao=(
                 "Divergência não é erro do sistema: normalmente indica cadastro desatualizado de um dos lados.",
                 "Não corrija o cadastro remoto por conta própria; a decisão do que prevalece é do responsável pelo setor.",
             )),
    _artigo("pe-semana-feitos", "Ver quais PEs foram feitos na semana", "Campo", ("/pontos-estrategicos",),
             ("pe", "semana", "feito", "pendente", "visita", "epidemiologica", "organizar", "cobranca"),
             "Os filtros de ano e semana epidemiológica marcam cada ponto estratégico ativo como Feito ou Pendente, mostrando o que ainda falta visitar no período.",
             ("Informe o ano e o número da semana nos campos de filtro; a semana atual já vem preenchida.",
              "Clique em Buscar para aplicar o recorte.",
              "Os cartões Feitos na semana e Pendentes na semana mostram o total de cada situação.",
              "A coluna Semana selecionada indica, PE a PE, se houve visita no período.",
              "Escolha Somente pendentes no filtro Na semana para listar apenas o que falta.",
              "Use a exportação em XLSX ou PDF para levar a lista de pendentes a campo."),
             "/pontos-estrategicos", "Abrir Pontos Estratégicos",
             atencao=(
                 "Só PEs ativos entram na contagem de feitos e pendentes. PEs inativos aparecem na lista mas não somam.",
                 "Um PE aparece como Feito quando existe visita registrada no período. Se a visita foi feita mas não importada, ele continua como Pendente.",
                 "Sem preencher ano e semana, a coluna fica vazia e os cartões ficam zerados: isso é o filtro desligado, não ausência de visitas.",
             )),
    _artigo("esporo-anexos-arrastar", "Anexar documentos do animal doente", "Esporotricose", ("/esporotricose",),
             ("anexo", "arrastar", "arquivo", "documento", "receita", "foto", "pdf", "upload"),
             "Na ficha do animal doente, a área de anexos aceita arquivos arrastados direto do computador, sem precisar abrir o explorador de arquivos.",
             ("Abra a ficha do animal doente e localize o bloco Anexos.",
              "Arraste os arquivos do computador e solte sobre a área tracejada; ela fica destacada quando o arquivo está na posição certa.",
              "Se preferir, clique na área para escolher os arquivos pelo explorador.",
              "Os arquivos escolhidos aparecem como etiquetas antes do envio.",
              "Remova um arquivo pelo x da etiqueta caso tenha escolhido errado.",
              "Clique em Enviar anexos para gravar; só depois disso o arquivo fica salvo na ficha."),
             "/esporotricose", "Abrir Esporotricose",
             atencao=(
                 "Escolher o arquivo não salva nada. Enquanto você não clicar em Enviar anexos, ele continua apenas selecionado.",
                 "Anexe documentos legíveis: receita e comprovante ilegíveis atrasam a liberação da medicação.",
             )),
    _artigo("exportar-planilhas", "Exportar listas em XLSX e PDF", "Geral", ("/",),
             ("exportar", "xlsx", "excel", "pdf", "imprimir", "planilha", "salvar", "relatorio"),
             "Várias páginas exportam a lista filtrada em XLSX, para trabalhar no Excel, ou PDF, para imprimir e encaminhar.",
             ("Aplique os filtros até a tela mostrar exatamente o que deve ser exportado.",
              "Confira a contagem de registros antes de exportar.",
              "Escolha XLSX quando precisar somar, ordenar ou editar os dados depois.",
              "Escolha PDF quando precisar imprimir ou enviar um documento fechado.",
              "No PDF, use a opção Salvar como PDF na janela de impressão do navegador."),
             "/", "Abrir Início",
             atencao=(
                 "A exportação leva o recorte filtrado, não a base inteira. Se faltar informação no arquivo, revise os filtros e exporte de novo.",
             )),
    _artigo("periodo-ferias", "Operar o sistema durante uma ausência", "Geral", ("/",),
             ("ferias", "ausencia", "sozinho", "responsavel", "cuidado", "congelamento", "risco"),
             "Com o responsável ausente, o objetivo é manter a rotina funcionando sem criar problemas que exijam socorro técnico.",
             ("Mantenha a rotina normal de importação, laboratório e notificações.",
              "Consulte, filtre e imprima à vontade: nada disso oferece risco.",
              "Evite exclusões definitivas; prefira registrar uma observação e tratar depois.",
              "Não execute restauração de backup nem ações da Central do Sistema sem orientação.",
              "Anote qualquer comportamento estranho com data, hora e tela para relatar no retorno.",
              "Confira periodicamente na Central do Sistema se os backups seguem saudáveis."),
             "/", "Abrir Início",
             atencao=(
                 "Restaurar backup substitui o banco inteiro e desfaz o trabalho registrado depois daquela cópia. Nunca faça isso por conta própria.",
                 "Se algo parecer errado, registre e aguarde. Tentar corrigir sem certeza costuma agravar o problema.",
             )),
)


def _normalizar(value):
    texto = unicodedata.normalize("NFD", str(value or ""))
    return "".join(char for char in texto if unicodedata.category(char) != "Mn").casefold()


def _texto_artigo(artigo):
    return " ".join((
        artigo["titulo"],
        artigo["categoria"],
        artigo["resumo"],
        " ".join(artigo["tags"]),
        " ".join(artigo["passos"]),
        " ".join(artigo.get("atencao", ())),
    ))


def _publico(artigo):
    return {
        "id": artigo["id"],
        "titulo": artigo["titulo"],
        "categoria": artigo["categoria"],
        "resumo": artigo["resumo"],
        "passos": artigo["passos"],
        "atencao": artigo.get("atencao", ()),
        "link": artigo["link"],
        "link_label": artigo["link_label"],
    }


def consultar(consulta="", rota="", limite=12, contexto="", nivel="visualizador", somente_laboratorio=False):
    consulta_normalizada = _normalizar(consulta)
    termos = tuple(term for term in consulta_normalizada.split() if len(term) >= 2)
    contextos_ativos = tuple(
        _normalizar(item).strip()
        for item in str(contexto or "").replace("|", ">").split(">")
        if _normalizar(item).strip()
    )
    rota = str(rota or "/").rstrip("/") or "/"
    ordem_niveis = {"visualizador": 1, "operador": 2, "admin": 3}
    resultados = []
    for artigo in ARTIGOS:
        if ordem_niveis.get(nivel, 0) < ordem_niveis.get(artigo.get("nivel_minimo", "visualizador"), 99):
            continue
        if somente_laboratorio and "/laboratorio/lancamentos" not in artigo["rotas"]:
            continue
        score = 0
        corresponde_contexto = any(
            rota == prefixo or (prefixo != "/" and rota.startswith(prefixo + "/"))
            for prefixo in artigo["rotas"]
        )
        if corresponde_contexto:
            score += 100
            if not contextos_ativos and artigo in ARTIGOS_BASE:
                score += 30
        contextos_artigo = tuple(_normalizar(item) for item in artigo.get("contextos", ()))
        for contexto_ativo in contextos_ativos:
            if contexto_ativo in contextos_artigo:
                score += 100
            elif any(contexto_ativo in item or item in contexto_ativo for item in contextos_artigo):
                score += 20
        texto = _normalizar(_texto_artigo(artigo))
        titulo = _normalizar(artigo["titulo"])
        corresponde_busca = True
        for termo in termos:
            if termo in titulo:
                score += 30
            elif termo in texto:
                score += 10
            else:
                corresponde_busca = False
                break
        if not corresponde_busca:
            continue
        resultados.append((score, artigo))
    resultados.sort(key=lambda item: (-item[0], item[1]["titulo"]))
    contexto_resultado = [_publico(artigo) for score, artigo in resultados if score >= 100]
    categorias = {}
    for _, artigo in resultados:
        categorias[artigo["categoria"]] = categorias.get(artigo["categoria"], 0) + 1
    try:
        limite = int(limite or 12)
    except (TypeError, ValueError):
        limite = 12
    limite = max(1, min(limite, 120))
    return {
        "contexto": contexto_resultado[:5],
        "artigos": [_publico(artigo) for _, artigo in resultados[:limite]],
        "categorias": [
            {"nome": nome, "total": total}
            for nome, total in sorted(categorias.items(), key=lambda item: _normalizar(item[0]))
        ],
        "total": len(resultados),
    }
