"""Valida o historico de importacoes em tabela PostgreSQL temporaria."""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import db as db_core  # noqa: E402
from app_core import import_history  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description="Testa o historico de importacoes sem alterar dados."
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    parser.add_argument(
        "--confirmar-banco",
        help="Obrigatorio para qualquer banco diferente de endemias_teste.",
    )
    return parser


def _temporary_imports(conn):
    conn.execute(
        """
        CREATE TEMPORARY TABLE importacoes (
            id_importacao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id text NOT NULL UNIQUE,
            usuario text,
            arquivos_json text NOT NULL DEFAULT '[]',
            status text NOT NULL DEFAULT 'upload',
            dry_run_ok bigint,
            commit_ok bigint,
            sumario_json text,
            erro text,
            criado_em text NOT NULL,
            atualizado_em text NOT NULL
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.commit()


def main(argv=None):
    args = _parser().parse_args(argv)
    if (
        args.database != SAFE_DATABASE
        and args.confirmar_banco != args.database
    ):
        print(
            "[ERRO] Para testar outro banco, informe "
            f"--confirmar-banco {args.database}"
        )
        return 2

    target = db_core.DatabaseTarget("postgresql", args.database)
    conn = None
    real_close = None
    try:
        conn = db_core.connect(target)
        public_before = conn.execute(
            "SELECT COUNT(*) FROM public.importacoes"
        ).fetchone()[0]
        conn.rollback()
        _temporary_imports(conn)

        real_close = conn.close
        conn.close = lambda: None
        get_db = lambda: conn

        import_history.registrar_importacao(
            get_db,
            "job-postgresql-temporario",
            ["TB.xlsx"],
            usuario="Teste inicial",
        )
        first = conn.execute(
            "SELECT criado_em FROM importacoes WHERE job_id=?",
            ("job-postgresql-temporario",),
        ).fetchone()[0]
        import_history.atualizar_importacao(
            get_db,
            "job-postgresql-temporario",
            "dry_run_ok",
            dry_run_ok=True,
            sumario={"visitas": 3},
        )
        import_history.registrar_importacao(
            get_db,
            "job-postgresql-temporario",
            ["TB_corrigido.xlsx"],
            status="upload",
            usuario="Nao substituir",
        )
        import_history.atualizar_importacao(
            get_db,
            "job-postgresql-temporario",
            "confirmado",
            commit_ok=True,
        )
        recent = import_history.listar_importacoes_recentes(get_db, limite=5)
        if len(recent) != 1:
            raise RuntimeError("A listagem das importacoes divergiu.")
        item = recent[0]
        if item["usuario"] != "Teste inicial":
            raise RuntimeError("O usuario original nao foi preservado.")
        if item["criado_em"] != first:
            raise RuntimeError("A data de criacao original nao foi preservada.")
        if item["arquivos"] != ["TB_corrigido.xlsx"]:
            raise RuntimeError("A lista de arquivos nao foi atualizada.")
        if item["status"] != "confirmado" or item["commit_ok"] != 1:
            raise RuntimeError("A confirmacao da importacao divergiu.")

        conn.close = real_close
        public_after = conn.execute(
            "SELECT COUNT(*) FROM public.importacoes"
        ).fetchone()[0]
        conn.rollback()
        if public_before != public_after:
            raise RuntimeError("A tabela publica de importacoes foi alterada.")
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if conn is not None:
            if real_close is not None:
                conn.close = real_close
            conn.close()

    print("Teste do Historico de Importacoes no PostgreSQL")
    print("=" * 50)
    print(f"Banco: {args.database}")
    print("Registro e reprocessamento: OK")
    print("Usuario e data original: preservados")
    print("Arquivos, status e resumo: OK")
    print("Ordenacao por data ISO: OK")
    print("Tabela publica de importacoes: preservada")
    print("\n[OK] Modulo validado somente em tabela temporaria.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
