"""Ensaio isolado da sincronizacao Conta Ovos no PostgreSQL de teste."""

import argparse
import sys
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import contaovos_sync  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import postgresql  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description="Testa a sincronizacao em tabelas temporarias PostgreSQL."
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    return parser


def _public_counts(conn):
    result = {}
    for table in (
        "ovitrampas_ocorrencias_conta_ovos",
        "contaovos_sync_cursor",
        "contaovos_execucoes",
    ):
        with conn.cursor() as cursor:
            cursor.execute(f'SELECT COUNT(*) FROM public."{table}"')
            result[table] = cursor.fetchone()[0]
    return result


def _create_temp_schema(conn):
    with conn.cursor() as cursor:
        cursor.execute("SET search_path TO pg_temp, public")
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_sync_cursor (
                fluxo text PRIMARY KEY,
                ultimo_id_remoto text,
                atualizado_em text NOT NULL,
                em_execucao_desde text,
                execucao_token text
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_execucoes (
                id_execucao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tipo text NOT NULL,
                iniciado_em text NOT NULL,
                finalizado_em text,
                status text NOT NULL,
                itens_ok bigint NOT NULL DEFAULT 0,
                itens_erro bigint NOT NULL DEFAULT 0,
                resumo_sanitizado text
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_ocorrencias_conta_ovos (
                id_contagem text PRIMARY KEY,
                ovitrampa_id text NOT NULL,
                ano bigint NOT NULL,
                semana bigint NOT NULL,
                data date,
                data_envio_contagem text,
                ovos bigint DEFAULT 0,
                resultado text,
                codigo_conta_ovos bigint,
                observacao_conta_ovos text,
                ocorrencia_codigo bigint,
                latitude double precision,
                longitude double precision,
                lat_lng text,
                arquivo_origem text,
                importado_em text NOT NULL
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_armadilhas (
                ovitrampa_id text PRIMARY KEY
            )"""
        )
        cursor.execute(
            "INSERT INTO ovitrampas_armadilhas (ovitrampa_id) VALUES ('97')"
        )
    conn.commit()


def _fetcher(key, **params):
    if params["page"] > 1:
        return []
    return [
        {
            "municipality": "Almirante Tamandare",
            "municipality_code": "4100400",
            "state_code": "PR",
            "counting_id": 990001,
            "ovitrap_id": "00097",
            "year": 2026,
            "week": 31,
            "eggs": 7,
            "date_collect": "2026-08-03",
            "counting_observation_id": 6,
        }
    ]


def main(argv=None):
    args = _parser().parse_args(argv)
    if args.database != SAFE_DATABASE:
        print(f"[ERRO] Este ensaio aceita somente o banco {SAFE_DATABASE}.")
        return 2
    raw_conn = None
    try:
        raw_conn = postgresql.connect(database=args.database)
        before = _public_counts(raw_conn)
        _create_temp_schema(raw_conn)
        conn = db_core.PostgreSQLConnection(raw_conn)
        first = contaovos_sync.synchronize_countings(
            connection=conn,
            key="chave-falsa-sem-rede",
            page_fetcher=_fetcher,
            now=datetime(2026, 8, 3, 16, 0, 0),
        )
        second = contaovos_sync.synchronize_countings(
            connection=conn,
            key="chave-falsa-sem-rede",
            page_fetcher=_fetcher,
            now=datetime(2026, 8, 3, 16, 5, 0),
        )
        row = conn.execute(
            "SELECT ovitrampa_id, ovos FROM ovitrampas_ocorrencias_conta_ovos"
        ).fetchone()
        after = _public_counts(raw_conn)
        if before != after:
            raise RuntimeError("O ensaio alterou tabelas publicas.")
        if first["inseridos"] != 1 or second["sem_alteracao"] != 1:
            raise RuntimeError("A idempotencia da sincronizacao divergiu.")
        if row[0] != "97" or row[1] != 7:
            raise RuntimeError("A normalizacao PostgreSQL divergiu.")
        print("[OK] Sincronizacao Conta Ovos validada em tabelas temporarias.")
        print("[OK] Tabelas publicas permaneceram inalteradas.")
        return 0
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if raw_conn is not None:
            raw_conn.rollback()
            raw_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
