"""Valida escritas de autenticacao e auditoria sem tocar nas tabelas publicas."""

import argparse
import sys
from datetime import date
from pathlib import Path

from flask import Flask, session


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import audit  # noqa: E402
from app_core import auth  # noqa: E402
from app_core import db as db_core  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description=(
            "Testa autenticacao e auditoria em tabelas PostgreSQL temporarias."
        )
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    parser.add_argument(
        "--confirmar-banco",
        help="Obrigatorio para qualquer banco diferente de endemias_teste.",
    )
    return parser


def _public_counts(conn):
    return {
        "login_tentativas": conn.execute(
            "SELECT COUNT(*) FROM public.login_tentativas"
        ).fetchone()[0],
        "auditoria_eventos": conn.execute(
            "SELECT COUNT(*) FROM public.auditoria_eventos"
        ).fetchone()[0],
    }


def _create_temporary_tables(conn):
    conn.execute(
        """
        CREATE TEMPORARY TABLE login_tentativas (
            chave text PRIMARY KEY,
            tentativas bigint NOT NULL DEFAULT 0,
            primeira_em double precision NOT NULL,
            atualizado_em text NOT NULL
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE TEMPORARY TABLE auditoria_eventos (
            id_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            acao text NOT NULL,
            entidade text,
            entidade_id text,
            usuario_id bigint,
            usuario_nome text,
            ip text,
            detalhes_json text NOT NULL DEFAULT '{}',
            criado_em text NOT NULL
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.commit()


def main(argv=None):
    args = _parser().parse_args(argv)
    if (
        args.database != SAFE_DATABASE
        and args.confirmar_banco != args.database
    ):
        print(
            "[ERRO] Para testar outro banco, informe "
            f"--confirmar-banco {args.database}"
        )
        return 2

    target = db_core.DatabaseTarget("postgresql", args.database)
    conn = None
    real_close = None
    try:
        conn = db_core.connect(target)
        before = _public_counts(conn)
        conn.rollback()
        _create_temporary_tables(conn)

        real_close = conn.close
        conn.close = lambda: None
        get_db = lambda: conn

        key = "127.0.0.1:teste_postgresql"
        auth.registrar_login_falha_db(get_db, key, agora=100.0)
        auth.registrar_login_falha_db(get_db, key, agora=101.0)
        attempt = conn.execute(
            "SELECT tentativas FROM login_tentativas WHERE chave=?",
            (key,),
        ).fetchone()
        if not attempt or attempt["tentativas"] != 2:
            raise RuntimeError("A contagem de tentativas nao foi persistida.")

        flask_app = Flask(__name__)
        flask_app.secret_key = "teste-temporario-nao-operacional"
        with flask_app.test_request_context(
            "/",
            environ_base={"REMOTE_ADDR": "127.0.0.1"},
        ):
            session["uid"] = 1
            session["nome"] = "Teste PostgreSQL"
            audit.registrar_evento(
                get_db,
                "teste_postgresql_temporario",
                entidade="diagnostico",
                entidade_id="temporario",
                detalhes={"persistencia": "temporaria"},
            )
            events = audit.listar_eventos(
                get_db,
                {
                    "acao": "teste_postgresql",
                    "d_ini": date.today().isoformat(),
                    "d_fim": date.today().isoformat(),
                },
                limite=5,
            )
        if len(events) != 1:
            raise RuntimeError("O evento temporario nao foi localizado.")
        if events[0]["detalhes"].get("persistencia") != "temporaria":
            raise RuntimeError("Os detalhes da auditoria divergiram.")

        auth.limpar_login_falhas_db(get_db, key)
        if conn.execute(
            "SELECT COUNT(*) FROM login_tentativas WHERE chave=?",
            (key,),
        ).fetchone()[0]:
            raise RuntimeError("A limpeza das tentativas falhou.")

        conn.close = real_close
        after = _public_counts(conn)
        conn.rollback()
        if before != after:
            raise RuntimeError(
                "As contagens das tabelas publicas foram alteradas."
            )
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if conn is not None:
            if real_close is not None:
                conn.close = real_close
            conn.close()

    print("Teste de autenticacao e auditoria no PostgreSQL")
    print("=" * 48)
    print(f"Banco: {args.database}")
    print("Tentativas de login: gravacao, leitura e limpeza OK")
    print("Auditoria: gravacao, filtro e JSON OK")
    print("Tabelas publicas: contagens preservadas")
    print("\n[OK] Escritas validadas apenas em tabelas temporarias.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
