"""Ensaio da central Conta Ovos usando somente tabelas temporarias."""

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import contaovos_consultas  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import postgresql  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description="Testa a central Conta Ovos em tabelas temporarias PostgreSQL."
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    return parser


def _public_counts(conn):
    tables = (
        "ovitrampas_armadilhas",
        "ovitrampas_ocorrencias_conta_ovos",
        "contaovos_execucoes",
    )
    result = {}
    with conn.cursor() as cursor:
        for table in tables:
            cursor.execute(f'SELECT COUNT(*) FROM public."{table}"')
            result[table] = cursor.fetchone()[0]
    return result


def _create_temp_schema(conn):
    with conn.cursor() as cursor:
        cursor.execute("SET search_path TO pg_temp, public")
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_armadilhas (
                ovitrampa_id text PRIMARY KEY, rua text, numero text, complemento text,
                bairro text, localizacao text, localidade text, responsavel text,
                telefone_responsavel text, quarteirao text, latitude double precision,
                longitude double precision, ativo bigint NOT NULL DEFAULT 1,
                arquivo_origem text, atualizado_em text NOT NULL
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_ocorrencias_conta_ovos (
                id_contagem text PRIMARY KEY, ovitrampa_id text NOT NULL,
                ano bigint NOT NULL, semana bigint NOT NULL, data date,
                data_envio_contagem text, ovos bigint DEFAULT 0, resultado text,
                codigo_conta_ovos bigint, observacao_conta_ovos text,
                ocorrencia_codigo bigint, latitude double precision,
                longitude double precision, lat_lng text, arquivo_origem text,
                importado_em text NOT NULL
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_execucoes (
                id_execucao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tipo text NOT NULL, iniciado_em text NOT NULL, finalizado_em text,
                status text NOT NULL, itens_ok bigint NOT NULL DEFAULT 0,
                itens_erro bigint NOT NULL DEFAULT 0, resumo_sanitizado text
            )"""
        )
        cursor.execute(
            """INSERT INTO ovitrampas_armadilhas
               (ovitrampa_id,rua,numero,localidade,responsavel,quarteirao,ativo,atualizado_em)
               VALUES ('00097','Rua A','10','Sede','Maria','0042',1,'2026-08-04T10:00:00')"""
        )
        cursor.execute(
            """INSERT INTO ovitrampas_ocorrencias_conta_ovos
               (id_contagem,ovitrampa_id,ano,semana,data,ovos,resultado,importado_em)
               VALUES ('101','00097',2026,31,'2026-08-03',12,'Positiva','2026-08-04T10:00:00')"""
        )
        cursor.execute(
            """INSERT INTO contaovos_execucoes
               (tipo,iniciado_em,finalizado_em,status,itens_ok,resumo_sanitizado)
               VALUES ('sincronizacao','2026-08-04T10:00:00','2026-08-04T10:01:00','concluido',1,'sem dados sensiveis')"""
        )
    conn.commit()


def main(argv=None):
    args = _parser().parse_args(argv)
    if args.database != SAFE_DATABASE:
        print(f"[ERRO] Este ensaio aceita somente o banco {SAFE_DATABASE}.")
        return 2
    raw_conn = None
    try:
        raw_conn = postgresql.connect(database=args.database)
        before = _public_counts(raw_conn)
        _create_temp_schema(raw_conn)
        target = db_core.PostgreSQLConnection(raw_conn)
        resumo = contaovos_consultas.resumo(target)
        contagens = contaovos_consultas.listar_contagens(target, {"busca": "sede"})
        cadastro = contaovos_consultas.listar_ovitrampas(target, {"ativo": "1"})
        detalhe = contaovos_consultas.detalhes_ovitrampa(target, "00097")
        after = _public_counts(raw_conn)
        if before != after:
            raise RuntimeError("O ensaio alterou tabelas publicas.")
        if resumo["totais"]["contagens"] != 1 or resumo["totais"]["ovos"] != 12:
            raise RuntimeError("Resumo PostgreSQL divergiu.")
        if contagens["total"] != 1 or contagens["registros"][0]["localidade"] != "Sede":
            raise RuntimeError("Filtro de contagens PostgreSQL divergiu.")
        if cadastro["total"] != 1 or cadastro["registros"][0]["contagens"] != 1:
            raise RuntimeError("Cadastro PostgreSQL divergiu.")
        if not detalhe["armadilha"] or len(detalhe["contagens"]) != 1:
            raise RuntimeError("Detalhe PostgreSQL divergiu.")
        print("[OK] Central Conta Ovos validada em tabelas temporarias PostgreSQL.")
        print("[OK] Tabelas publicas permaneceram inalteradas.")
        return 0
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if raw_conn is not None:
            raw_conn.rollback()
            raw_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
