"""Valida Controle de Pessoal no PostgreSQL sem alterar dados publicos."""

import argparse
import logging
import os
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import agentes  # noqa: E402
from app_core import db as db_core  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description=(
            "Testa servidores em tabela temporaria e renderiza a pagina."
        )
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    parser.add_argument(
        "--confirmar-banco",
        help="Obrigatorio para qualquer banco diferente de endemias_teste.",
    )
    return parser


def _temporary_agents(conn):
    conn.execute(
        """
        CREATE TEMPORARY TABLE agentes (
            id_agente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome text NOT NULL UNIQUE,
            matricula text,
            cargo text,
            ativo bigint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),
            data_inicio text,
            data_saida text,
            observacoes text,
            nome_completo text,
            cpf text,
            data_nascimento text
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE UNIQUE INDEX agentes_cpf_temporario
            ON agentes(cpf)
         WHERE cpf IS NOT NULL AND cpf<>''
        """
    )
    conn.commit()


def _test_crud(target):
    conn = db_core.connect(target)
    try:
        public_before = conn.execute(
            "SELECT COUNT(*) FROM public.agentes"
        ).fetchone()[0]
        conn.rollback()
        _temporary_agents(conn)

        server_id = agentes.criar(
            conn,
            {
                "nome": "Teste Kobo PostgreSQL",
                "nome_completo": "Servidor Temporario PostgreSQL",
                "matricula": "TEMP-001",
                "cpf": "123.456.789-09",
                "data_nascimento": "1990-07-16",
                "cargo": "Teste",
                "ativo": "1",
            },
        )
        created = agentes.obter(conn, server_id)
        if created["nome_completo"] != "Servidor Temporario PostgreSQL":
            raise RuntimeError("O servidor criado nao foi recuperado.")

        found = agentes.listar(
            conn,
            {"status": "ativos", "busca": "servidor temporario"},
        )
        if [item["id_agente"] for item in found] != [server_id]:
            raise RuntimeError("A busca sem diferenca de caixa falhou.")

        previous, new_value = agentes.atualizar_campo(
            conn,
            server_id,
            "cargo",
            "Laboratorio",
        )
        if previous["cargo"] != "Teste" or new_value != "Laboratorio":
            raise RuntimeError("A edicao do servidor divergiu.")

        same_id = agentes.obter_ou_criar(conn, "Teste Kobo PostgreSQL")
        other_id = agentes.obter_ou_criar(conn, "Novo Servidor Temporario")
        if same_id != server_id or other_id == server_id:
            raise RuntimeError("A normalizacao obter/ou criar falhou.")
        other = agentes.obter(conn, other_id)
        if other["nome_completo"] != "Novo Servidor Temporario":
            raise RuntimeError("O nome completo automatico nao foi salvo.")

        public_after = conn.execute(
            "SELECT COUNT(*) FROM public.agentes"
        ).fetchone()[0]
        conn.rollback()
        if public_before != public_after:
            raise RuntimeError("A tabela publica de servidores foi alterada.")
        return len(found)
    finally:
        conn.close()


def _test_history(target):
    row = db_core.query_one(
        target,
        """
        SELECT id_agente
          FROM visita_agentes
         ORDER BY id_agente
         LIMIT ?
        """,
        (1,),
    )
    if not row:
        return 0, 0
    history = agentes.historico(
        target,
        row["id_agente"],
        "2025-01-01",
        "2026-12-31",
    )
    if history is None:
        raise RuntimeError("O historico do servidor nao foi encontrado.")
    return history["total"], len(history["por_origem"])


def _test_page(database, target):
    admin = db_core.query_one(
        target,
        """
        SELECT id_usuario, nome, nivel
          FROM usuarios
         WHERE ativo=1 AND nivel='admin'
         ORDER BY id_usuario
         LIMIT ?
        """,
        (1,),
    )
    if not admin:
        raise RuntimeError("Nao existe usuario administrador para o teste.")

    with tempfile.TemporaryDirectory(prefix="endemias-pg-servidores-") as tmpdir:
        from app import create_app

        log_path = str(Path(tmpdir) / "teste.log")
        try:
            flask_app = create_app(
                {
                    "DB_BACKEND": "postgresql",
                    "PG_DATABASE": database,
                    "TESTING": True,
                    "WTF_CSRF_ENABLED": False,
                    "LOG_PATH": log_path,
                    "SECRET_KEY_PATH": str(Path(tmpdir) / "secret.key"),
                }
            )
            client = flask_app.test_client()
            with client.session_transaction() as flask_session:
                flask_session["uid"] = admin["id_usuario"]
                flask_session["nome"] = admin["nome"]
                flask_session["nivel"] = admin["nivel"]
            response = client.get("/admin/agentes")
            if response.status_code != 200:
                raise RuntimeError(
                    "Controle de Pessoal respondeu "
                    f"HTTP {response.status_code}."
                )
            if b"Controle de Pessoal" not in response.data:
                raise RuntimeError(
                    "O conteudo esperado da pagina nao foi renderizado."
                )
        finally:
            for handler in list(logging.getLogger().handlers):
                if (
                    getattr(handler, "baseFilename", None)
                    == os.path.abspath(log_path)
                ):
                    logging.getLogger().removeHandler(handler)
                    handler.close()


def main(argv=None):
    args = _parser().parse_args(argv)
    if (
        args.database != SAFE_DATABASE
        and args.confirmar_banco != args.database
    ):
        print(
            "[ERRO] Para testar outro banco, informe "
            f"--confirmar-banco {args.database}"
        )
        return 2

    target = db_core.DatabaseTarget("postgresql", args.database)
    try:
        found = _test_crud(target)
        events, sources = _test_history(target)
        _test_page(args.database, target)
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1

    print("Teste do Controle de Pessoal no PostgreSQL")
    print("=" * 47)
    print(f"Banco: {args.database}")
    print("CRUD temporario: OK")
    print(f"Busca sem diferenca de caixa: {found} resultado")
    print(f"Historico real somente leitura: {events} eventos")
    print(f"Origens do historico: {sources}")
    print("Pagina Controle de Pessoal: HTTP 200")
    print("Tabela publica de servidores: preservada")
    print("\n[OK] Modulo validado sem alterar os dados publicos.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
