"""Ensaio do envio Conta Ovos com PostgreSQL temporario e transporte falso."""

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import contaovos_envio  # noqa: E402
from app_core import contaovos_fila  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import postgresql  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _create_temp_schema(raw_conn):
    with raw_conn.cursor() as cursor:
        cursor.execute("SET search_path TO pg_temp, public")
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_laboratorio_lotes (
                id_lote bigint PRIMARY KEY,
                data_movimento date NOT NULL,
                status text NOT NULL
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_laboratorio_itens (
                id_item bigint PRIMARY KEY,
                id_lote bigint NOT NULL,
                ovitrampa_id text NOT NULL,
                ovos bigint NOT NULL,
                ocorrencia bigint
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_armadilhas (
                ovitrampa_id text PRIMARY KEY,
                latitude double precision,
                longitude double precision
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_ocorrencias_conta_ovos (
                id_contagem text PRIMARY KEY,
                ovitrampa_id text NOT NULL,
                data date,
                ano bigint,
                semana bigint,
                ovos bigint,
                ocorrencia_codigo bigint
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_fila_contagens (
                id_fila bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_item bigint NOT NULL UNIQUE,
                status text NOT NULL,
                tentativas bigint NOT NULL DEFAULT 0,
                id_remoto text,
                erro_sanitizado text,
                payload_hash text NOT NULL,
                criado_em text NOT NULL,
                atualizado_em text NOT NULL,
                ultima_tentativa_em text,
                confirmado_em text
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE auditoria_eventos (
                id_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                acao text NOT NULL,
                entidade text,
                entidade_id text,
                usuario_id bigint,
                usuario_nome text,
                ip text,
                detalhes_json text NOT NULL DEFAULT '{}',
                criado_em text NOT NULL
            )"""
        )
        cursor.execute(
            "INSERT INTO ovitrampas_laboratorio_lotes "
            "VALUES (1, DATE '2026-08-02', 'concluido')"
        )
        cursor.execute(
            "INSERT INTO ovitrampas_laboratorio_itens VALUES (11,1,'97',7,5)"
        )
        cursor.execute(
            "INSERT INTO ovitrampas_armadilhas VALUES ('97',-25.1,-49.2)"
        )
    raw_conn.commit()


def _remote():
    return {
        "counting_id": "995001",
        "ovitrap_id": "97",
        "municipality_code": "4100400",
        "state_code": "PR",
        "date": "2026-08-02",
        "year": 2026,
        "week": 31,
        "eggs": 7,
        "counting_observation_id": 6,
        "latitude": -25.1,
        "longitude": -49.2,
    }


def main(argv=None):
    argv = list(argv or sys.argv[1:])
    database = SAFE_DATABASE
    if argv:
        if len(argv) != 2 or argv[0] != "--database":
            print(f"[ERRO] Uso: --database {SAFE_DATABASE}")
            return 2
        database = argv[1]
    if database != SAFE_DATABASE:
        print(f"[ERRO] Este ensaio aceita somente o banco {SAFE_DATABASE}.")
        return 2

    raw_conn = None
    try:
        raw_conn = postgresql.connect(database=database)
        with raw_conn.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM public.contaovos_fila_contagens")
            queue_before = cursor.fetchone()[0]
            cursor.execute("SELECT COUNT(*) FROM public.auditoria_eventos")
            audit_before = cursor.fetchone()[0]
        _create_temp_schema(raw_conn)
        conn = db_core.PostgreSQLConnection(raw_conn)
        contaovos_fila.prepare_and_reconcile(conn, 1)
        conn.commit()
        queue_id = conn.execute(
            "SELECT id_fila FROM contaovos_fila_contagens"
        ).fetchone()[0]
        rounds = {"value": 0}

        def fetcher(key, **params):
            if params["page"] == 1:
                rounds["value"] += 1
                return [] if rounds["value"] == 1 else [_remote()]
            return []

        observed = {}

        def poster(key, payload, **kwargs):
            observed["status"] = conn.execute(
                "SELECT status FROM contaovos_fila_contagens WHERE id_fila=?",
                (queue_id,),
            ).fetchone()[0]
            return {"accepted": True, "status_code": 200}

        def ovitrap_fetcher(**params):
            if params["page"] > 1:
                return []
            return [
                {
                    "ovitrap_group_id": "97",
                    "ovitrap_lat": -25.1,
                    "ovitrap_lng": -49.2,
                    "municipality_code": "4100400",
                    "state_code": "PR",
                }
            ]

        result = contaovos_envio.send_one(
            connection=conn,
            queue_id=queue_id,
            operator_name="Ensaio PostgreSQL",
            key="chave-falsa",
            allow_remote_write=True,
            page_fetcher=fetcher,
            ovitrap_fetcher=ovitrap_fetcher,
            poster=poster,
        )
        status = conn.execute(
            "SELECT status, id_remoto, tentativas FROM contaovos_fila_contagens"
        ).fetchone()
        audit_count = conn.execute(
            "SELECT COUNT(*) FROM auditoria_eventos"
        ).fetchone()[0]
        with raw_conn.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM public.contaovos_fila_contagens")
            queue_after = cursor.fetchone()[0]
            cursor.execute("SELECT COUNT(*) FROM public.auditoria_eventos")
            audit_after = cursor.fetchone()[0]
        if queue_before != queue_after or audit_before != audit_after:
            raise RuntimeError("O ensaio alterou tabelas publicas.")
        if observed.get("status") != "enviando":
            raise RuntimeError("O estado enviando nao foi commitado antes do POST falso.")
        if not result["sent"] or tuple(status) != ("confirmado", "995001", 1):
            raise RuntimeError("A confirmacao PostgreSQL divergiu.")
        if audit_count != 2:
            raise RuntimeError("A auditoria transacional do envio divergiu.")
        print("[OK] Envio Conta Ovos validado com transporte falso no PostgreSQL.")
        print("[OK] Tabelas publicas permaneceram inalteradas.")
        return 0
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if raw_conn is not None:
            raw_conn.rollback()
            raw_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
