"""Valida Gestao de Usuarios no PostgreSQL sem alterar dados publicos."""

import argparse
import logging
import os
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import auth  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import usuarios  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description="Testa usuarios em tabela PostgreSQL temporaria."
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    parser.add_argument(
        "--confirmar-banco",
        help="Obrigatorio para qualquer banco diferente de endemias_teste.",
    )
    return parser


def _temporary_users(conn):
    conn.execute(
        """
        CREATE TEMPORARY TABLE usuarios (
            id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario text NOT NULL UNIQUE,
            nome text NOT NULL,
            senha_hash text NOT NULL,
            nivel text NOT NULL DEFAULT 'visualizador'
                CHECK(nivel IN ('admin','operador','visualizador')),
            ativo bigint NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),
            criado_em text NOT NULL,
            acesso_laboratorio bigint NOT NULL DEFAULT 0
                CHECK(acesso_laboratorio IN (0,1)),
            somente_laboratorio bigint NOT NULL DEFAULT 0
                CHECK(somente_laboratorio IN (0,1))
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.commit()


def _test_crud(target):
    conn = db_core.connect(target)
    try:
        public_before = conn.execute(
            "SELECT COUNT(*) FROM public.usuarios"
        ).fetchone()[0]
        conn.rollback()
        _temporary_users(conn)

        uid = usuarios.criar(
            conn,
            {
                "usuario": " USUARIO.TEMPORARIO ",
                "nome": "Usuario Temporario",
                "senha": "SenhaTemporaria123",
                "nivel": "visualizador",
                "somente_laboratorio": "1",
            },
            agora="2026-07-29T12:00:00",
        )
        listed = usuarios.listar(conn)
        if len(listed) != 1 or listed[0]["id_usuario"] != uid:
            raise RuntimeError("A listagem do usuario temporario divergiu.")
        if (
            listed[0]["acesso_laboratorio"] != 1
            or listed[0]["somente_laboratorio"] != 1
        ):
            raise RuntimeError("As permissoes de laboratorio divergiram.")

        previous, new_level = usuarios.editar(
            conn,
            uid,
            "nivel",
            "operador",
        )
        if previous["nivel"] != "visualizador" or new_level != "operador":
            raise RuntimeError("A edicao do nivel divergiu.")

        try:
            usuarios.editar(
                conn,
                uid,
                "ativo",
                "0",
                usuario_atual_id=uid,
            )
        except ValueError:
            pass
        else:
            raise RuntimeError("A propria conta foi desativada pelo teste.")

        target_user = usuarios.resetar_senha(
            conn,
            uid,
            "SenhaRedefinida456",
        )
        row = conn.execute(
            "SELECT senha_hash FROM usuarios WHERE id_usuario=?",
            (uid,),
        ).fetchone()
        if target_user["usuario"] != "usuario.temporario":
            raise RuntimeError("O login nao foi normalizado.")
        if not auth.verificar_senha("SenhaRedefinida456", row[0])[0]:
            raise RuntimeError("A senha redefinida nao foi protegida.")

        public_after = conn.execute(
            "SELECT COUNT(*) FROM public.usuarios"
        ).fetchone()[0]
        conn.rollback()
        if public_before != public_after:
            raise RuntimeError("A tabela publica de usuarios foi alterada.")
        return uid
    finally:
        conn.close()


def _test_page(database, target):
    admin = db_core.query_one(
        target,
        """
        SELECT id_usuario, nome, nivel
          FROM usuarios
         WHERE ativo=1 AND nivel='admin'
         ORDER BY id_usuario
         LIMIT ?
        """,
        (1,),
    )
    if not admin:
        raise RuntimeError("Nao existe administrador para o teste da pagina.")

    with tempfile.TemporaryDirectory(prefix="endemias-pg-usuarios-") as tmpdir:
        from app import create_app

        log_path = str(Path(tmpdir) / "teste.log")
        try:
            flask_app = create_app(
                {
                    "DB_BACKEND": "postgresql",
                    "PG_DATABASE": database,
                    "TESTING": True,
                    "WTF_CSRF_ENABLED": False,
                    "LOG_PATH": log_path,
                    "SECRET_KEY_PATH": str(Path(tmpdir) / "secret.key"),
                }
            )
            client = flask_app.test_client()
            with client.session_transaction() as flask_session:
                flask_session["uid"] = admin["id_usuario"]
                flask_session["nome"] = admin["nome"]
                flask_session["nivel"] = admin["nivel"]
            response = client.get("/admin/usuarios")
            if response.status_code != 200:
                raise RuntimeError(
                    f"Gestao de Usuarios respondeu HTTP {response.status_code}."
                )
            if b"admin/usuarios/criar" not in response.data:
                raise RuntimeError("O formulario de usuarios nao foi exibido.")
        finally:
            for handler in list(logging.getLogger().handlers):
                if (
                    getattr(handler, "baseFilename", None)
                    == os.path.abspath(log_path)
                ):
                    logging.getLogger().removeHandler(handler)
                    handler.close()


def main(argv=None):
    args = _parser().parse_args(argv)
    if (
        args.database != SAFE_DATABASE
        and args.confirmar_banco != args.database
    ):
        print(
            "[ERRO] Para testar outro banco, informe "
            f"--confirmar-banco {args.database}"
        )
        return 2

    target = db_core.DatabaseTarget("postgresql", args.database)
    try:
        uid = _test_crud(target)
        _test_page(args.database, target)
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1

    print("Teste da Gestao de Usuarios no PostgreSQL")
    print("=" * 45)
    print(f"Banco: {args.database}")
    print(f"Identidade temporaria: {uid}")
    print("Cadastro e listagem: OK")
    print("Nivel e permissoes: OK")
    print("Protecao da propria conta: OK")
    print("Reset e verificacao da senha: OK")
    print("Pagina Gestao de Usuarios: HTTP 200")
    print("Tabela publica de usuarios: preservada")
    print("\n[OK] Modulo validado sem alterar os dados publicos.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
