"""Ensaio isolado do espelho de cadastro de ovitrampas em PostgreSQL."""

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import contaovos_registro  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import postgresql  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _public_counts(conn):
    result = {}
    for table in ("contaovos_registro_ovitrampas", "contaovos_execucoes"):
        with conn.cursor() as cursor:
            cursor.execute(f'SELECT COUNT(*) FROM public."{table}"')
            result[table] = cursor.fetchone()[0]
    return result


def _create_temp_schema(conn):
    with conn.cursor() as cursor:
        cursor.execute("SET search_path TO pg_temp, public")
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_registro_ovitrampas (
                ovitrampa_id_remoto text PRIMARY KEY,
                ovitrap_id text,
                latitude double precision,
                longitude double precision,
                coordenada_erro bigint,
                municipio text,
                municipio_codigo text,
                estado text,
                ovos_media double precision,
                quarteirao_remoto_id text,
                grupo_remoto_id text,
                usuario_remoto_id text,
                atualizado_remoto_em text,
                sincronizado_em text NOT NULL
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_execucoes (
                id_execucao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tipo text NOT NULL,
                iniciado_em text NOT NULL,
                finalizado_em text,
                status text NOT NULL,
                itens_ok bigint NOT NULL DEFAULT 0,
                itens_erro bigint NOT NULL DEFAULT 0,
                resumo_sanitizado text
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_sync_cursor (
                fluxo text PRIMARY KEY,
                ultimo_id_remoto text,
                atualizado_em text NOT NULL,
                em_execucao_desde text,
                execucao_token text
            )"""
        )
    conn.commit()


def _fetcher(**params):
    if params["page"] > 1:
        return []
    return [
        {
            "ovitrap_id": 4471,
            "ovitrap_group_id": "97",
            "ovitrap_datetime": "2026-08-02 14:32:10",
            "ovitrap_lat": -25.31,
            "ovitrap_lng": -49.29,
            "ovitrap_lat_lng_error": 0,
            "ovitrap_municipality_id": 4100400,
            "group_id": 12,
            "user_id": 348,
            "ovitrap_eggs_mean": 7.5,
            "ovitrap_block_id": 4521,
            "municipality": "Almirante Tamandaré",
            "municipality_code": "4100400",
            "state_name": "Paraná",
            "state_code": "PR",
        }
    ]


def main(argv=None):
    args = list(argv or sys.argv[1:])
    database = SAFE_DATABASE
    if args:
        if len(args) != 2 or args[0] != "--database":
            print(f"[ERRO] Uso: --database {SAFE_DATABASE}")
            return 2
        database = args[1]
    if database != SAFE_DATABASE:
        print(f"[ERRO] Este ensaio aceita somente o banco {SAFE_DATABASE}.")
        return 2
    raw_conn = None
    try:
        raw_conn = postgresql.connect(database=database)
        before = _public_counts(raw_conn)
        _create_temp_schema(raw_conn)
        conn = db_core.PostgreSQLConnection(raw_conn)
        first = contaovos_registro.synchronize(connection=conn, page_fetcher=_fetcher)
        raw_conn.commit()
        second = contaovos_registro.synchronize(connection=conn, page_fetcher=_fetcher)
        raw_conn.commit()
        row = conn.execute(
            "SELECT ovitrampa_id_remoto, latitude, longitude "
            "FROM contaovos_registro_ovitrampas"
        ).fetchone()
        after = _public_counts(raw_conn)
        if before != after:
            raise RuntimeError("O ensaio alterou tabelas publicas.")
        if first["inseridos"] != 1 or second["sem_alteracao"] != 1:
            raise RuntimeError("A idempotencia do registro divergiu.")
        if row[0] != "97":
            raise RuntimeError("A gravacao do registro divergiu.")
        print("[OK] Espelho de cadastro Conta Ovos validado em tabelas temporarias.")
        print("[OK] Tabelas publicas permaneceram inalteradas.")
        return 0
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if raw_conn is not None:
            raw_conn.rollback()
            raw_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
