"""Ensaio isolado da fila Conta Ovos em tabelas temporarias PostgreSQL."""

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import contaovos_fila  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import postgresql  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _create_temp_schema(raw_conn):
    with raw_conn.cursor() as cursor:
        cursor.execute("SET search_path TO pg_temp, public")
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_laboratorio_lotes (
                id_lote bigint PRIMARY KEY,
                data_movimento date NOT NULL,
                status text NOT NULL
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_laboratorio_itens (
                id_item bigint PRIMARY KEY,
                id_lote bigint NOT NULL,
                ovitrampa_id text NOT NULL,
                ovos bigint NOT NULL,
                ocorrencia bigint
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_armadilhas (
                ovitrampa_id text PRIMARY KEY,
                latitude double precision,
                longitude double precision
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE ovitrampas_ocorrencias_conta_ovos (
                id_contagem text PRIMARY KEY,
                ovitrampa_id text NOT NULL,
                data date,
                ano bigint,
                semana bigint,
                ovos bigint,
                ocorrencia_codigo bigint
            )"""
        )
        cursor.execute(
            """CREATE TEMPORARY TABLE contaovos_fila_contagens (
                id_fila bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                id_item bigint NOT NULL UNIQUE,
                status text NOT NULL,
                tentativas bigint NOT NULL DEFAULT 0,
                id_remoto text,
                erro_sanitizado text,
                payload_hash text NOT NULL,
                criado_em text NOT NULL,
                atualizado_em text NOT NULL,
                ultima_tentativa_em text,
                confirmado_em text
            )"""
        )
        cursor.execute(
            "INSERT INTO ovitrampas_laboratorio_lotes VALUES (1, DATE '2026-08-02', 'concluido')"
        )
        cursor.execute(
            "INSERT INTO ovitrampas_laboratorio_itens VALUES (11,1,'97',7,5)"
        )
        cursor.execute(
            "INSERT INTO ovitrampas_armadilhas VALUES ('97',-25.1,-49.2)"
        )
        cursor.execute(
            "INSERT INTO ovitrampas_ocorrencias_conta_ovos "
            "VALUES ('990001','97',DATE '2026-08-02',2026,31,7,5)"
        )
    raw_conn.commit()


def main(argv=None):
    argv = list(argv or sys.argv[1:])
    database = SAFE_DATABASE
    if argv:
        if len(argv) != 2 or argv[0] != "--database":
            print(f"[ERRO] Uso: --database {SAFE_DATABASE}")
            return 2
        database = argv[1]
    if database != SAFE_DATABASE:
        print(f"[ERRO] Este ensaio aceita somente o banco {SAFE_DATABASE}.")
        return 2
    raw_conn = None
    try:
        raw_conn = postgresql.connect(database=database)
        with raw_conn.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM public.contaovos_fila_contagens")
            before = cursor.fetchone()[0]
        _create_temp_schema(raw_conn)
        conn = db_core.PostgreSQLConnection(raw_conn)
        first = contaovos_fila.prepare_and_reconcile(conn, 1)
        raw_conn.commit()
        second = contaovos_fila.prepare_and_reconcile(conn, 1)
        weeks = contaovos_fila.check_epidemiological_weeks(conn)
        raw_conn.commit()
        with raw_conn.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM public.contaovos_fila_contagens")
            after = cursor.fetchone()[0]
        if before != after:
            raise RuntimeError("O ensaio alterou a fila publica.")
        if first["confirmados"] != 1 or second["confirmados"] != 1:
            raise RuntimeError("A reconciliacao PostgreSQL divergiu.")
        if not weeks["ok"] or weeks["comparados"] != 1:
            raise RuntimeError("A semana epidemiologica PostgreSQL divergiu.")
        print("[OK] Fila Conta Ovos validada em tabelas temporarias.")
        print("[OK] Tabela publica permaneceu inalterada.")
        return 0
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1
    finally:
        if raw_conn is not None:
            raw_conn.rollback()
            raw_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
