"""Valida Recolhimentos e Amostras de Animais no PostgreSQL."""

import argparse
import logging
import os
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app_core import amostras_animais  # noqa: E402
from app_core import db as db_core  # noqa: E402
from app_core import recolhimentos  # noqa: E402


SAFE_DATABASE = "endemias_teste"


def _parser():
    parser = argparse.ArgumentParser(
        description=(
            "Testa Recolhimentos e Amostras de Animais em tabelas temporarias."
        )
    )
    parser.add_argument("--database", default=SAFE_DATABASE)
    parser.add_argument(
        "--confirmar-banco",
        help="Obrigatorio para qualquer banco diferente de endemias_teste.",
    )
    return parser


def _temporary_schema(conn):
    conn.execute(
        """
        CREATE TEMPORARY TABLE localidades (
            id_localidade bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome text NOT NULL UNIQUE,
            cod_localidade text
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE TEMPORARY TABLE agentes (
            id_agente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome text NOT NULL UNIQUE,
            nome_completo text
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE TEMPORARY TABLE recolhimentos (
            id_recolhimento text PRIMARY KEY,
            kobo_uuid text UNIQUE,
            kobo_id bigint,
            data date NOT NULL,
            hora time,
            inicio_registro text,
            fim_registro text,
            localidade text,
            id_localidade bigint,
            agentes_texto text,
            pneu bigint DEFAULT 0,
            louca_sanitaria bigint DEFAULT 0,
            tv bigint DEFAULT 0,
            parachoque bigint DEFAULT 0,
            outros bigint DEFAULT 0,
            total_materiais bigint DEFAULT 0,
            origem_estrutura text NOT NULL DEFAULT 'nova',
            arquivo_origem text,
            submission_time text,
            processado_em text NOT NULL
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE TEMPORARY TABLE recolhimento_agentes (
            id_recolhimento text NOT NULL,
            id_agente bigint NOT NULL,
            PRIMARY KEY (id_recolhimento, id_agente)
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE TEMPORARY TABLE amostras_animais (
            id_amostra text PRIMARY KEY,
            kobo_uuid text UNIQUE,
            kobo_id bigint,
            data date NOT NULL,
            hora time,
            inicio_registro text,
            fim_registro text,
            agentes_texto text,
            motivo_visita text,
            animal_motivador text,
            animal_motivador_outro text,
            localidade text,
            id_localidade bigint,
            quarteirao bigint,
            tipo_imovel text,
            visita text,
            logradouro text,
            numero text,
            sequencia text,
            morador text,
            ocorrencia_residencia text,
            onde text,
            houve_acidente text,
            houve_captura text,
            local_captura text,
            tipo_animal text,
            animal_capturado text,
            especie_serpente text,
            especie_escorpiao text,
            especie_lagarta text,
            especie_aranha text,
            especie_carrapato text,
            especie_resumo text,
            quantidade bigint DEFAULT 0,
            origem_estrutura text NOT NULL DEFAULT 'nova',
            arquivo_origem text,
            submission_time text,
            processado_em text NOT NULL
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.execute(
        """
        CREATE TEMPORARY TABLE amostra_animais_agentes (
            id_amostra text NOT NULL,
            id_agente bigint NOT NULL,
            PRIMARY KEY (id_amostra, id_agente)
        ) ON COMMIT PRESERVE ROWS
        """
    )
    conn.commit()


def _public_counts(conn):
    return {
        table: conn.execute(
            f"SELECT COUNT(*) FROM public.{table}"
        ).fetchone()[0]
        for table in (
            "recolhimentos",
            "recolhimento_agentes",
            "amostras_animais",
            "amostra_animais_agentes",
            "agentes",
            "localidades",
        )
    }


def _test_data(target):
    conn = db_core.connect(target)
    try:
        before = _public_counts(conn)
        conn.rollback()
        _temporary_schema(conn)

        recolhimento = {
            "id_recolhimento": "rec-pg-1",
            "kobo_uuid": "uuid-rec-pg-1",
            "data": "2026-07-29",
            "hora": "08:30",
            "localidade": "Tamboara",
            "agentes_texto": "Ana Beatriz",
            "pneu": 4,
            "total_materiais": 4,
        }
        if not recolhimentos._inserir_recolhimento(
            conn, recolhimento, "2026-07-29T09:00:00"
        ):
            raise RuntimeError("O recolhimento temporario nao foi inserido.")
        if recolhimentos._inserir_recolhimento(
            conn, recolhimento, "2026-07-29T09:00:00"
        ):
            raise RuntimeError("O recolhimento duplicado foi inserido.")
        recolhimentos._inserir_agentes(
            conn, recolhimento["id_recolhimento"], "Ana Beatriz"
        )

        amostra = {
            "id_amostra": "amostra-pg-1",
            "kobo_uuid": "uuid-amostra-pg-1",
            "data": "2026-07-29",
            "hora": "10:45",
            "agentes_texto": "Fernando",
            "motivo_visita": "Investigacao",
            "animal_motivador": "Escorpiao",
            "localidade": "Lamenha",
            "logradouro": "Rua de Teste",
            "houve_acidente": "Sim",
            "houve_captura": "Sim",
            "tipo_animal": "Escorpiao",
            "especie_resumo": "Tityus",
            "quantidade": 2,
        }
        if not amostras_animais._inserir_amostra(
            conn, amostra, "2026-07-29T11:00:00"
        ):
            raise RuntimeError("A amostra temporaria nao foi inserida.")
        if amostras_animais._inserir_amostra(
            conn, amostra, "2026-07-29T11:00:00"
        ):
            raise RuntimeError("A amostra duplicada foi inserida.")
        amostras_animais._inserir_agentes(
            conn, amostra["id_amostra"], "Fernando"
        )
        conn.commit()

        rec_resumo = recolhimentos.resumo(conn)
        rec_lista = recolhimentos.listar(conn, {"busca": "TAMBOARA"})
        amostra_resumo = amostras_animais.resumo(conn)
        amostra_lista = amostras_animais.listar(conn, {"busca": "TITYUS"})

        if rec_resumo["totais"]["total_materiais"] != 4:
            raise RuntimeError("O resumo de recolhimentos divergiu.")
        if rec_lista["total"] != 1:
            raise RuntimeError("A busca de recolhimentos divergiu.")
        if rec_lista["registros"][0]["data"] != "2026-07-29":
            raise RuntimeError("A data do recolhimento nao foi serializada.")
        if amostra_resumo["totais"]["quantidade"] != 2:
            raise RuntimeError("O resumo de amostras divergiu.")
        if amostra_lista["total"] != 1:
            raise RuntimeError("A busca de amostras divergiu.")
        if amostra_lista["registros"][0]["hora"] != "10:45:00":
            raise RuntimeError("A hora da amostra nao foi serializada.")

        after = _public_counts(conn)
        conn.rollback()
        if before != after:
            raise RuntimeError("Uma tabela publica foi alterada.")
        return rec_lista["total"], amostra_lista["total"]
    finally:
        conn.close()


def _test_pages(database, target):
    admin = db_core.query_one(
        target,
        """
        SELECT id_usuario, nome, nivel
          FROM usuarios
         WHERE ativo=1 AND nivel='admin'
         ORDER BY id_usuario
         LIMIT ?
        """,
        (1,),
    )
    if not admin:
        raise RuntimeError("Nao existe administrador para o teste das paginas.")

    with tempfile.TemporaryDirectory(prefix="endemias-pg-campo-") as tmpdir:
        from app import create_app

        log_path = str(Path(tmpdir) / "teste.log")
        try:
            flask_app = create_app(
                {
                    "DB_BACKEND": "postgresql",
                    "PG_DATABASE": database,
                    "TESTING": True,
                    "WTF_CSRF_ENABLED": False,
                    "LOG_PATH": log_path,
                    "SECRET_KEY_PATH": str(Path(tmpdir) / "secret.key"),
                }
            )
            client = flask_app.test_client()
            with client.session_transaction() as flask_session:
                flask_session["uid"] = admin["id_usuario"]
                flask_session["nome"] = admin["nome"]
                flask_session["nivel"] = admin["nivel"]

            checks = {
                "/recolhimentos": b"Recolhimento de Materiais",
                "/api/recolhimentos": b'"totais"',
                "/api/recolhimentos/listar": b'"registros"',
                "/amostras-animais": b"Amostra de Animais",
                "/api/amostras-animais": b'"totais"',
                "/api/amostras-animais/listar": b'"registros"',
            }
            for route, marker in checks.items():
                response = client.get(route)
                if response.status_code != 200:
                    raise RuntimeError(
                        f"{route} respondeu HTTP {response.status_code}."
                    )
                if marker not in response.data:
                    raise RuntimeError(
                        f"{route} nao apresentou o conteudo esperado."
                    )
        finally:
            for handler in list(logging.getLogger().handlers):
                if (
                    getattr(handler, "baseFilename", None)
                    == os.path.abspath(log_path)
                ):
                    logging.getLogger().removeHandler(handler)
                    handler.close()


def main(argv=None):
    args = _parser().parse_args(argv)
    if (
        args.database != SAFE_DATABASE
        and args.confirmar_banco != args.database
    ):
        print(
            "[ERRO] Para testar outro banco, informe "
            f"--confirmar-banco {args.database}"
        )
        return 2

    target = db_core.DatabaseTarget("postgresql", args.database)
    try:
        recolhimentos_total, amostras_total = _test_data(target)
        _test_pages(args.database, target)
    except Exception as exc:
        print(f"[ERRO] {exc}")
        return 1

    print("Teste dos modulos operacionais no PostgreSQL")
    print("=" * 48)
    print(f"Banco: {args.database}")
    print(f"Recolhimentos temporarios listados: {recolhimentos_total}")
    print(f"Amostras temporarias listadas: {amostras_total}")
    print("Insercao e deduplicacao: OK")
    print("Agentes, filtros, resumos e datas: OK")
    print("Paginas e APIs: HTTP 200")
    print("Tabelas publicas: preservadas")
    print("\n[OK] Modulos homologados sem alterar os dados publicos.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
